// Code generated by protoc-gen-go. DO NOT EDIT.
// source: push.proto

package SimonProto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PushModelMsg struct {
	FromUser             string   `protobuf:"bytes,1,opt,name=fromUser,proto3" json:"fromUser,omitempty"`
	TargetUser           string   `protobuf:"bytes,2,opt,name=targetUser,proto3" json:"targetUser,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	SendTime             int32    `protobuf:"varint,4,opt,name=sendTime,proto3" json:"sendTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushModelMsg) Reset()         { *m = PushModelMsg{} }
func (m *PushModelMsg) String() string { return proto.CompactTextString(m) }
func (*PushModelMsg) ProtoMessage()    {}
func (*PushModelMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1e4bfd2e9d102bb, []int{0}
}

func (m *PushModelMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushModelMsg.Unmarshal(m, b)
}
func (m *PushModelMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushModelMsg.Marshal(b, m, deterministic)
}
func (m *PushModelMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushModelMsg.Merge(m, src)
}
func (m *PushModelMsg) XXX_Size() int {
	return xxx_messageInfo_PushModelMsg.Size(m)
}
func (m *PushModelMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PushModelMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PushModelMsg proto.InternalMessageInfo

func (m *PushModelMsg) GetFromUser() string {
	if m != nil {
		return m.FromUser
	}
	return ""
}

func (m *PushModelMsg) GetTargetUser() string {
	if m != nil {
		return m.TargetUser
	}
	return ""
}

func (m *PushModelMsg) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *PushModelMsg) GetSendTime() int32 {
	if m != nil {
		return m.SendTime
	}
	return 0
}

type PushOnChat struct {
	MsgList              []*PushModelMsg `protobuf:"bytes,1,rep,name=msgList,proto3" json:"msgList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PushOnChat) Reset()         { *m = PushOnChat{} }
func (m *PushOnChat) String() string { return proto.CompactTextString(m) }
func (*PushOnChat) ProtoMessage()    {}
func (*PushOnChat) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1e4bfd2e9d102bb, []int{1}
}

func (m *PushOnChat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushOnChat.Unmarshal(m, b)
}
func (m *PushOnChat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushOnChat.Marshal(b, m, deterministic)
}
func (m *PushOnChat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushOnChat.Merge(m, src)
}
func (m *PushOnChat) XXX_Size() int {
	return xxx_messageInfo_PushOnChat.Size(m)
}
func (m *PushOnChat) XXX_DiscardUnknown() {
	xxx_messageInfo_PushOnChat.DiscardUnknown(m)
}

var xxx_messageInfo_PushOnChat proto.InternalMessageInfo

func (m *PushOnChat) GetMsgList() []*PushModelMsg {
	if m != nil {
		return m.MsgList
	}
	return nil
}

func init() {
	proto.RegisterType((*PushModelMsg)(nil), "SimonProto.PushModelMsg")
	proto.RegisterType((*PushOnChat)(nil), "SimonProto.PushOnChat")
}

func init() { proto.RegisterFile("push.proto", fileDescriptor_d1e4bfd2e9d102bb) }

var fileDescriptor_d1e4bfd2e9d102bb = []byte{
	// 182 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x28, 0x2d, 0xce,
	0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x0a, 0xce, 0xcc, 0xcd, 0xcf, 0x0b, 0x00, 0xb1,
	0x95, 0x1a, 0x18, 0xb9, 0x78, 0x02, 0x4a, 0x8b, 0x33, 0x7c, 0xf3, 0x53, 0x52, 0x73, 0x7c, 0x8b,
	0xd3, 0x85, 0xa4, 0xb8, 0x38, 0xd2, 0x8a, 0xf2, 0x73, 0x43, 0x8b, 0x53, 0x8b, 0x24, 0x18, 0x15,
	0x18, 0x35, 0x38, 0x83, 0xe0, 0x7c, 0x21, 0x39, 0x2e, 0xae, 0x92, 0xc4, 0xa2, 0xf4, 0xd4, 0x12,
	0xb0, 0x2c, 0x13, 0x58, 0x16, 0x49, 0x44, 0x48, 0x82, 0x8b, 0x3d, 0x39, 0x3f, 0xaf, 0x24, 0x35,
	0xaf, 0x44, 0x82, 0x19, 0x2c, 0x09, 0xe3, 0x82, 0x4c, 0x2d, 0x4e, 0xcd, 0x4b, 0x09, 0xc9, 0xcc,
	0x4d, 0x95, 0x60, 0x51, 0x60, 0xd4, 0x60, 0x0d, 0x82, 0xf3, 0x95, 0x1c, 0xb8, 0xb8, 0x40, 0x2e,
	0xf0, 0xcf, 0x73, 0xce, 0x48, 0x2c, 0x11, 0x32, 0xe2, 0x62, 0xcf, 0x2d, 0x4e, 0xf7, 0xc9, 0x2c,
	0x2e, 0x91, 0x60, 0x54, 0x60, 0xd6, 0xe0, 0x36, 0x92, 0xd0, 0x43, 0x38, 0x57, 0x0f, 0xd9, 0xa9,
	0x41, 0x30, 0x85, 0x49, 0x6c, 0x60, 0x7f, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x27, 0xa7,
	0xa8, 0x9e, 0xe5, 0x00, 0x00, 0x00,
}
