// Code generated by protoc-gen-go. DO NOT EDIT.
// source: req.proto

package SimonProto

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReqGateGetConnector struct {
	Region               string   `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqGateGetConnector) Reset()         { *m = ReqGateGetConnector{} }
func (m *ReqGateGetConnector) String() string { return proto.CompactTextString(m) }
func (*ReqGateGetConnector) ProtoMessage()    {}
func (*ReqGateGetConnector) Descriptor() ([]byte, []int) {
	return fileDescriptor_a52bd445c288993d, []int{0}
}

func (m *ReqGateGetConnector) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqGateGetConnector.Unmarshal(m, b)
}
func (m *ReqGateGetConnector) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqGateGetConnector.Marshal(b, m, deterministic)
}
func (m *ReqGateGetConnector) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqGateGetConnector.Merge(m, src)
}
func (m *ReqGateGetConnector) XXX_Size() int {
	return xxx_messageInfo_ReqGateGetConnector.Size(m)
}
func (m *ReqGateGetConnector) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqGateGetConnector.DiscardUnknown(m)
}

var xxx_messageInfo_ReqGateGetConnector proto.InternalMessageInfo

func (m *ReqGateGetConnector) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

type ReqUserRegister struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	CFrom                string   `protobuf:"bytes,3,opt,name=cFrom,proto3" json:"cFrom,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqUserRegister) Reset()         { *m = ReqUserRegister{} }
func (m *ReqUserRegister) String() string { return proto.CompactTextString(m) }
func (*ReqUserRegister) ProtoMessage()    {}
func (*ReqUserRegister) Descriptor() ([]byte, []int) {
	return fileDescriptor_a52bd445c288993d, []int{1}
}

func (m *ReqUserRegister) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqUserRegister.Unmarshal(m, b)
}
func (m *ReqUserRegister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqUserRegister.Marshal(b, m, deterministic)
}
func (m *ReqUserRegister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqUserRegister.Merge(m, src)
}
func (m *ReqUserRegister) XXX_Size() int {
	return xxx_messageInfo_ReqUserRegister.Size(m)
}
func (m *ReqUserRegister) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqUserRegister.DiscardUnknown(m)
}

var xxx_messageInfo_ReqUserRegister proto.InternalMessageInfo

func (m *ReqUserRegister) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ReqUserRegister) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ReqUserRegister) GetCFrom() string {
	if m != nil {
		return m.CFrom
	}
	return ""
}

type ReqUserGetAreas struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqUserGetAreas) Reset()         { *m = ReqUserGetAreas{} }
func (m *ReqUserGetAreas) String() string { return proto.CompactTextString(m) }
func (*ReqUserGetAreas) ProtoMessage()    {}
func (*ReqUserGetAreas) Descriptor() ([]byte, []int) {
	return fileDescriptor_a52bd445c288993d, []int{2}
}

func (m *ReqUserGetAreas) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqUserGetAreas.Unmarshal(m, b)
}
func (m *ReqUserGetAreas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqUserGetAreas.Marshal(b, m, deterministic)
}
func (m *ReqUserGetAreas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqUserGetAreas.Merge(m, src)
}
func (m *ReqUserGetAreas) XXX_Size() int {
	return xxx_messageInfo_ReqUserGetAreas.Size(m)
}
func (m *ReqUserGetAreas) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqUserGetAreas.DiscardUnknown(m)
}

var xxx_messageInfo_ReqUserGetAreas proto.InternalMessageInfo

func (m *ReqUserGetAreas) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ReqUserGetAreas) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ReqUserSelectArea struct {
	AreaId               int32    `protobuf:"varint,1,opt,name=areaId,proto3" json:"areaId,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	AppVersion           string   `protobuf:"bytes,4,opt,name=appVersion,proto3" json:"appVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqUserSelectArea) Reset()         { *m = ReqUserSelectArea{} }
func (m *ReqUserSelectArea) String() string { return proto.CompactTextString(m) }
func (*ReqUserSelectArea) ProtoMessage()    {}
func (*ReqUserSelectArea) Descriptor() ([]byte, []int) {
	return fileDescriptor_a52bd445c288993d, []int{3}
}

func (m *ReqUserSelectArea) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqUserSelectArea.Unmarshal(m, b)
}
func (m *ReqUserSelectArea) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqUserSelectArea.Marshal(b, m, deterministic)
}
func (m *ReqUserSelectArea) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqUserSelectArea.Merge(m, src)
}
func (m *ReqUserSelectArea) XXX_Size() int {
	return xxx_messageInfo_ReqUserSelectArea.Size(m)
}
func (m *ReqUserSelectArea) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqUserSelectArea.DiscardUnknown(m)
}

var xxx_messageInfo_ReqUserSelectArea proto.InternalMessageInfo

func (m *ReqUserSelectArea) GetAreaId() int32 {
	if m != nil {
		return m.AreaId
	}
	return 0
}

func (m *ReqUserSelectArea) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ReqUserSelectArea) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ReqUserSelectArea) GetAppVersion() string {
	if m != nil {
		return m.AppVersion
	}
	return ""
}

func init() {
	proto.RegisterType((*ReqGateGetConnector)(nil), "SimonProto.ReqGateGetConnector")
	proto.RegisterType((*ReqUserRegister)(nil), "SimonProto.ReqUserRegister")
	proto.RegisterType((*ReqUserGetAreas)(nil), "SimonProto.ReqUserGetAreas")
	proto.RegisterType((*ReqUserSelectArea)(nil), "SimonProto.ReqUserSelectArea")
}

func init() { proto.RegisterFile("req.proto", fileDescriptor_a52bd445c288993d) }

var fileDescriptor_a52bd445c288993d = []byte{
	// 223 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x90, 0xb1, 0x4a, 0x04, 0x31,
	0x10, 0x86, 0xd9, 0x3b, 0xef, 0xf0, 0xa6, 0x11, 0xa3, 0xc8, 0x62, 0x21, 0x92, 0xca, 0x46, 0x1b,
	0x9f, 0x40, 0x04, 0x97, 0xeb, 0x24, 0x87, 0xb6, 0x12, 0xf7, 0x7e, 0x8e, 0x05, 0x37, 0x93, 0x9d,
	0x44, 0x7c, 0x00, 0x5f, 0x5c, 0x92, 0x8d, 0x8b, 0x5a, 0x58, 0x5c, 0x97, 0x2f, 0xff, 0xf0, 0x7f,
	0xcc, 0xd0, 0x4a, 0x30, 0xdc, 0x78, 0xe1, 0xc8, 0x8a, 0x36, 0x5d, 0xcf, 0xee, 0x31, 0xbd, 0xf5,
	0x35, 0x9d, 0x18, 0x0c, 0x8d, 0x8d, 0x68, 0x10, 0xef, 0xd9, 0x39, 0xb4, 0x91, 0x45, 0x9d, 0xd1,
	0x52, 0xb0, 0xeb, 0xd8, 0xd5, 0xd5, 0x65, 0x75, 0xb5, 0x32, 0x85, 0xf4, 0x0b, 0x1d, 0x19, 0x0c,
	0x4f, 0x01, 0x62, 0xb0, 0xeb, 0x42, 0x84, 0xa8, 0x73, 0x3a, 0x7c, 0x0f, 0x10, 0x67, 0x7b, 0x94,
	0xe1, 0x89, 0x53, 0xe6, 0x6d, 0x08, 0x1f, 0x2c, 0xdb, 0x7a, 0x36, 0x66, 0xdf, 0xac, 0x4e, 0x69,
	0xd1, 0x3e, 0x08, 0xf7, 0xf5, 0x3c, 0x07, 0x23, 0xe8, 0xf5, 0x24, 0x68, 0x10, 0xef, 0x04, 0x36,
	0xec, 0x2b, 0xd0, 0x9f, 0x15, 0x1d, 0x97, 0xae, 0x0d, 0xde, 0xd0, 0xe6, 0xba, 0xb4, 0x99, 0x15,
	0xd8, 0xf5, 0x36, 0x77, 0x2d, 0x4c, 0xa1, 0x5f, 0x96, 0xd9, 0x3f, 0x96, 0xf9, 0x9f, 0x35, 0x2e,
	0x88, 0xac, 0xf7, 0xcf, 0x90, 0x90, 0xae, 0x75, 0x90, 0xd3, 0x1f, 0x3f, 0xaf, 0xcb, 0x7c, 0xf3,
	0xdb, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd3, 0xec, 0x85, 0xf9, 0x80, 0x01, 0x00, 0x00,
}
