// Code generated by protoc-gen-go. DO NOT EDIT.
// source: push.proto

package gopb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//玩家准备发单个信息给所有人
type OnPlayerReady struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Select               []string `protobuf:"bytes,2,rep,name=select,proto3" json:"select,omitempty"`
	Gender               int32    `protobuf:"varint,3,opt,name=gender,proto3" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnPlayerReady) Reset()         { *m = OnPlayerReady{} }
func (m *OnPlayerReady) String() string { return proto.CompactTextString(m) }
func (*OnPlayerReady) ProtoMessage()    {}
func (*OnPlayerReady) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1e4bfd2e9d102bb, []int{0}
}

func (m *OnPlayerReady) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnPlayerReady.Unmarshal(m, b)
}
func (m *OnPlayerReady) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnPlayerReady.Marshal(b, m, deterministic)
}
func (m *OnPlayerReady) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnPlayerReady.Merge(m, src)
}
func (m *OnPlayerReady) XXX_Size() int {
	return xxx_messageInfo_OnPlayerReady.Size(m)
}
func (m *OnPlayerReady) XXX_DiscardUnknown() {
	xxx_messageInfo_OnPlayerReady.DiscardUnknown(m)
}

var xxx_messageInfo_OnPlayerReady proto.InternalMessageInfo

func (m *OnPlayerReady) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *OnPlayerReady) GetSelect() []string {
	if m != nil {
		return m.Select
	}
	return nil
}

func (m *OnPlayerReady) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

type OnGameEnd struct {
	Result               []*OnGameEnd_GameResult `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	Timestamp            int64                   `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	LuckyStar            *OnGameEnd_LuckyPlayer  `protobuf:"bytes,3,opt,name=LuckyStar,proto3" json:"LuckyStar,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *OnGameEnd) Reset()         { *m = OnGameEnd{} }
func (m *OnGameEnd) String() string { return proto.CompactTextString(m) }
func (*OnGameEnd) ProtoMessage()    {}
func (*OnGameEnd) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1e4bfd2e9d102bb, []int{1}
}

func (m *OnGameEnd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnGameEnd.Unmarshal(m, b)
}
func (m *OnGameEnd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnGameEnd.Marshal(b, m, deterministic)
}
func (m *OnGameEnd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnGameEnd.Merge(m, src)
}
func (m *OnGameEnd) XXX_Size() int {
	return xxx_messageInfo_OnGameEnd.Size(m)
}
func (m *OnGameEnd) XXX_DiscardUnknown() {
	xxx_messageInfo_OnGameEnd.DiscardUnknown(m)
}

var xxx_messageInfo_OnGameEnd proto.InternalMessageInfo

func (m *OnGameEnd) GetResult() []*OnGameEnd_GameResult {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *OnGameEnd) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *OnGameEnd) GetLuckyStar() *OnGameEnd_LuckyPlayer {
	if m != nil {
		return m.LuckyStar
	}
	return nil
}

type OnGameEnd_RoomAward struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CouponName           string   `protobuf:"bytes,2,opt,name=couponName,proto3" json:"couponName,omitempty"`
	CouponImg            string   `protobuf:"bytes,3,opt,name=couponImg,proto3" json:"couponImg,omitempty"`
	CouponDesc           string   `protobuf:"bytes,4,opt,name=couponDesc,proto3" json:"couponDesc,omitempty"`
	Aid                  int32    `protobuf:"varint,5,opt,name=aid,proto3" json:"aid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnGameEnd_RoomAward) Reset()         { *m = OnGameEnd_RoomAward{} }
func (m *OnGameEnd_RoomAward) String() string { return proto.CompactTextString(m) }
func (*OnGameEnd_RoomAward) ProtoMessage()    {}
func (*OnGameEnd_RoomAward) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1e4bfd2e9d102bb, []int{1, 0}
}

func (m *OnGameEnd_RoomAward) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnGameEnd_RoomAward.Unmarshal(m, b)
}
func (m *OnGameEnd_RoomAward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnGameEnd_RoomAward.Marshal(b, m, deterministic)
}
func (m *OnGameEnd_RoomAward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnGameEnd_RoomAward.Merge(m, src)
}
func (m *OnGameEnd_RoomAward) XXX_Size() int {
	return xxx_messageInfo_OnGameEnd_RoomAward.Size(m)
}
func (m *OnGameEnd_RoomAward) XXX_DiscardUnknown() {
	xxx_messageInfo_OnGameEnd_RoomAward.DiscardUnknown(m)
}

var xxx_messageInfo_OnGameEnd_RoomAward proto.InternalMessageInfo

func (m *OnGameEnd_RoomAward) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OnGameEnd_RoomAward) GetCouponName() string {
	if m != nil {
		return m.CouponName
	}
	return ""
}

func (m *OnGameEnd_RoomAward) GetCouponImg() string {
	if m != nil {
		return m.CouponImg
	}
	return ""
}

func (m *OnGameEnd_RoomAward) GetCouponDesc() string {
	if m != nil {
		return m.CouponDesc
	}
	return ""
}

func (m *OnGameEnd_RoomAward) GetAid() int32 {
	if m != nil {
		return m.Aid
	}
	return 0
}

type OnGameEnd_LuckyPlayer struct {
	Uid                  string               `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AvaUrl               string               `protobuf:"bytes,3,opt,name=avaUrl,proto3" json:"avaUrl,omitempty"`
	Award                *OnGameEnd_RoomAward `protobuf:"bytes,4,opt,name=award,proto3" json:"award,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *OnGameEnd_LuckyPlayer) Reset()         { *m = OnGameEnd_LuckyPlayer{} }
func (m *OnGameEnd_LuckyPlayer) String() string { return proto.CompactTextString(m) }
func (*OnGameEnd_LuckyPlayer) ProtoMessage()    {}
func (*OnGameEnd_LuckyPlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1e4bfd2e9d102bb, []int{1, 1}
}

func (m *OnGameEnd_LuckyPlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnGameEnd_LuckyPlayer.Unmarshal(m, b)
}
func (m *OnGameEnd_LuckyPlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnGameEnd_LuckyPlayer.Marshal(b, m, deterministic)
}
func (m *OnGameEnd_LuckyPlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnGameEnd_LuckyPlayer.Merge(m, src)
}
func (m *OnGameEnd_LuckyPlayer) XXX_Size() int {
	return xxx_messageInfo_OnGameEnd_LuckyPlayer.Size(m)
}
func (m *OnGameEnd_LuckyPlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_OnGameEnd_LuckyPlayer.DiscardUnknown(m)
}

var xxx_messageInfo_OnGameEnd_LuckyPlayer proto.InternalMessageInfo

func (m *OnGameEnd_LuckyPlayer) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *OnGameEnd_LuckyPlayer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OnGameEnd_LuckyPlayer) GetAvaUrl() string {
	if m != nil {
		return m.AvaUrl
	}
	return ""
}

func (m *OnGameEnd_LuckyPlayer) GetAward() *OnGameEnd_RoomAward {
	if m != nil {
		return m.Award
	}
	return nil
}

type OnGameEnd_GameResult struct {
	Uid                  string               `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Score                int32                `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	Hit                  int32                `protobuf:"varint,3,opt,name=hit,proto3" json:"hit,omitempty"`
	Perfect              int32                `protobuf:"varint,4,opt,name=perfect,proto3" json:"perfect,omitempty"`
	Star                 int32                `protobuf:"varint,5,opt,name=star,proto3" json:"star,omitempty"`
	Award                *OnGameEnd_RoomAward `protobuf:"bytes,6,opt,name=award,proto3" json:"award,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *OnGameEnd_GameResult) Reset()         { *m = OnGameEnd_GameResult{} }
func (m *OnGameEnd_GameResult) String() string { return proto.CompactTextString(m) }
func (*OnGameEnd_GameResult) ProtoMessage()    {}
func (*OnGameEnd_GameResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1e4bfd2e9d102bb, []int{1, 2}
}

func (m *OnGameEnd_GameResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnGameEnd_GameResult.Unmarshal(m, b)
}
func (m *OnGameEnd_GameResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnGameEnd_GameResult.Marshal(b, m, deterministic)
}
func (m *OnGameEnd_GameResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnGameEnd_GameResult.Merge(m, src)
}
func (m *OnGameEnd_GameResult) XXX_Size() int {
	return xxx_messageInfo_OnGameEnd_GameResult.Size(m)
}
func (m *OnGameEnd_GameResult) XXX_DiscardUnknown() {
	xxx_messageInfo_OnGameEnd_GameResult.DiscardUnknown(m)
}

var xxx_messageInfo_OnGameEnd_GameResult proto.InternalMessageInfo

func (m *OnGameEnd_GameResult) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *OnGameEnd_GameResult) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *OnGameEnd_GameResult) GetHit() int32 {
	if m != nil {
		return m.Hit
	}
	return 0
}

func (m *OnGameEnd_GameResult) GetPerfect() int32 {
	if m != nil {
		return m.Perfect
	}
	return 0
}

func (m *OnGameEnd_GameResult) GetStar() int32 {
	if m != nil {
		return m.Star
	}
	return 0
}

func (m *OnGameEnd_GameResult) GetAward() *OnGameEnd_RoomAward {
	if m != nil {
		return m.Award
	}
	return nil
}

//frame
type OnFrame struct {
	CurFrame             int32               `protobuf:"varint,1,opt,name=curFrame,proto3" json:"curFrame,omitempty"`
	Commands             []*OnFrame_FCommand `protobuf:"bytes,2,rep,name=commands,proto3" json:"commands,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *OnFrame) Reset()         { *m = OnFrame{} }
func (m *OnFrame) String() string { return proto.CompactTextString(m) }
func (*OnFrame) ProtoMessage()    {}
func (*OnFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1e4bfd2e9d102bb, []int{2}
}

func (m *OnFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnFrame.Unmarshal(m, b)
}
func (m *OnFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnFrame.Marshal(b, m, deterministic)
}
func (m *OnFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnFrame.Merge(m, src)
}
func (m *OnFrame) XXX_Size() int {
	return xxx_messageInfo_OnFrame.Size(m)
}
func (m *OnFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_OnFrame.DiscardUnknown(m)
}

var xxx_messageInfo_OnFrame proto.InternalMessageInfo

func (m *OnFrame) GetCurFrame() int32 {
	if m != nil {
		return m.CurFrame
	}
	return 0
}

func (m *OnFrame) GetCommands() []*OnFrame_FCommand {
	if m != nil {
		return m.Commands
	}
	return nil
}

type OnFrame_FCommand struct {
	ExFrame              int32    `protobuf:"varint,1,opt,name=exFrame,proto3" json:"exFrame,omitempty"`
	EpFrame              int32    `protobuf:"varint,2,opt,name=epFrame,proto3" json:"epFrame,omitempty"`
	Uid                  string   `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Ctype                int32    `protobuf:"varint,4,opt,name=ctype,proto3" json:"ctype,omitempty"`
	ParamList            []int32  `protobuf:"varint,5,rep,packed,name=paramList,proto3" json:"paramList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnFrame_FCommand) Reset()         { *m = OnFrame_FCommand{} }
func (m *OnFrame_FCommand) String() string { return proto.CompactTextString(m) }
func (*OnFrame_FCommand) ProtoMessage()    {}
func (*OnFrame_FCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1e4bfd2e9d102bb, []int{2, 0}
}

func (m *OnFrame_FCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnFrame_FCommand.Unmarshal(m, b)
}
func (m *OnFrame_FCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnFrame_FCommand.Marshal(b, m, deterministic)
}
func (m *OnFrame_FCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnFrame_FCommand.Merge(m, src)
}
func (m *OnFrame_FCommand) XXX_Size() int {
	return xxx_messageInfo_OnFrame_FCommand.Size(m)
}
func (m *OnFrame_FCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_OnFrame_FCommand.DiscardUnknown(m)
}

var xxx_messageInfo_OnFrame_FCommand proto.InternalMessageInfo

func (m *OnFrame_FCommand) GetExFrame() int32 {
	if m != nil {
		return m.ExFrame
	}
	return 0
}

func (m *OnFrame_FCommand) GetEpFrame() int32 {
	if m != nil {
		return m.EpFrame
	}
	return 0
}

func (m *OnFrame_FCommand) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *OnFrame_FCommand) GetCtype() int32 {
	if m != nil {
		return m.Ctype
	}
	return 0
}

func (m *OnFrame_FCommand) GetParamList() []int32 {
	if m != nil {
		return m.ParamList
	}
	return nil
}

type PushCommonArgs struct {
	Args                 []*PushCommonArgs_CommonArg `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *PushCommonArgs) Reset()         { *m = PushCommonArgs{} }
func (m *PushCommonArgs) String() string { return proto.CompactTextString(m) }
func (*PushCommonArgs) ProtoMessage()    {}
func (*PushCommonArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1e4bfd2e9d102bb, []int{3}
}

func (m *PushCommonArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushCommonArgs.Unmarshal(m, b)
}
func (m *PushCommonArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushCommonArgs.Marshal(b, m, deterministic)
}
func (m *PushCommonArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushCommonArgs.Merge(m, src)
}
func (m *PushCommonArgs) XXX_Size() int {
	return xxx_messageInfo_PushCommonArgs.Size(m)
}
func (m *PushCommonArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_PushCommonArgs.DiscardUnknown(m)
}

var xxx_messageInfo_PushCommonArgs proto.InternalMessageInfo

func (m *PushCommonArgs) GetArgs() []*PushCommonArgs_CommonArg {
	if m != nil {
		return m.Args
	}
	return nil
}

type PushCommonArgs_CommonArg struct {
	StrVal1              string   `protobuf:"bytes,1,opt,name=strVal1,proto3" json:"strVal1,omitempty"`
	StrVal2              string   `protobuf:"bytes,2,opt,name=strVal2,proto3" json:"strVal2,omitempty"`
	IntVal1              int32    `protobuf:"varint,3,opt,name=intVal1,proto3" json:"intVal1,omitempty"`
	IntVal2              int32    `protobuf:"varint,4,opt,name=intVal2,proto3" json:"intVal2,omitempty"`
	IntVal3              int32    `protobuf:"varint,5,opt,name=intVal3,proto3" json:"intVal3,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushCommonArgs_CommonArg) Reset()         { *m = PushCommonArgs_CommonArg{} }
func (m *PushCommonArgs_CommonArg) String() string { return proto.CompactTextString(m) }
func (*PushCommonArgs_CommonArg) ProtoMessage()    {}
func (*PushCommonArgs_CommonArg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1e4bfd2e9d102bb, []int{3, 0}
}

func (m *PushCommonArgs_CommonArg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushCommonArgs_CommonArg.Unmarshal(m, b)
}
func (m *PushCommonArgs_CommonArg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushCommonArgs_CommonArg.Marshal(b, m, deterministic)
}
func (m *PushCommonArgs_CommonArg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushCommonArgs_CommonArg.Merge(m, src)
}
func (m *PushCommonArgs_CommonArg) XXX_Size() int {
	return xxx_messageInfo_PushCommonArgs_CommonArg.Size(m)
}
func (m *PushCommonArgs_CommonArg) XXX_DiscardUnknown() {
	xxx_messageInfo_PushCommonArgs_CommonArg.DiscardUnknown(m)
}

var xxx_messageInfo_PushCommonArgs_CommonArg proto.InternalMessageInfo

func (m *PushCommonArgs_CommonArg) GetStrVal1() string {
	if m != nil {
		return m.StrVal1
	}
	return ""
}

func (m *PushCommonArgs_CommonArg) GetStrVal2() string {
	if m != nil {
		return m.StrVal2
	}
	return ""
}

func (m *PushCommonArgs_CommonArg) GetIntVal1() int32 {
	if m != nil {
		return m.IntVal1
	}
	return 0
}

func (m *PushCommonArgs_CommonArg) GetIntVal2() int32 {
	if m != nil {
		return m.IntVal2
	}
	return 0
}

func (m *PushCommonArgs_CommonArg) GetIntVal3() int32 {
	if m != nil {
		return m.IntVal3
	}
	return 0
}

type OnPlayerEnterFRoom struct {
	Player               *OnPlayerEnterFRoom_PlayerInfo `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	LeftTIme             int64                          `protobuf:"varint,2,opt,name=leftTIme,proto3" json:"leftTIme,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *OnPlayerEnterFRoom) Reset()         { *m = OnPlayerEnterFRoom{} }
func (m *OnPlayerEnterFRoom) String() string { return proto.CompactTextString(m) }
func (*OnPlayerEnterFRoom) ProtoMessage()    {}
func (*OnPlayerEnterFRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1e4bfd2e9d102bb, []int{4}
}

func (m *OnPlayerEnterFRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnPlayerEnterFRoom.Unmarshal(m, b)
}
func (m *OnPlayerEnterFRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnPlayerEnterFRoom.Marshal(b, m, deterministic)
}
func (m *OnPlayerEnterFRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnPlayerEnterFRoom.Merge(m, src)
}
func (m *OnPlayerEnterFRoom) XXX_Size() int {
	return xxx_messageInfo_OnPlayerEnterFRoom.Size(m)
}
func (m *OnPlayerEnterFRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_OnPlayerEnterFRoom.DiscardUnknown(m)
}

var xxx_messageInfo_OnPlayerEnterFRoom proto.InternalMessageInfo

func (m *OnPlayerEnterFRoom) GetPlayer() *OnPlayerEnterFRoom_PlayerInfo {
	if m != nil {
		return m.Player
	}
	return nil
}

func (m *OnPlayerEnterFRoom) GetLeftTIme() int64 {
	if m != nil {
		return m.LeftTIme
	}
	return 0
}

type OnPlayerEnterFRoom_PlayerInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AvaUrl               string   `protobuf:"bytes,3,opt,name=avaUrl,proto3" json:"avaUrl,omitempty"`
	IsReady              bool     `protobuf:"varint,4,opt,name=isReady,proto3" json:"isReady,omitempty"`
	Have                 []string `protobuf:"bytes,6,rep,name=have,proto3" json:"have,omitempty"`
	Select               []string `protobuf:"bytes,7,rep,name=select,proto3" json:"select,omitempty"`
	Gender               int32    `protobuf:"varint,8,opt,name=gender,proto3" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnPlayerEnterFRoom_PlayerInfo) Reset()         { *m = OnPlayerEnterFRoom_PlayerInfo{} }
func (m *OnPlayerEnterFRoom_PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*OnPlayerEnterFRoom_PlayerInfo) ProtoMessage()    {}
func (*OnPlayerEnterFRoom_PlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1e4bfd2e9d102bb, []int{4, 0}
}

func (m *OnPlayerEnterFRoom_PlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnPlayerEnterFRoom_PlayerInfo.Unmarshal(m, b)
}
func (m *OnPlayerEnterFRoom_PlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnPlayerEnterFRoom_PlayerInfo.Marshal(b, m, deterministic)
}
func (m *OnPlayerEnterFRoom_PlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnPlayerEnterFRoom_PlayerInfo.Merge(m, src)
}
func (m *OnPlayerEnterFRoom_PlayerInfo) XXX_Size() int {
	return xxx_messageInfo_OnPlayerEnterFRoom_PlayerInfo.Size(m)
}
func (m *OnPlayerEnterFRoom_PlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OnPlayerEnterFRoom_PlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OnPlayerEnterFRoom_PlayerInfo proto.InternalMessageInfo

func (m *OnPlayerEnterFRoom_PlayerInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *OnPlayerEnterFRoom_PlayerInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OnPlayerEnterFRoom_PlayerInfo) GetAvaUrl() string {
	if m != nil {
		return m.AvaUrl
	}
	return ""
}

func (m *OnPlayerEnterFRoom_PlayerInfo) GetIsReady() bool {
	if m != nil {
		return m.IsReady
	}
	return false
}

func (m *OnPlayerEnterFRoom_PlayerInfo) GetHave() []string {
	if m != nil {
		return m.Have
	}
	return nil
}

func (m *OnPlayerEnterFRoom_PlayerInfo) GetSelect() []string {
	if m != nil {
		return m.Select
	}
	return nil
}

func (m *OnPlayerEnterFRoom_PlayerInfo) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

type OnRefreshWaitings struct {
	Waitings             []*OnRefreshWaitings_PlayerInfo `protobuf:"bytes,1,rep,name=waitings,proto3" json:"waitings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *OnRefreshWaitings) Reset()         { *m = OnRefreshWaitings{} }
func (m *OnRefreshWaitings) String() string { return proto.CompactTextString(m) }
func (*OnRefreshWaitings) ProtoMessage()    {}
func (*OnRefreshWaitings) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1e4bfd2e9d102bb, []int{5}
}

func (m *OnRefreshWaitings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnRefreshWaitings.Unmarshal(m, b)
}
func (m *OnRefreshWaitings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnRefreshWaitings.Marshal(b, m, deterministic)
}
func (m *OnRefreshWaitings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnRefreshWaitings.Merge(m, src)
}
func (m *OnRefreshWaitings) XXX_Size() int {
	return xxx_messageInfo_OnRefreshWaitings.Size(m)
}
func (m *OnRefreshWaitings) XXX_DiscardUnknown() {
	xxx_messageInfo_OnRefreshWaitings.DiscardUnknown(m)
}

var xxx_messageInfo_OnRefreshWaitings proto.InternalMessageInfo

func (m *OnRefreshWaitings) GetWaitings() []*OnRefreshWaitings_PlayerInfo {
	if m != nil {
		return m.Waitings
	}
	return nil
}

type OnRefreshWaitings_PlayerInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AvaUrl               string   `protobuf:"bytes,3,opt,name=avaUrl,proto3" json:"avaUrl,omitempty"`
	IsReady              bool     `protobuf:"varint,4,opt,name=isReady,proto3" json:"isReady,omitempty"`
	Have                 []string `protobuf:"bytes,6,rep,name=have,proto3" json:"have,omitempty"`
	Select               []string `protobuf:"bytes,7,rep,name=select,proto3" json:"select,omitempty"`
	Gender               int32    `protobuf:"varint,8,opt,name=gender,proto3" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnRefreshWaitings_PlayerInfo) Reset()         { *m = OnRefreshWaitings_PlayerInfo{} }
func (m *OnRefreshWaitings_PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*OnRefreshWaitings_PlayerInfo) ProtoMessage()    {}
func (*OnRefreshWaitings_PlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1e4bfd2e9d102bb, []int{5, 0}
}

func (m *OnRefreshWaitings_PlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnRefreshWaitings_PlayerInfo.Unmarshal(m, b)
}
func (m *OnRefreshWaitings_PlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnRefreshWaitings_PlayerInfo.Marshal(b, m, deterministic)
}
func (m *OnRefreshWaitings_PlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnRefreshWaitings_PlayerInfo.Merge(m, src)
}
func (m *OnRefreshWaitings_PlayerInfo) XXX_Size() int {
	return xxx_messageInfo_OnRefreshWaitings_PlayerInfo.Size(m)
}
func (m *OnRefreshWaitings_PlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OnRefreshWaitings_PlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OnRefreshWaitings_PlayerInfo proto.InternalMessageInfo

func (m *OnRefreshWaitings_PlayerInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *OnRefreshWaitings_PlayerInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OnRefreshWaitings_PlayerInfo) GetAvaUrl() string {
	if m != nil {
		return m.AvaUrl
	}
	return ""
}

func (m *OnRefreshWaitings_PlayerInfo) GetIsReady() bool {
	if m != nil {
		return m.IsReady
	}
	return false
}

func (m *OnRefreshWaitings_PlayerInfo) GetHave() []string {
	if m != nil {
		return m.Have
	}
	return nil
}

func (m *OnRefreshWaitings_PlayerInfo) GetSelect() []string {
	if m != nil {
		return m.Select
	}
	return nil
}

func (m *OnRefreshWaitings_PlayerInfo) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

type OnPlayerWatch struct {
	Player               *OnPlayerWatch_PlayerInfo `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	TarUid               string                    `protobuf:"bytes,2,opt,name=tarUid,proto3" json:"tarUid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *OnPlayerWatch) Reset()         { *m = OnPlayerWatch{} }
func (m *OnPlayerWatch) String() string { return proto.CompactTextString(m) }
func (*OnPlayerWatch) ProtoMessage()    {}
func (*OnPlayerWatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1e4bfd2e9d102bb, []int{6}
}

func (m *OnPlayerWatch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnPlayerWatch.Unmarshal(m, b)
}
func (m *OnPlayerWatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnPlayerWatch.Marshal(b, m, deterministic)
}
func (m *OnPlayerWatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnPlayerWatch.Merge(m, src)
}
func (m *OnPlayerWatch) XXX_Size() int {
	return xxx_messageInfo_OnPlayerWatch.Size(m)
}
func (m *OnPlayerWatch) XXX_DiscardUnknown() {
	xxx_messageInfo_OnPlayerWatch.DiscardUnknown(m)
}

var xxx_messageInfo_OnPlayerWatch proto.InternalMessageInfo

func (m *OnPlayerWatch) GetPlayer() *OnPlayerWatch_PlayerInfo {
	if m != nil {
		return m.Player
	}
	return nil
}

func (m *OnPlayerWatch) GetTarUid() string {
	if m != nil {
		return m.TarUid
	}
	return ""
}

type OnPlayerWatch_PlayerInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AvaUrl               string   `protobuf:"bytes,3,opt,name=avaUrl,proto3" json:"avaUrl,omitempty"`
	IsReady              bool     `protobuf:"varint,4,opt,name=isReady,proto3" json:"isReady,omitempty"`
	Have                 []string `protobuf:"bytes,6,rep,name=have,proto3" json:"have,omitempty"`
	Select               []string `protobuf:"bytes,7,rep,name=select,proto3" json:"select,omitempty"`
	Gender               int32    `protobuf:"varint,8,opt,name=gender,proto3" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnPlayerWatch_PlayerInfo) Reset()         { *m = OnPlayerWatch_PlayerInfo{} }
func (m *OnPlayerWatch_PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*OnPlayerWatch_PlayerInfo) ProtoMessage()    {}
func (*OnPlayerWatch_PlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1e4bfd2e9d102bb, []int{6, 0}
}

func (m *OnPlayerWatch_PlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnPlayerWatch_PlayerInfo.Unmarshal(m, b)
}
func (m *OnPlayerWatch_PlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnPlayerWatch_PlayerInfo.Marshal(b, m, deterministic)
}
func (m *OnPlayerWatch_PlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnPlayerWatch_PlayerInfo.Merge(m, src)
}
func (m *OnPlayerWatch_PlayerInfo) XXX_Size() int {
	return xxx_messageInfo_OnPlayerWatch_PlayerInfo.Size(m)
}
func (m *OnPlayerWatch_PlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OnPlayerWatch_PlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OnPlayerWatch_PlayerInfo proto.InternalMessageInfo

func (m *OnPlayerWatch_PlayerInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *OnPlayerWatch_PlayerInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OnPlayerWatch_PlayerInfo) GetAvaUrl() string {
	if m != nil {
		return m.AvaUrl
	}
	return ""
}

func (m *OnPlayerWatch_PlayerInfo) GetIsReady() bool {
	if m != nil {
		return m.IsReady
	}
	return false
}

func (m *OnPlayerWatch_PlayerInfo) GetHave() []string {
	if m != nil {
		return m.Have
	}
	return nil
}

func (m *OnPlayerWatch_PlayerInfo) GetSelect() []string {
	if m != nil {
		return m.Select
	}
	return nil
}

func (m *OnPlayerWatch_PlayerInfo) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

type OnPlayerClientEnter struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnPlayerClientEnter) Reset()         { *m = OnPlayerClientEnter{} }
func (m *OnPlayerClientEnter) String() string { return proto.CompactTextString(m) }
func (*OnPlayerClientEnter) ProtoMessage()    {}
func (*OnPlayerClientEnter) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1e4bfd2e9d102bb, []int{7}
}

func (m *OnPlayerClientEnter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnPlayerClientEnter.Unmarshal(m, b)
}
func (m *OnPlayerClientEnter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnPlayerClientEnter.Marshal(b, m, deterministic)
}
func (m *OnPlayerClientEnter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnPlayerClientEnter.Merge(m, src)
}
func (m *OnPlayerClientEnter) XXX_Size() int {
	return xxx_messageInfo_OnPlayerClientEnter.Size(m)
}
func (m *OnPlayerClientEnter) XXX_DiscardUnknown() {
	xxx_messageInfo_OnPlayerClientEnter.DiscardUnknown(m)
}

var xxx_messageInfo_OnPlayerClientEnter proto.InternalMessageInfo

func (m *OnPlayerClientEnter) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type OnPlayerUpvote struct {
	Upvotes              []*OnPlayerUpvote_Upvote `protobuf:"bytes,1,rep,name=upvotes,proto3" json:"upvotes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *OnPlayerUpvote) Reset()         { *m = OnPlayerUpvote{} }
func (m *OnPlayerUpvote) String() string { return proto.CompactTextString(m) }
func (*OnPlayerUpvote) ProtoMessage()    {}
func (*OnPlayerUpvote) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1e4bfd2e9d102bb, []int{8}
}

func (m *OnPlayerUpvote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnPlayerUpvote.Unmarshal(m, b)
}
func (m *OnPlayerUpvote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnPlayerUpvote.Marshal(b, m, deterministic)
}
func (m *OnPlayerUpvote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnPlayerUpvote.Merge(m, src)
}
func (m *OnPlayerUpvote) XXX_Size() int {
	return xxx_messageInfo_OnPlayerUpvote.Size(m)
}
func (m *OnPlayerUpvote) XXX_DiscardUnknown() {
	xxx_messageInfo_OnPlayerUpvote.DiscardUnknown(m)
}

var xxx_messageInfo_OnPlayerUpvote proto.InternalMessageInfo

func (m *OnPlayerUpvote) GetUpvotes() []*OnPlayerUpvote_Upvote {
	if m != nil {
		return m.Upvotes
	}
	return nil
}

type OnPlayerUpvote_Upvote struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	TarUid               string   `protobuf:"bytes,2,opt,name=tarUid,proto3" json:"tarUid,omitempty"`
	Num                  int32    `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
	Total                int32    `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnPlayerUpvote_Upvote) Reset()         { *m = OnPlayerUpvote_Upvote{} }
func (m *OnPlayerUpvote_Upvote) String() string { return proto.CompactTextString(m) }
func (*OnPlayerUpvote_Upvote) ProtoMessage()    {}
func (*OnPlayerUpvote_Upvote) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1e4bfd2e9d102bb, []int{8, 0}
}

func (m *OnPlayerUpvote_Upvote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnPlayerUpvote_Upvote.Unmarshal(m, b)
}
func (m *OnPlayerUpvote_Upvote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnPlayerUpvote_Upvote.Marshal(b, m, deterministic)
}
func (m *OnPlayerUpvote_Upvote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnPlayerUpvote_Upvote.Merge(m, src)
}
func (m *OnPlayerUpvote_Upvote) XXX_Size() int {
	return xxx_messageInfo_OnPlayerUpvote_Upvote.Size(m)
}
func (m *OnPlayerUpvote_Upvote) XXX_DiscardUnknown() {
	xxx_messageInfo_OnPlayerUpvote_Upvote.DiscardUnknown(m)
}

var xxx_messageInfo_OnPlayerUpvote_Upvote proto.InternalMessageInfo

func (m *OnPlayerUpvote_Upvote) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *OnPlayerUpvote_Upvote) GetTarUid() string {
	if m != nil {
		return m.TarUid
	}
	return ""
}

func (m *OnPlayerUpvote_Upvote) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *OnPlayerUpvote_Upvote) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type PlayerInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AvaUrl               string   `protobuf:"bytes,3,opt,name=avaUrl,proto3" json:"avaUrl,omitempty"`
	IsReady              bool     `protobuf:"varint,4,opt,name=isReady,proto3" json:"isReady,omitempty"`
	Have                 []string `protobuf:"bytes,6,rep,name=have,proto3" json:"have,omitempty"`
	Select               []string `protobuf:"bytes,7,rep,name=select,proto3" json:"select,omitempty"`
	Gender               int32    `protobuf:"varint,8,opt,name=gender,proto3" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerInfo) Reset()         { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()    {}
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1e4bfd2e9d102bb, []int{9}
}

func (m *PlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerInfo.Unmarshal(m, b)
}
func (m *PlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerInfo.Marshal(b, m, deterministic)
}
func (m *PlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerInfo.Merge(m, src)
}
func (m *PlayerInfo) XXX_Size() int {
	return xxx_messageInfo_PlayerInfo.Size(m)
}
func (m *PlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerInfo proto.InternalMessageInfo

func (m *PlayerInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *PlayerInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PlayerInfo) GetAvaUrl() string {
	if m != nil {
		return m.AvaUrl
	}
	return ""
}

func (m *PlayerInfo) GetIsReady() bool {
	if m != nil {
		return m.IsReady
	}
	return false
}

func (m *PlayerInfo) GetHave() []string {
	if m != nil {
		return m.Have
	}
	return nil
}

func (m *PlayerInfo) GetSelect() []string {
	if m != nil {
		return m.Select
	}
	return nil
}

func (m *PlayerInfo) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

//--------------client proto--------------
type OnSkipSyncCommandData struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Ctype                string   `protobuf:"bytes,2,opt,name=ctype,proto3" json:"ctype,omitempty"`
	X                    int32    `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	Dir                  int32    `protobuf:"varint,5,opt,name=dir,proto3" json:"dir,omitempty"`
	State                int32    `protobuf:"varint,6,opt,name=state,proto3" json:"state,omitempty"`
	BoxSpeed             int32    `protobuf:"varint,7,opt,name=boxSpeed,proto3" json:"boxSpeed,omitempty"`
	Score                int32    `protobuf:"varint,8,opt,name=score,proto3" json:"score,omitempty"`
	Time                 int32    `protobuf:"varint,9,opt,name=time,proto3" json:"time,omitempty"`
	ReqID                int32    `protobuf:"varint,10,opt,name=reqID,proto3" json:"reqID,omitempty"`
	JumpTime             int32    `protobuf:"varint,11,opt,name=jumpTime,proto3" json:"jumpTime,omitempty"`
	StopTime             int32    `protobuf:"varint,12,opt,name=stopTime,proto3" json:"stopTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnSkipSyncCommandData) Reset()         { *m = OnSkipSyncCommandData{} }
func (m *OnSkipSyncCommandData) String() string { return proto.CompactTextString(m) }
func (*OnSkipSyncCommandData) ProtoMessage()    {}
func (*OnSkipSyncCommandData) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1e4bfd2e9d102bb, []int{10}
}

func (m *OnSkipSyncCommandData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnSkipSyncCommandData.Unmarshal(m, b)
}
func (m *OnSkipSyncCommandData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnSkipSyncCommandData.Marshal(b, m, deterministic)
}
func (m *OnSkipSyncCommandData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnSkipSyncCommandData.Merge(m, src)
}
func (m *OnSkipSyncCommandData) XXX_Size() int {
	return xxx_messageInfo_OnSkipSyncCommandData.Size(m)
}
func (m *OnSkipSyncCommandData) XXX_DiscardUnknown() {
	xxx_messageInfo_OnSkipSyncCommandData.DiscardUnknown(m)
}

var xxx_messageInfo_OnSkipSyncCommandData proto.InternalMessageInfo

func (m *OnSkipSyncCommandData) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *OnSkipSyncCommandData) GetCtype() string {
	if m != nil {
		return m.Ctype
	}
	return ""
}

func (m *OnSkipSyncCommandData) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *OnSkipSyncCommandData) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *OnSkipSyncCommandData) GetDir() int32 {
	if m != nil {
		return m.Dir
	}
	return 0
}

func (m *OnSkipSyncCommandData) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *OnSkipSyncCommandData) GetBoxSpeed() int32 {
	if m != nil {
		return m.BoxSpeed
	}
	return 0
}

func (m *OnSkipSyncCommandData) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *OnSkipSyncCommandData) GetTime() int32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *OnSkipSyncCommandData) GetReqID() int32 {
	if m != nil {
		return m.ReqID
	}
	return 0
}

func (m *OnSkipSyncCommandData) GetJumpTime() int32 {
	if m != nil {
		return m.JumpTime
	}
	return 0
}

func (m *OnSkipSyncCommandData) GetStopTime() int32 {
	if m != nil {
		return m.StopTime
	}
	return 0
}

//跳一跳房间状态
type OnRoomState struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	BoxCount             int32    `protobuf:"varint,2,opt,name=boxCount,proto3" json:"boxCount,omitempty"`
	Score                int32    `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	Popularity           int32    `protobuf:"varint,4,opt,name=popularity,proto3" json:"popularity,omitempty"`
	LeftGameTime         int32    `protobuf:"varint,5,opt,name=leftGameTime,proto3" json:"leftGameTime,omitempty"`
	MaxPopularityUid     string   `protobuf:"bytes,6,opt,name=maxPopularityUid,proto3" json:"maxPopularityUid,omitempty"`
	PlayerIndex          int32    `protobuf:"varint,7,opt,name=playerIndex,proto3" json:"playerIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnRoomState) Reset()         { *m = OnRoomState{} }
func (m *OnRoomState) String() string { return proto.CompactTextString(m) }
func (*OnRoomState) ProtoMessage()    {}
func (*OnRoomState) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1e4bfd2e9d102bb, []int{11}
}

func (m *OnRoomState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnRoomState.Unmarshal(m, b)
}
func (m *OnRoomState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnRoomState.Marshal(b, m, deterministic)
}
func (m *OnRoomState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnRoomState.Merge(m, src)
}
func (m *OnRoomState) XXX_Size() int {
	return xxx_messageInfo_OnRoomState.Size(m)
}
func (m *OnRoomState) XXX_DiscardUnknown() {
	xxx_messageInfo_OnRoomState.DiscardUnknown(m)
}

var xxx_messageInfo_OnRoomState proto.InternalMessageInfo

func (m *OnRoomState) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *OnRoomState) GetBoxCount() int32 {
	if m != nil {
		return m.BoxCount
	}
	return 0
}

func (m *OnRoomState) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *OnRoomState) GetPopularity() int32 {
	if m != nil {
		return m.Popularity
	}
	return 0
}

func (m *OnRoomState) GetLeftGameTime() int32 {
	if m != nil {
		return m.LeftGameTime
	}
	return 0
}

func (m *OnRoomState) GetMaxPopularityUid() string {
	if m != nil {
		return m.MaxPopularityUid
	}
	return ""
}

func (m *OnRoomState) GetPlayerIndex() int32 {
	if m != nil {
		return m.PlayerIndex
	}
	return 0
}

func init() {
	proto.RegisterType((*OnPlayerReady)(nil), "gopb.OnPlayerReady")
	proto.RegisterType((*OnGameEnd)(nil), "gopb.OnGameEnd")
	proto.RegisterType((*OnGameEnd_RoomAward)(nil), "gopb.OnGameEnd.RoomAward")
	proto.RegisterType((*OnGameEnd_LuckyPlayer)(nil), "gopb.OnGameEnd.LuckyPlayer")
	proto.RegisterType((*OnGameEnd_GameResult)(nil), "gopb.OnGameEnd.GameResult")
	proto.RegisterType((*OnFrame)(nil), "gopb.OnFrame")
	proto.RegisterType((*OnFrame_FCommand)(nil), "gopb.OnFrame.FCommand")
	proto.RegisterType((*PushCommonArgs)(nil), "gopb.PushCommonArgs")
	proto.RegisterType((*PushCommonArgs_CommonArg)(nil), "gopb.PushCommonArgs.CommonArg")
	proto.RegisterType((*OnPlayerEnterFRoom)(nil), "gopb.OnPlayerEnterFRoom")
	proto.RegisterType((*OnPlayerEnterFRoom_PlayerInfo)(nil), "gopb.OnPlayerEnterFRoom.PlayerInfo")
	proto.RegisterType((*OnRefreshWaitings)(nil), "gopb.OnRefreshWaitings")
	proto.RegisterType((*OnRefreshWaitings_PlayerInfo)(nil), "gopb.OnRefreshWaitings.PlayerInfo")
	proto.RegisterType((*OnPlayerWatch)(nil), "gopb.OnPlayerWatch")
	proto.RegisterType((*OnPlayerWatch_PlayerInfo)(nil), "gopb.OnPlayerWatch.PlayerInfo")
	proto.RegisterType((*OnPlayerClientEnter)(nil), "gopb.OnPlayerClientEnter")
	proto.RegisterType((*OnPlayerUpvote)(nil), "gopb.OnPlayerUpvote")
	proto.RegisterType((*OnPlayerUpvote_Upvote)(nil), "gopb.OnPlayerUpvote.Upvote")
	proto.RegisterType((*PlayerInfo)(nil), "gopb.PlayerInfo")
	proto.RegisterType((*OnSkipSyncCommandData)(nil), "gopb.OnSkipSyncCommandData")
	proto.RegisterType((*OnRoomState)(nil), "gopb.OnRoomState")
}

func init() { proto.RegisterFile("push.proto", fileDescriptor_d1e4bfd2e9d102bb) }

var fileDescriptor_d1e4bfd2e9d102bb = []byte{
	// 1001 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x56, 0x4f, 0x6b, 0x24, 0x45,
	0x14, 0xa7, 0xe7, 0x5f, 0xa6, 0xdf, 0xc4, 0xb0, 0x96, 0x1a, 0xda, 0x59, 0x09, 0x43, 0x7b, 0x70,
	0xf0, 0x30, 0x62, 0x2f, 0x0a, 0x22, 0x08, 0x4b, 0xb2, 0x91, 0xc0, 0xe2, 0xc4, 0xca, 0xc6, 0x05,
	0x6f, 0x95, 0xee, 0xca, 0x4c, 0xbb, 0xd3, 0xd5, 0x6d, 0x75, 0x75, 0x76, 0x06, 0x3c, 0x7a, 0x52,
	0x3c, 0xeb, 0x5d, 0x04, 0x3f, 0x8c, 0x47, 0x3f, 0x80, 0xe0, 0xf7, 0x10, 0x79, 0xf5, 0xa7, 0xbb,
	0x27, 0x19, 0x41, 0xd8, 0x53, 0x4e, 0xf3, 0x7e, 0xaf, 0x7e, 0x55, 0xf5, 0xde, 0xaf, 0xde, 0xbc,
	0xd7, 0x00, 0x45, 0x55, 0x2e, 0x67, 0x85, 0xcc, 0x55, 0x4e, 0x7a, 0x8b, 0xbc, 0xb8, 0x0a, 0xbf,
	0x84, 0xd7, 0xe6, 0xe2, 0x7c, 0xc5, 0x36, 0x5c, 0x52, 0xce, 0x92, 0x0d, 0x79, 0x00, 0xdd, 0x2a,
	0x4d, 0x02, 0x6f, 0xe2, 0x4d, 0x7d, 0x8a, 0x26, 0x39, 0x84, 0x41, 0xc9, 0x57, 0x3c, 0x56, 0x41,
	0x67, 0xd2, 0x9d, 0xfa, 0xd4, 0x22, 0xf4, 0x2f, 0xb8, 0x48, 0xb8, 0x0c, 0xba, 0x13, 0x6f, 0xda,
	0xa7, 0x16, 0x85, 0x7f, 0xf4, 0xc0, 0x9f, 0x8b, 0xcf, 0x59, 0xc6, 0x9f, 0x88, 0x84, 0x44, 0x30,
	0x90, 0xbc, 0xac, 0x56, 0x2a, 0xf0, 0x26, 0xdd, 0xe9, 0x28, 0x1a, 0xcf, 0xf0, 0xde, 0x59, 0x4d,
	0x98, 0xe1, 0x2f, 0xd5, 0x0c, 0x6a, 0x99, 0xe4, 0x1d, 0xf0, 0x55, 0x9a, 0xf1, 0x52, 0xb1, 0xac,
	0x08, 0x3a, 0x13, 0x6f, 0xda, 0xa5, 0x8d, 0x83, 0x7c, 0x02, 0xfe, 0xd3, 0x2a, 0x7e, 0xb1, 0xb9,
	0x50, 0xcc, 0x5c, 0x3d, 0x8a, 0x1e, 0xde, 0x3e, 0x54, 0x13, 0x6c, 0x5a, 0x0d, 0x7b, 0xfc, 0xa3,
	0x07, 0x3e, 0xcd, 0xf3, 0xec, 0xf1, 0x4b, 0x26, 0x13, 0x72, 0x00, 0x9d, 0x3a, 0xd3, 0x4e, 0x9a,
	0x90, 0x23, 0x80, 0x38, 0xaf, 0x8a, 0x5c, 0x7c, 0xc1, 0x32, 0xae, 0xef, 0xf5, 0x69, 0xcb, 0x83,
	0x61, 0x19, 0x74, 0x96, 0x2d, 0xf4, 0xc5, 0x3e, 0x6d, 0x1c, 0xcd, 0xee, 0x13, 0x5e, 0xc6, 0x41,
	0xaf, 0xbd, 0x1b, 0x3d, 0x28, 0x2c, 0x4b, 0x93, 0xa0, 0xaf, 0xb5, 0x42, 0x73, 0xfc, 0x1d, 0x8c,
	0x5a, 0x71, 0xee, 0x50, 0x9e, 0x40, 0x4f, 0x34, 0xa1, 0x68, 0x1b, 0x55, 0x67, 0x37, 0xec, 0x52,
	0xae, 0x6c, 0x04, 0x16, 0x91, 0x0f, 0xa0, 0xcf, 0x30, 0x2b, 0x7d, 0xf3, 0x28, 0x7a, 0xfb, 0xb6,
	0x22, 0x75, 0xda, 0xd4, 0xf0, 0xc6, 0xbf, 0x79, 0x00, 0x8d, 0xf6, 0x3b, 0x6e, 0x7f, 0x13, 0xfa,
	0x65, 0x9c, 0x4b, 0x73, 0x7d, 0x9f, 0x1a, 0x80, 0xbc, 0x65, 0xaa, 0xec, 0x93, 0xa3, 0x49, 0x02,
	0xd8, 0x2b, 0xb8, 0xbc, 0xc6, 0x02, 0xe9, 0x69, 0xaf, 0x83, 0x18, 0x7f, 0x89, 0x8f, 0x64, 0x72,
	0xd6, 0x76, 0x13, 0xe7, 0xe0, 0xff, 0xc5, 0x19, 0xfe, 0xe5, 0xc1, 0xde, 0x5c, 0x9c, 0x4a, 0x4c,
	0x7e, 0x0c, 0xc3, 0xb8, 0x92, 0xda, 0xd6, 0x91, 0xf6, 0x69, 0x8d, 0x49, 0x04, 0xc3, 0x38, 0xcf,
	0x32, 0x26, 0x92, 0x52, 0x17, 0xea, 0x28, 0x3a, 0x74, 0x67, 0x6b, 0xc2, 0xec, 0xf4, 0xd8, 0x2c,
	0xd3, 0x9a, 0x37, 0xfe, 0xde, 0x83, 0xa1, 0x73, 0x63, 0x1e, 0x7c, 0xdd, 0x3e, 0xdb, 0x41, 0xbd,
	0x52, 0x98, 0x95, 0x8e, 0x5d, 0x31, 0xd0, 0xa9, 0xd6, 0xdd, 0x52, 0x2d, 0x56, 0x9b, 0x82, 0x5b,
	0x2d, 0x0c, 0xc0, 0xd2, 0x29, 0x98, 0x64, 0xd9, 0xd3, 0xb4, 0x54, 0x41, 0x7f, 0xd2, 0x9d, 0xf6,
	0x69, 0xe3, 0x08, 0xff, 0xf4, 0xe0, 0xe0, 0xbc, 0x2a, 0x97, 0x18, 0x49, 0x2e, 0x1e, 0xcb, 0x45,
	0x49, 0x22, 0xe8, 0x31, 0xb9, 0x28, 0xed, 0x9f, 0xe6, 0xc8, 0x64, 0xb2, 0xcd, 0x99, 0xd5, 0x26,
	0xd5, 0xdc, 0xf1, 0x4f, 0x1e, 0xf8, 0xb5, 0x0f, 0x83, 0x2e, 0x95, 0xfc, 0x8a, 0xad, 0x3e, 0xb4,
	0x8f, 0xea, 0x60, 0xb3, 0x12, 0xd9, 0xca, 0x72, 0x10, 0x57, 0x52, 0xa1, 0xf4, 0x1e, 0xf3, 0xc0,
	0x0e, 0x36, 0x2b, 0x91, 0x7b, 0x64, 0x0b, 0x9b, 0x95, 0x47, 0xf6, 0x9d, 0x1d, 0x0c, 0x7f, 0xe9,
	0x00, 0x71, 0xcd, 0xe5, 0x89, 0x50, 0x5c, 0x9e, 0xe2, 0xe3, 0x92, 0x4f, 0x61, 0x50, 0x68, 0x9f,
	0x8e, 0x6b, 0x14, 0xbd, 0xeb, 0x9e, 0xe9, 0x36, 0x73, 0x66, 0x1c, 0x67, 0xe2, 0x3a, 0xa7, 0x76,
	0x0b, 0x56, 0xc0, 0x8a, 0x5f, 0xab, 0x67, 0x67, 0xf6, 0x2d, 0xba, 0xb4, 0xc6, 0xe3, 0xdf, 0x3d,
	0x80, 0x66, 0xcb, 0x2b, 0xfe, 0x9f, 0x30, 0xad, 0x52, 0xb7, 0x44, 0x9d, 0xf0, 0x90, 0x3a, 0x88,
	0xa7, 0x2c, 0xd9, 0x0d, 0x0f, 0x06, 0xba, 0x1b, 0x6a, 0xbb, 0xd5, 0x23, 0xf7, 0xfe, 0xa3, 0x47,
	0x0e, 0xb7, 0x7a, 0xe4, 0x3f, 0x1e, 0xbc, 0x3e, 0x17, 0x94, 0x5f, 0x4b, 0x5e, 0x2e, 0x9f, 0xb3,
	0x54, 0xa5, 0x62, 0x51, 0x92, 0xcf, 0x60, 0xf8, 0xd2, 0xda, 0xf6, 0xe1, 0x43, 0xa7, 0xcd, 0x2d,
	0x6a, 0x5b, 0x9a, 0x7a, 0xcf, 0x7d, 0x12, 0xe0, 0x87, 0x4e, 0x33, 0x78, 0x9e, 0x33, 0x15, 0x2f,
	0xc9, 0xc7, 0xb7, 0xca, 0xe2, 0x68, 0xbb, 0x2c, 0x34, 0x69, 0x57, 0x45, 0x1c, 0xc2, 0x40, 0x31,
	0x79, 0x99, 0x26, 0x36, 0x2b, 0x8b, 0xee, 0x93, 0x18, 0xef, 0xc1, 0x1b, 0x2e, 0xcd, 0xe3, 0x55,
	0xca, 0x85, 0xd2, 0xff, 0x81, 0xbb, 0x21, 0x87, 0xbf, 0x7a, 0x70, 0xe0, 0x98, 0x97, 0xc5, 0x4d,
	0xae, 0x38, 0xf9, 0x08, 0xf6, 0x2a, 0x6d, 0xb9, 0x92, 0x79, 0xb8, 0xad, 0x9b, 0xa1, 0xcd, 0xcc,
	0x0f, 0x75, 0xdc, 0xf1, 0xd7, 0x30, 0xb0, 0x07, 0xec, 0x1c, 0xf8, 0xbb, 0x14, 0x45, 0xa6, 0xa8,
	0x32, 0xd7, 0xfa, 0x45, 0x95, 0x61, 0xb3, 0x53, 0xb9, 0x62, 0x2b, 0xd7, 0xec, 0x34, 0x08, 0xef,
	0x91, 0xf2, 0x3f, 0x77, 0xe0, 0xad, 0xb9, 0xb8, 0x78, 0x91, 0x16, 0x17, 0x1b, 0x11, 0xdb, 0x49,
	0x70, 0xc2, 0x14, 0xdb, 0x3d, 0x0f, 0x4d, 0x67, 0x37, 0x61, 0xdb, 0xce, 0xbe, 0x0f, 0xde, 0xda,
	0x4a, 0xe2, 0xad, 0x11, 0x6d, 0xac, 0x18, 0x9e, 0xfe, 0x96, 0x4a, 0x52, 0x37, 0xfe, 0xd0, 0xd4,
	0x33, 0x55, 0x31, 0xc5, 0xf5, 0xf4, 0xc3, 0x99, 0x8a, 0x00, 0x9b, 0xda, 0x55, 0xbe, 0xbe, 0x28,
	0x38, 0x4f, 0x82, 0x3d, 0x33, 0xd6, 0x1c, 0x6e, 0xa6, 0xf0, 0xb0, 0x3d, 0x85, 0x09, 0xf4, 0xf0,
	0x83, 0x28, 0xf0, 0xcd, 0x64, 0x45, 0x1b, 0x99, 0x92, 0x7f, 0x7b, 0x76, 0x12, 0x80, 0x61, 0x6a,
	0x80, 0x67, 0x7f, 0x53, 0x65, 0xc5, 0x33, 0x64, 0x8f, 0xcc, 0xd9, 0x0e, 0xe3, 0x5a, 0xa9, 0x72,
	0xb3, 0xb6, 0x6f, 0xd6, 0x1c, 0x0e, 0xff, 0xf6, 0x60, 0x34, 0x17, 0xd8, 0x86, 0x2f, 0x74, 0x8c,
	0x77, 0xf5, 0x30, 0x51, 0x1f, 0xe7, 0x95, 0x50, 0x76, 0x2c, 0xd6, 0xb8, 0x89, 0xba, 0xdb, 0x8e,
	0xfa, 0x08, 0xa0, 0xc8, 0x8b, 0x6a, 0xc5, 0x64, 0xaa, 0x9c, 0x4c, 0x2d, 0x0f, 0x09, 0x61, 0x1f,
	0x9b, 0x39, 0x7e, 0x0a, 0xe8, 0x98, 0x8c, 0x70, 0x5b, 0x3e, 0xf2, 0x3e, 0x3c, 0xc8, 0xd8, 0xfa,
	0xbc, 0xde, 0x84, 0x65, 0x3a, 0xd0, 0x41, 0xdd, 0xf1, 0x93, 0x09, 0x8c, 0x0a, 0x5b, 0x87, 0x09,
	0x5f, 0x5b, 0x69, 0xdb, 0xae, 0xab, 0x81, 0xfe, 0x16, 0x7e, 0xf4, 0x6f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x61, 0x6f, 0x04, 0xcc, 0x19, 0x0b, 0x00, 0x00,
}
