// Code generated by protoc-gen-go. DO NOT EDIT.
// source: req.proto

package gopb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Net
type ReqNetLogin struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqNetLogin) Reset()         { *m = ReqNetLogin{} }
func (m *ReqNetLogin) String() string { return proto.CompactTextString(m) }
func (*ReqNetLogin) ProtoMessage()    {}
func (*ReqNetLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_a52bd445c288993d, []int{0}
}

func (m *ReqNetLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqNetLogin.Unmarshal(m, b)
}
func (m *ReqNetLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqNetLogin.Marshal(b, m, deterministic)
}
func (m *ReqNetLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqNetLogin.Merge(m, src)
}
func (m *ReqNetLogin) XXX_Size() int {
	return xxx_messageInfo_ReqNetLogin.Size(m)
}
func (m *ReqNetLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqNetLogin.DiscardUnknown(m)
}

var xxx_messageInfo_ReqNetLogin proto.InternalMessageInfo

func (m *ReqNetLogin) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ReqNetLogin) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ReqNetEnterMatchQueue struct {
	Level                int32    `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqNetEnterMatchQueue) Reset()         { *m = ReqNetEnterMatchQueue{} }
func (m *ReqNetEnterMatchQueue) String() string { return proto.CompactTextString(m) }
func (*ReqNetEnterMatchQueue) ProtoMessage()    {}
func (*ReqNetEnterMatchQueue) Descriptor() ([]byte, []int) {
	return fileDescriptor_a52bd445c288993d, []int{1}
}

func (m *ReqNetEnterMatchQueue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqNetEnterMatchQueue.Unmarshal(m, b)
}
func (m *ReqNetEnterMatchQueue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqNetEnterMatchQueue.Marshal(b, m, deterministic)
}
func (m *ReqNetEnterMatchQueue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqNetEnterMatchQueue.Merge(m, src)
}
func (m *ReqNetEnterMatchQueue) XXX_Size() int {
	return xxx_messageInfo_ReqNetEnterMatchQueue.Size(m)
}
func (m *ReqNetEnterMatchQueue) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqNetEnterMatchQueue.DiscardUnknown(m)
}

var xxx_messageInfo_ReqNetEnterMatchQueue proto.InternalMessageInfo

func (m *ReqNetEnterMatchQueue) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

//同步状态 data是二进制数据，需要再次解proto
type ReqGameSyncState struct {
	SType                int32    `protobuf:"varint,1,opt,name=sType,proto3" json:"sType,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Route                string   `protobuf:"bytes,3,opt,name=route,proto3" json:"route,omitempty"`
	Tag                  int32    `protobuf:"varint,4,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqGameSyncState) Reset()         { *m = ReqGameSyncState{} }
func (m *ReqGameSyncState) String() string { return proto.CompactTextString(m) }
func (*ReqGameSyncState) ProtoMessage()    {}
func (*ReqGameSyncState) Descriptor() ([]byte, []int) {
	return fileDescriptor_a52bd445c288993d, []int{2}
}

func (m *ReqGameSyncState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqGameSyncState.Unmarshal(m, b)
}
func (m *ReqGameSyncState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqGameSyncState.Marshal(b, m, deterministic)
}
func (m *ReqGameSyncState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqGameSyncState.Merge(m, src)
}
func (m *ReqGameSyncState) XXX_Size() int {
	return xxx_messageInfo_ReqGameSyncState.Size(m)
}
func (m *ReqGameSyncState) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqGameSyncState.DiscardUnknown(m)
}

var xxx_messageInfo_ReqGameSyncState proto.InternalMessageInfo

func (m *ReqGameSyncState) GetSType() int32 {
	if m != nil {
		return m.SType
	}
	return 0
}

func (m *ReqGameSyncState) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ReqGameSyncState) GetRoute() string {
	if m != nil {
		return m.Route
	}
	return ""
}

func (m *ReqGameSyncState) GetTag() int32 {
	if m != nil {
		return m.Tag
	}
	return 0
}

type ReqGameSyncFCommand struct {
	ExFrame              int32    `protobuf:"varint,1,opt,name=exFrame,proto3" json:"exFrame,omitempty"`
	EpFrame              int32    `protobuf:"varint,2,opt,name=epFrame,proto3" json:"epFrame,omitempty"`
	Uid                  string   `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Ctype                int32    `protobuf:"varint,4,opt,name=ctype,proto3" json:"ctype,omitempty"`
	ParamList            []int32  `protobuf:"varint,5,rep,packed,name=paramList,proto3" json:"paramList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqGameSyncFCommand) Reset()         { *m = ReqGameSyncFCommand{} }
func (m *ReqGameSyncFCommand) String() string { return proto.CompactTextString(m) }
func (*ReqGameSyncFCommand) ProtoMessage()    {}
func (*ReqGameSyncFCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_a52bd445c288993d, []int{3}
}

func (m *ReqGameSyncFCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqGameSyncFCommand.Unmarshal(m, b)
}
func (m *ReqGameSyncFCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqGameSyncFCommand.Marshal(b, m, deterministic)
}
func (m *ReqGameSyncFCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqGameSyncFCommand.Merge(m, src)
}
func (m *ReqGameSyncFCommand) XXX_Size() int {
	return xxx_messageInfo_ReqGameSyncFCommand.Size(m)
}
func (m *ReqGameSyncFCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqGameSyncFCommand.DiscardUnknown(m)
}

var xxx_messageInfo_ReqGameSyncFCommand proto.InternalMessageInfo

func (m *ReqGameSyncFCommand) GetExFrame() int32 {
	if m != nil {
		return m.ExFrame
	}
	return 0
}

func (m *ReqGameSyncFCommand) GetEpFrame() int32 {
	if m != nil {
		return m.EpFrame
	}
	return 0
}

func (m *ReqGameSyncFCommand) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqGameSyncFCommand) GetCtype() int32 {
	if m != nil {
		return m.Ctype
	}
	return 0
}

func (m *ReqGameSyncFCommand) GetParamList() []int32 {
	if m != nil {
		return m.ParamList
	}
	return nil
}

type ReqNetCreateRoom struct {
	Mac                  string   `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`
	PlayMod              string   `protobuf:"bytes,2,opt,name=playMod,proto3" json:"playMod,omitempty"`
	FingerPrint          string   `protobuf:"bytes,3,opt,name=fingerPrint,proto3" json:"fingerPrint,omitempty"`
	ItemId               int32    `protobuf:"varint,4,opt,name=itemId,proto3" json:"itemId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqNetCreateRoom) Reset()         { *m = ReqNetCreateRoom{} }
func (m *ReqNetCreateRoom) String() string { return proto.CompactTextString(m) }
func (*ReqNetCreateRoom) ProtoMessage()    {}
func (*ReqNetCreateRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_a52bd445c288993d, []int{4}
}

func (m *ReqNetCreateRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqNetCreateRoom.Unmarshal(m, b)
}
func (m *ReqNetCreateRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqNetCreateRoom.Marshal(b, m, deterministic)
}
func (m *ReqNetCreateRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqNetCreateRoom.Merge(m, src)
}
func (m *ReqNetCreateRoom) XXX_Size() int {
	return xxx_messageInfo_ReqNetCreateRoom.Size(m)
}
func (m *ReqNetCreateRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqNetCreateRoom.DiscardUnknown(m)
}

var xxx_messageInfo_ReqNetCreateRoom proto.InternalMessageInfo

func (m *ReqNetCreateRoom) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func (m *ReqNetCreateRoom) GetPlayMod() string {
	if m != nil {
		return m.PlayMod
	}
	return ""
}

func (m *ReqNetCreateRoom) GetFingerPrint() string {
	if m != nil {
		return m.FingerPrint
	}
	return ""
}

func (m *ReqNetCreateRoom) GetItemId() int32 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

type ReqNetEnterRoom struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	DeviceId             string   `protobuf:"bytes,2,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqNetEnterRoom) Reset()         { *m = ReqNetEnterRoom{} }
func (m *ReqNetEnterRoom) String() string { return proto.CompactTextString(m) }
func (*ReqNetEnterRoom) ProtoMessage()    {}
func (*ReqNetEnterRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_a52bd445c288993d, []int{5}
}

func (m *ReqNetEnterRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqNetEnterRoom.Unmarshal(m, b)
}
func (m *ReqNetEnterRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqNetEnterRoom.Marshal(b, m, deterministic)
}
func (m *ReqNetEnterRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqNetEnterRoom.Merge(m, src)
}
func (m *ReqNetEnterRoom) XXX_Size() int {
	return xxx_messageInfo_ReqNetEnterRoom.Size(m)
}
func (m *ReqNetEnterRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqNetEnterRoom.DiscardUnknown(m)
}

var xxx_messageInfo_ReqNetEnterRoom proto.InternalMessageInfo

func (m *ReqNetEnterRoom) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ReqNetEnterRoom) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

//从服务端进房间
type ReqNetEnterRoomServer struct {
	RoomId               string   `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	NickName             string   `protobuf:"bytes,3,opt,name=nickName,proto3" json:"nickName,omitempty"`
	AvatarUrl            string   `protobuf:"bytes,4,opt,name=avatarUrl,proto3" json:"avatarUrl,omitempty"`
	Have                 []string `protobuf:"bytes,5,rep,name=have,proto3" json:"have,omitempty"`
	Select               []string `protobuf:"bytes,6,rep,name=select,proto3" json:"select,omitempty"`
	Gender               int32    `protobuf:"varint,7,opt,name=gender,proto3" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqNetEnterRoomServer) Reset()         { *m = ReqNetEnterRoomServer{} }
func (m *ReqNetEnterRoomServer) String() string { return proto.CompactTextString(m) }
func (*ReqNetEnterRoomServer) ProtoMessage()    {}
func (*ReqNetEnterRoomServer) Descriptor() ([]byte, []int) {
	return fileDescriptor_a52bd445c288993d, []int{6}
}

func (m *ReqNetEnterRoomServer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqNetEnterRoomServer.Unmarshal(m, b)
}
func (m *ReqNetEnterRoomServer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqNetEnterRoomServer.Marshal(b, m, deterministic)
}
func (m *ReqNetEnterRoomServer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqNetEnterRoomServer.Merge(m, src)
}
func (m *ReqNetEnterRoomServer) XXX_Size() int {
	return xxx_messageInfo_ReqNetEnterRoomServer.Size(m)
}
func (m *ReqNetEnterRoomServer) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqNetEnterRoomServer.DiscardUnknown(m)
}

var xxx_messageInfo_ReqNetEnterRoomServer proto.InternalMessageInfo

func (m *ReqNetEnterRoomServer) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *ReqNetEnterRoomServer) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqNetEnterRoomServer) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *ReqNetEnterRoomServer) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *ReqNetEnterRoomServer) GetHave() []string {
	if m != nil {
		return m.Have
	}
	return nil
}

func (m *ReqNetEnterRoomServer) GetSelect() []string {
	if m != nil {
		return m.Select
	}
	return nil
}

func (m *ReqNetEnterRoomServer) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

type ReqGameFPlayerReday struct {
	Select               []string `protobuf:"bytes,1,rep,name=select,proto3" json:"select,omitempty"`
	Gender               int32    `protobuf:"varint,2,opt,name=gender,proto3" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqGameFPlayerReday) Reset()         { *m = ReqGameFPlayerReday{} }
func (m *ReqGameFPlayerReday) String() string { return proto.CompactTextString(m) }
func (*ReqGameFPlayerReday) ProtoMessage()    {}
func (*ReqGameFPlayerReday) Descriptor() ([]byte, []int) {
	return fileDescriptor_a52bd445c288993d, []int{7}
}

func (m *ReqGameFPlayerReday) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqGameFPlayerReday.Unmarshal(m, b)
}
func (m *ReqGameFPlayerReday) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqGameFPlayerReday.Marshal(b, m, deterministic)
}
func (m *ReqGameFPlayerReday) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqGameFPlayerReday.Merge(m, src)
}
func (m *ReqGameFPlayerReday) XXX_Size() int {
	return xxx_messageInfo_ReqGameFPlayerReday.Size(m)
}
func (m *ReqGameFPlayerReday) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqGameFPlayerReday.DiscardUnknown(m)
}

var xxx_messageInfo_ReqGameFPlayerReday proto.InternalMessageInfo

func (m *ReqGameFPlayerReday) GetSelect() []string {
	if m != nil {
		return m.Select
	}
	return nil
}

func (m *ReqGameFPlayerReday) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

//通用
type ReqCommonArg struct {
	StrVal1              string   `protobuf:"bytes,1,opt,name=strVal1,proto3" json:"strVal1,omitempty"`
	StrVal2              string   `protobuf:"bytes,2,opt,name=strVal2,proto3" json:"strVal2,omitempty"`
	IntVal1              int32    `protobuf:"varint,3,opt,name=intVal1,proto3" json:"intVal1,omitempty"`
	IntVal2              int32    `protobuf:"varint,4,opt,name=intVal2,proto3" json:"intVal2,omitempty"`
	IntVal3              int32    `protobuf:"varint,5,opt,name=intVal3,proto3" json:"intVal3,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqCommonArg) Reset()         { *m = ReqCommonArg{} }
func (m *ReqCommonArg) String() string { return proto.CompactTextString(m) }
func (*ReqCommonArg) ProtoMessage()    {}
func (*ReqCommonArg) Descriptor() ([]byte, []int) {
	return fileDescriptor_a52bd445c288993d, []int{8}
}

func (m *ReqCommonArg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCommonArg.Unmarshal(m, b)
}
func (m *ReqCommonArg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCommonArg.Marshal(b, m, deterministic)
}
func (m *ReqCommonArg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCommonArg.Merge(m, src)
}
func (m *ReqCommonArg) XXX_Size() int {
	return xxx_messageInfo_ReqCommonArg.Size(m)
}
func (m *ReqCommonArg) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCommonArg.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCommonArg proto.InternalMessageInfo

func (m *ReqCommonArg) GetStrVal1() string {
	if m != nil {
		return m.StrVal1
	}
	return ""
}

func (m *ReqCommonArg) GetStrVal2() string {
	if m != nil {
		return m.StrVal2
	}
	return ""
}

func (m *ReqCommonArg) GetIntVal1() int32 {
	if m != nil {
		return m.IntVal1
	}
	return 0
}

func (m *ReqCommonArg) GetIntVal2() int32 {
	if m != nil {
		return m.IntVal2
	}
	return 0
}

func (m *ReqCommonArg) GetIntVal3() int32 {
	if m != nil {
		return m.IntVal3
	}
	return 0
}

type ReqCommonArgs struct {
	Args                 []*ReqCommonArg `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ReqCommonArgs) Reset()         { *m = ReqCommonArgs{} }
func (m *ReqCommonArgs) String() string { return proto.CompactTextString(m) }
func (*ReqCommonArgs) ProtoMessage()    {}
func (*ReqCommonArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_a52bd445c288993d, []int{9}
}

func (m *ReqCommonArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCommonArgs.Unmarshal(m, b)
}
func (m *ReqCommonArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCommonArgs.Marshal(b, m, deterministic)
}
func (m *ReqCommonArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCommonArgs.Merge(m, src)
}
func (m *ReqCommonArgs) XXX_Size() int {
	return xxx_messageInfo_ReqCommonArgs.Size(m)
}
func (m *ReqCommonArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCommonArgs.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCommonArgs proto.InternalMessageInfo

func (m *ReqCommonArgs) GetArgs() []*ReqCommonArg {
	if m != nil {
		return m.Args
	}
	return nil
}

//--------------client proto--------------
type ReqSyncSnakeCmd struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Angle                int32    `protobuf:"varint,2,opt,name=angle,proto3" json:"angle,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqSyncSnakeCmd) Reset()         { *m = ReqSyncSnakeCmd{} }
func (m *ReqSyncSnakeCmd) String() string { return proto.CompactTextString(m) }
func (*ReqSyncSnakeCmd) ProtoMessage()    {}
func (*ReqSyncSnakeCmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_a52bd445c288993d, []int{10}
}

func (m *ReqSyncSnakeCmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSyncSnakeCmd.Unmarshal(m, b)
}
func (m *ReqSyncSnakeCmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSyncSnakeCmd.Marshal(b, m, deterministic)
}
func (m *ReqSyncSnakeCmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSyncSnakeCmd.Merge(m, src)
}
func (m *ReqSyncSnakeCmd) XXX_Size() int {
	return xxx_messageInfo_ReqSyncSnakeCmd.Size(m)
}
func (m *ReqSyncSnakeCmd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSyncSnakeCmd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSyncSnakeCmd proto.InternalMessageInfo

func (m *ReqSyncSnakeCmd) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqSyncSnakeCmd) GetAngle() int32 {
	if m != nil {
		return m.Angle
	}
	return 0
}

type ReqSyncSnakeState struct {
	States               []*SnakeState `protobuf:"bytes,1,rep,name=states,proto3" json:"states,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ReqSyncSnakeState) Reset()         { *m = ReqSyncSnakeState{} }
func (m *ReqSyncSnakeState) String() string { return proto.CompactTextString(m) }
func (*ReqSyncSnakeState) ProtoMessage()    {}
func (*ReqSyncSnakeState) Descriptor() ([]byte, []int) {
	return fileDescriptor_a52bd445c288993d, []int{11}
}

func (m *ReqSyncSnakeState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSyncSnakeState.Unmarshal(m, b)
}
func (m *ReqSyncSnakeState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSyncSnakeState.Marshal(b, m, deterministic)
}
func (m *ReqSyncSnakeState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSyncSnakeState.Merge(m, src)
}
func (m *ReqSyncSnakeState) XXX_Size() int {
	return xxx_messageInfo_ReqSyncSnakeState.Size(m)
}
func (m *ReqSyncSnakeState) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSyncSnakeState.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSyncSnakeState proto.InternalMessageInfo

func (m *ReqSyncSnakeState) GetStates() []*SnakeState {
	if m != nil {
		return m.States
	}
	return nil
}

type SnakeState struct {
	AiIndex              int32    `protobuf:"varint,1,opt,name=aiIndex,proto3" json:"aiIndex,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Score                int32    `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	Rank                 int32    `protobuf:"varint,4,opt,name=rank,proto3" json:"rank,omitempty"`
	SnakeLength          int32    `protobuf:"varint,5,opt,name=snakeLength,proto3" json:"snakeLength,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SnakeState) Reset()         { *m = SnakeState{} }
func (m *SnakeState) String() string { return proto.CompactTextString(m) }
func (*SnakeState) ProtoMessage()    {}
func (*SnakeState) Descriptor() ([]byte, []int) {
	return fileDescriptor_a52bd445c288993d, []int{12}
}

func (m *SnakeState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SnakeState.Unmarshal(m, b)
}
func (m *SnakeState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SnakeState.Marshal(b, m, deterministic)
}
func (m *SnakeState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnakeState.Merge(m, src)
}
func (m *SnakeState) XXX_Size() int {
	return xxx_messageInfo_SnakeState.Size(m)
}
func (m *SnakeState) XXX_DiscardUnknown() {
	xxx_messageInfo_SnakeState.DiscardUnknown(m)
}

var xxx_messageInfo_SnakeState proto.InternalMessageInfo

func (m *SnakeState) GetAiIndex() int32 {
	if m != nil {
		return m.AiIndex
	}
	return 0
}

func (m *SnakeState) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *SnakeState) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *SnakeState) GetRank() int32 {
	if m != nil {
		return m.Rank
	}
	return 0
}

func (m *SnakeState) GetSnakeLength() int32 {
	if m != nil {
		return m.SnakeLength
	}
	return 0
}

type ReqSkipSyncCommandData struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Ctype                string   `protobuf:"bytes,2,opt,name=ctype,proto3" json:"ctype,omitempty"`
	X                    int32    `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	Dir                  int32    `protobuf:"varint,5,opt,name=dir,proto3" json:"dir,omitempty"`
	State                int32    `protobuf:"varint,6,opt,name=state,proto3" json:"state,omitempty"`
	BoxSpeed             int32    `protobuf:"varint,7,opt,name=boxSpeed,proto3" json:"boxSpeed,omitempty"`
	Score                int32    `protobuf:"varint,8,opt,name=score,proto3" json:"score,omitempty"`
	Time                 int32    `protobuf:"varint,9,opt,name=time,proto3" json:"time,omitempty"`
	ReqID                int32    `protobuf:"varint,10,opt,name=reqID,proto3" json:"reqID,omitempty"`
	JumpTime             int32    `protobuf:"varint,11,opt,name=jumpTime,proto3" json:"jumpTime,omitempty"`
	StopTime             int32    `protobuf:"varint,12,opt,name=stopTime,proto3" json:"stopTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqSkipSyncCommandData) Reset()         { *m = ReqSkipSyncCommandData{} }
func (m *ReqSkipSyncCommandData) String() string { return proto.CompactTextString(m) }
func (*ReqSkipSyncCommandData) ProtoMessage()    {}
func (*ReqSkipSyncCommandData) Descriptor() ([]byte, []int) {
	return fileDescriptor_a52bd445c288993d, []int{13}
}

func (m *ReqSkipSyncCommandData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSkipSyncCommandData.Unmarshal(m, b)
}
func (m *ReqSkipSyncCommandData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSkipSyncCommandData.Marshal(b, m, deterministic)
}
func (m *ReqSkipSyncCommandData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSkipSyncCommandData.Merge(m, src)
}
func (m *ReqSkipSyncCommandData) XXX_Size() int {
	return xxx_messageInfo_ReqSkipSyncCommandData.Size(m)
}
func (m *ReqSkipSyncCommandData) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSkipSyncCommandData.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSkipSyncCommandData proto.InternalMessageInfo

func (m *ReqSkipSyncCommandData) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqSkipSyncCommandData) GetCtype() string {
	if m != nil {
		return m.Ctype
	}
	return ""
}

func (m *ReqSkipSyncCommandData) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *ReqSkipSyncCommandData) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *ReqSkipSyncCommandData) GetDir() int32 {
	if m != nil {
		return m.Dir
	}
	return 0
}

func (m *ReqSkipSyncCommandData) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *ReqSkipSyncCommandData) GetBoxSpeed() int32 {
	if m != nil {
		return m.BoxSpeed
	}
	return 0
}

func (m *ReqSkipSyncCommandData) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *ReqSkipSyncCommandData) GetTime() int32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *ReqSkipSyncCommandData) GetReqID() int32 {
	if m != nil {
		return m.ReqID
	}
	return 0
}

func (m *ReqSkipSyncCommandData) GetJumpTime() int32 {
	if m != nil {
		return m.JumpTime
	}
	return 0
}

func (m *ReqSkipSyncCommandData) GetStopTime() int32 {
	if m != nil {
		return m.StopTime
	}
	return 0
}

type ReqSyncPlayerData struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	BoxCount             int32    `protobuf:"varint,2,opt,name=boxCount,proto3" json:"boxCount,omitempty"`
	Score                int32    `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	Popularity           int32    `protobuf:"varint,4,opt,name=popularity,proto3" json:"popularity,omitempty"`
	LeftGameTime         int32    `protobuf:"varint,5,opt,name=leftGameTime,proto3" json:"leftGameTime,omitempty"`
	MaxPopularityUid     string   `protobuf:"bytes,6,opt,name=maxPopularityUid,proto3" json:"maxPopularityUid,omitempty"`
	PlayerIndex          int32    `protobuf:"varint,7,opt,name=playerIndex,proto3" json:"playerIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqSyncPlayerData) Reset()         { *m = ReqSyncPlayerData{} }
func (m *ReqSyncPlayerData) String() string { return proto.CompactTextString(m) }
func (*ReqSyncPlayerData) ProtoMessage()    {}
func (*ReqSyncPlayerData) Descriptor() ([]byte, []int) {
	return fileDescriptor_a52bd445c288993d, []int{14}
}

func (m *ReqSyncPlayerData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSyncPlayerData.Unmarshal(m, b)
}
func (m *ReqSyncPlayerData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSyncPlayerData.Marshal(b, m, deterministic)
}
func (m *ReqSyncPlayerData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSyncPlayerData.Merge(m, src)
}
func (m *ReqSyncPlayerData) XXX_Size() int {
	return xxx_messageInfo_ReqSyncPlayerData.Size(m)
}
func (m *ReqSyncPlayerData) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSyncPlayerData.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSyncPlayerData proto.InternalMessageInfo

func (m *ReqSyncPlayerData) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqSyncPlayerData) GetBoxCount() int32 {
	if m != nil {
		return m.BoxCount
	}
	return 0
}

func (m *ReqSyncPlayerData) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *ReqSyncPlayerData) GetPopularity() int32 {
	if m != nil {
		return m.Popularity
	}
	return 0
}

func (m *ReqSyncPlayerData) GetLeftGameTime() int32 {
	if m != nil {
		return m.LeftGameTime
	}
	return 0
}

func (m *ReqSyncPlayerData) GetMaxPopularityUid() string {
	if m != nil {
		return m.MaxPopularityUid
	}
	return ""
}

func (m *ReqSyncPlayerData) GetPlayerIndex() int32 {
	if m != nil {
		return m.PlayerIndex
	}
	return 0
}

//为了兼容线上只能在最后面加
type ReqGamRandomAward struct {
	Start                int32    `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	Steps                int32    `protobuf:"varint,2,opt,name=steps,proto3" json:"steps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqGamRandomAward) Reset()         { *m = ReqGamRandomAward{} }
func (m *ReqGamRandomAward) String() string { return proto.CompactTextString(m) }
func (*ReqGamRandomAward) ProtoMessage()    {}
func (*ReqGamRandomAward) Descriptor() ([]byte, []int) {
	return fileDescriptor_a52bd445c288993d, []int{15}
}

func (m *ReqGamRandomAward) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqGamRandomAward.Unmarshal(m, b)
}
func (m *ReqGamRandomAward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqGamRandomAward.Marshal(b, m, deterministic)
}
func (m *ReqGamRandomAward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqGamRandomAward.Merge(m, src)
}
func (m *ReqGamRandomAward) XXX_Size() int {
	return xxx_messageInfo_ReqGamRandomAward.Size(m)
}
func (m *ReqGamRandomAward) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqGamRandomAward.DiscardUnknown(m)
}

var xxx_messageInfo_ReqGamRandomAward proto.InternalMessageInfo

func (m *ReqGamRandomAward) GetStart() int32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *ReqGamRandomAward) GetSteps() int32 {
	if m != nil {
		return m.Steps
	}
	return 0
}

func init() {
	proto.RegisterType((*ReqNetLogin)(nil), "gopb.ReqNetLogin")
	proto.RegisterType((*ReqNetEnterMatchQueue)(nil), "gopb.ReqNetEnterMatchQueue")
	proto.RegisterType((*ReqGameSyncState)(nil), "gopb.ReqGameSyncState")
	proto.RegisterType((*ReqGameSyncFCommand)(nil), "gopb.ReqGameSyncFCommand")
	proto.RegisterType((*ReqNetCreateRoom)(nil), "gopb.ReqNetCreateRoom")
	proto.RegisterType((*ReqNetEnterRoom)(nil), "gopb.ReqNetEnterRoom")
	proto.RegisterType((*ReqNetEnterRoomServer)(nil), "gopb.ReqNetEnterRoomServer")
	proto.RegisterType((*ReqGameFPlayerReday)(nil), "gopb.ReqGameFPlayerReday")
	proto.RegisterType((*ReqCommonArg)(nil), "gopb.ReqCommonArg")
	proto.RegisterType((*ReqCommonArgs)(nil), "gopb.ReqCommonArgs")
	proto.RegisterType((*ReqSyncSnakeCmd)(nil), "gopb.ReqSyncSnakeCmd")
	proto.RegisterType((*ReqSyncSnakeState)(nil), "gopb.ReqSyncSnakeState")
	proto.RegisterType((*SnakeState)(nil), "gopb.SnakeState")
	proto.RegisterType((*ReqSkipSyncCommandData)(nil), "gopb.ReqSkipSyncCommandData")
	proto.RegisterType((*ReqSyncPlayerData)(nil), "gopb.ReqSyncPlayerData")
	proto.RegisterType((*ReqGamRandomAward)(nil), "gopb.ReqGamRandomAward")
}

func init() { proto.RegisterFile("req.proto", fileDescriptor_a52bd445c288993d) }

var fileDescriptor_a52bd445c288993d = []byte{
	// 852 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x55, 0xcd, 0x6e, 0xe4, 0x44,
	0x10, 0x96, 0x27, 0x99, 0x49, 0xa6, 0x32, 0x88, 0x60, 0x96, 0x95, 0x15, 0x21, 0x14, 0xf5, 0x01,
	0x45, 0x48, 0x44, 0x22, 0x39, 0x20, 0x0e, 0x08, 0xad, 0x66, 0x93, 0x55, 0xa4, 0x6c, 0x14, 0x7a,
	0x76, 0xb9, 0x77, 0xec, 0x5a, 0xc7, 0x8c, 0xdd, 0xed, 0x69, 0xb7, 0x67, 0x67, 0xee, 0xdc, 0xe1,
	0xc8, 0xdb, 0xf0, 0x3c, 0xbc, 0x05, 0xaa, 0xfe, 0xb1, 0x3d, 0x6c, 0x72, 0xeb, 0xaf, 0xaa, 0xbb,
	0xea, 0xab, 0xaf, 0xaa, 0x6c, 0x98, 0x6a, 0x5c, 0x9d, 0xd7, 0x5a, 0x19, 0x15, 0xef, 0xe7, 0xaa,
	0x7e, 0x60, 0x57, 0x70, 0xc4, 0x71, 0x75, 0x87, 0xe6, 0x56, 0xe5, 0x85, 0x8c, 0x4f, 0xe0, 0xb0,
	0x6d, 0x50, 0x4b, 0x51, 0x61, 0x12, 0x9d, 0x46, 0x67, 0x53, 0xde, 0x61, 0xf2, 0xd5, 0xa2, 0x69,
	0x3e, 0x2a, 0x9d, 0x25, 0x23, 0xe7, 0x0b, 0x98, 0x7d, 0x0f, 0x5f, 0xb9, 0x30, 0x57, 0xd2, 0xa0,
	0x7e, 0x2b, 0x4c, 0xfa, 0xf8, 0x6b, 0x8b, 0x2d, 0xc6, 0x2f, 0x60, 0x5c, 0xe2, 0x1a, 0x4b, 0x1b,
	0x6d, 0xcc, 0x1d, 0x60, 0x19, 0x1c, 0x73, 0x5c, 0xbd, 0x11, 0x15, 0x2e, 0xb6, 0x32, 0x5d, 0x18,
	0x61, 0xec, 0xcd, 0xe6, 0xdd, 0xb6, 0xc6, 0x70, 0xd3, 0x82, 0x38, 0x86, 0xfd, 0x4c, 0x18, 0x61,
	0x13, 0xce, 0xb8, 0x3d, 0xd3, 0x4d, 0xad, 0x5a, 0x83, 0xc9, 0x9e, 0x65, 0xe1, 0x40, 0x7c, 0x0c,
	0x7b, 0x46, 0xe4, 0xc9, 0xbe, 0x7d, 0x4d, 0x47, 0xf6, 0x67, 0x04, 0x5f, 0x0e, 0xd2, 0x5c, 0xcf,
	0x55, 0x55, 0x09, 0x99, 0xc5, 0x09, 0x1c, 0xe0, 0xe6, 0x5a, 0x87, 0x1a, 0xc7, 0x3c, 0x40, 0xeb,
	0xa9, 0x9d, 0x67, 0xe4, 0x3d, 0x0e, 0x52, 0xf4, 0xb6, 0xc8, 0x7c, 0x46, 0x3a, 0x12, 0x8b, 0xd4,
	0x10, 0x5f, 0x97, 0xd1, 0x81, 0xf8, 0x6b, 0x98, 0xd6, 0x42, 0x8b, 0xea, 0xb6, 0x68, 0x4c, 0x32,
	0x3e, 0xdd, 0x3b, 0x1b, 0xf3, 0xde, 0xc0, 0x36, 0xb6, 0xee, 0x3b, 0x34, 0x73, 0x8d, 0xc2, 0x20,
	0x57, 0xaa, 0xa2, 0xc8, 0x95, 0x48, 0xbd, 0xda, 0x74, 0x24, 0x16, 0x75, 0x29, 0xb6, 0x6f, 0x55,
	0xd0, 0x39, 0xc0, 0xf8, 0x14, 0x8e, 0x3e, 0x14, 0x32, 0x47, 0x7d, 0xaf, 0x0b, 0x69, 0x3c, 0x9b,
	0xa1, 0x29, 0x7e, 0x09, 0x93, 0xc2, 0x60, 0x75, 0x93, 0x79, 0x5a, 0x1e, 0xb1, 0x39, 0x7c, 0x3e,
	0x68, 0x90, 0x4d, 0xfc, 0x02, 0xc6, 0x46, 0x2d, 0x51, 0xfa, 0xd4, 0x0e, 0x50, 0x97, 0x33, 0x5c,
	0x17, 0x29, 0xde, 0x74, 0x5d, 0x0e, 0x98, 0xfd, 0x13, 0xed, 0xb4, 0x99, 0xa2, 0x2c, 0x50, 0xaf,
	0x51, 0x53, 0x5a, 0xad, 0x14, 0xa5, 0x75, 0xc1, 0x3c, 0x0a, 0xb2, 0x8d, 0x7a, 0xd9, 0x4e, 0xe0,
	0x50, 0x16, 0xe9, 0xf2, 0x8e, 0x34, 0x76, 0xfc, 0x3b, 0x4c, 0xe2, 0x89, 0xb5, 0x30, 0x42, 0xbf,
	0xd7, 0xa5, 0xe5, 0x3f, 0xe5, 0xbd, 0x81, 0x46, 0xe1, 0x51, 0xac, 0xd1, 0xaa, 0x3a, 0xe5, 0xf6,
	0x4c, 0x79, 0x1b, 0x2c, 0x31, 0x35, 0xc9, 0xc4, 0x5a, 0x3d, 0x22, 0x7b, 0x8e, 0x32, 0x43, 0x9d,
	0x1c, 0x38, 0x19, 0x1c, 0x62, 0x57, 0xdd, 0x44, 0x5c, 0xdf, 0x97, 0x62, 0x8b, 0x9a, 0x63, 0x26,
	0xb6, 0x83, 0x30, 0xd1, 0x33, 0x61, 0x46, 0x3b, 0x61, 0xfe, 0x8a, 0x60, 0xc6, 0x71, 0x45, 0x03,
	0xa5, 0xe4, 0x2b, 0x9d, 0x53, 0xcb, 0x1a, 0xa3, 0x7f, 0x13, 0xe5, 0x0f, 0x5e, 0x80, 0x00, 0x7b,
	0xcf, 0x45, 0x68, 0xa6, 0x87, 0xe4, 0x29, 0xa4, 0xb1, 0x6f, 0xf6, 0xdc, 0xb0, 0x79, 0xd8, 0x7b,
	0x2e, 0x7c, 0x17, 0x03, 0xec, 0x3d, 0x97, 0xc9, 0x78, 0xe8, 0xb9, 0x64, 0x3f, 0xc2, 0x67, 0x43,
	0x46, 0x4d, 0xfc, 0x2d, 0xec, 0x0b, 0x9d, 0x37, 0xb6, 0xa2, 0xa3, 0x8b, 0xf8, 0x9c, 0xd6, 0xfd,
	0x7c, 0x78, 0x85, 0x5b, 0x3f, 0xfb, 0xc9, 0x4e, 0x86, 0xdd, 0x43, 0x29, 0x96, 0x38, 0xaf, 0xba,
	0xae, 0x45, 0x3b, 0xc3, 0x2e, 0x64, 0x5e, 0x86, 0xb5, 0x70, 0x80, 0xfd, 0x0c, 0x5f, 0x0c, 0x9f,
	0xba, 0x3d, 0x3e, 0x83, 0x49, 0x43, 0x87, 0x90, 0xf9, 0xd8, 0x65, 0xee, 0x6f, 0x70, 0xef, 0x67,
	0x7f, 0x44, 0x00, 0x83, 0x87, 0x09, 0x1c, 0x88, 0xe2, 0x46, 0x66, 0xb8, 0x09, 0x6b, 0xe9, 0xe1,
	0x13, 0x53, 0x44, 0x1f, 0x8b, 0x54, 0x69, 0xf4, 0xca, 0x39, 0x40, 0x13, 0xa2, 0x85, 0x5c, 0x7a,
	0xd1, 0xec, 0x99, 0x56, 0xa6, 0xa1, 0x1c, 0xb7, 0x28, 0x73, 0xf3, 0xe8, 0x55, 0x1b, 0x9a, 0xd8,
	0xdf, 0x23, 0x78, 0x49, 0x65, 0x2c, 0x8b, 0x9a, 0x4a, 0xf1, 0x5f, 0x89, 0xd7, 0xf4, 0xa5, 0x79,
	0x52, 0x08, 0xb7, 0xf5, 0x8e, 0x8c, 0xdf, 0xfa, 0x19, 0x44, 0x1b, 0x4f, 0x25, 0xda, 0x10, 0xda,
	0x7a, 0x0e, 0xd1, 0x96, 0x62, 0x64, 0x85, 0xf6, 0x89, 0xe9, 0x68, 0xc9, 0x53, 0xc5, 0xc9, 0xc4,
	0x93, 0xb7, 0xe5, 0x9f, 0xc0, 0xe1, 0x83, 0xda, 0x2c, 0x6a, 0xc4, 0xcc, 0x0f, 0x6d, 0x87, 0xfb,
	0x72, 0x0f, 0xff, 0x57, 0xae, 0x29, 0x2a, 0x4c, 0xa6, 0xae, 0x5c, 0x3a, 0xdb, 0x6f, 0x23, 0xae,
	0x6e, 0x5e, 0x27, 0xe0, 0x6e, 0x5a, 0x40, 0xb1, 0x7f, 0x6f, 0xab, 0xfa, 0x1d, 0xdd, 0x3e, 0x72,
	0xb1, 0x03, 0x26, 0x5f, 0x63, 0x94, 0xf3, 0xcd, 0x9c, 0x2f, 0x60, 0xf6, 0x6f, 0xd4, 0x75, 0xd8,
	0xad, 0xcb, 0x33, 0xaa, 0x38, 0xee, 0x73, 0xd5, 0x4a, 0xe3, 0x27, 0xa4, 0xc3, 0xcf, 0xb4, 0xea,
	0x1b, 0x80, 0x5a, 0xd5, 0x6d, 0x29, 0x74, 0x61, 0x82, 0x58, 0x03, 0x4b, 0xcc, 0x60, 0x56, 0xe2,
	0x07, 0x43, 0x9b, 0x6a, 0x99, 0x39, 0xf9, 0x76, 0x6c, 0xf1, 0x77, 0x70, 0x5c, 0x89, 0xcd, 0x7d,
	0xf7, 0xe8, 0x7d, 0x91, 0x59, 0x49, 0xa7, 0xfc, 0x13, 0x3b, 0x8d, 0x41, 0x6d, 0x2b, 0x70, 0x03,
	0xe6, 0x04, 0x1e, 0x9a, 0xd8, 0x2f, 0xb6, 0xd4, 0x37, 0xa2, 0xe2, 0x42, 0x66, 0xaa, 0x7a, 0xf5,
	0x51, 0xe8, 0xcc, 0xb7, 0x4a, 0x9b, 0xee, 0xa7, 0x44, 0xc0, 0x59, 0xb1, 0x6e, 0xc2, 0x36, 0x58,
	0xf0, 0x30, 0xb1, 0xff, 0xd5, 0xcb, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x12, 0xc8, 0xcf, 0x98,
	0x64, 0x07, 0x00, 0x00,
}
