// Code generated by protoc-gen-go. DO NOT EDIT.
// source: res.proto

package gopb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Net
type ResNetLogin struct {
	Code                 int32               `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string              `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Player               *ResNetLogin_Player `protobuf:"bytes,3,opt,name=player,proto3" json:"player,omitempty"`
	GameConfig           string              `protobuf:"bytes,4,opt,name=gameConfig,proto3" json:"gameConfig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ResNetLogin) Reset()         { *m = ResNetLogin{} }
func (m *ResNetLogin) String() string { return proto.CompactTextString(m) }
func (*ResNetLogin) ProtoMessage()    {}
func (*ResNetLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_36bffc8626f07b47, []int{0}
}

func (m *ResNetLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResNetLogin.Unmarshal(m, b)
}
func (m *ResNetLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResNetLogin.Marshal(b, m, deterministic)
}
func (m *ResNetLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResNetLogin.Merge(m, src)
}
func (m *ResNetLogin) XXX_Size() int {
	return xxx_messageInfo_ResNetLogin.Size(m)
}
func (m *ResNetLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_ResNetLogin.DiscardUnknown(m)
}

var xxx_messageInfo_ResNetLogin proto.InternalMessageInfo

func (m *ResNetLogin) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResNetLogin) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ResNetLogin) GetPlayer() *ResNetLogin_Player {
	if m != nil {
		return m.Player
	}
	return nil
}

func (m *ResNetLogin) GetGameConfig() string {
	if m != nil {
		return m.GameConfig
	}
	return ""
}

type ResNetLogin_Player struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	AvaUrl               string   `protobuf:"bytes,4,opt,name=avaUrl,proto3" json:"avaUrl,omitempty"`
	Score                int32    `protobuf:"varint,5,opt,name=score,proto3" json:"score,omitempty"`
	Level                int32    `protobuf:"varint,6,opt,name=level,proto3" json:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResNetLogin_Player) Reset()         { *m = ResNetLogin_Player{} }
func (m *ResNetLogin_Player) String() string { return proto.CompactTextString(m) }
func (*ResNetLogin_Player) ProtoMessage()    {}
func (*ResNetLogin_Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_36bffc8626f07b47, []int{0, 0}
}

func (m *ResNetLogin_Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResNetLogin_Player.Unmarshal(m, b)
}
func (m *ResNetLogin_Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResNetLogin_Player.Marshal(b, m, deterministic)
}
func (m *ResNetLogin_Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResNetLogin_Player.Merge(m, src)
}
func (m *ResNetLogin_Player) XXX_Size() int {
	return xxx_messageInfo_ResNetLogin_Player.Size(m)
}
func (m *ResNetLogin_Player) XXX_DiscardUnknown() {
	xxx_messageInfo_ResNetLogin_Player.DiscardUnknown(m)
}

var xxx_messageInfo_ResNetLogin_Player proto.InternalMessageInfo

func (m *ResNetLogin_Player) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ResNetLogin_Player) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ResNetLogin_Player) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ResNetLogin_Player) GetAvaUrl() string {
	if m != nil {
		return m.AvaUrl
	}
	return ""
}

func (m *ResNetLogin_Player) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *ResNetLogin_Player) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

type ResNetEnterMatchQueue struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResNetEnterMatchQueue) Reset()         { *m = ResNetEnterMatchQueue{} }
func (m *ResNetEnterMatchQueue) String() string { return proto.CompactTextString(m) }
func (*ResNetEnterMatchQueue) ProtoMessage()    {}
func (*ResNetEnterMatchQueue) Descriptor() ([]byte, []int) {
	return fileDescriptor_36bffc8626f07b47, []int{1}
}

func (m *ResNetEnterMatchQueue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResNetEnterMatchQueue.Unmarshal(m, b)
}
func (m *ResNetEnterMatchQueue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResNetEnterMatchQueue.Marshal(b, m, deterministic)
}
func (m *ResNetEnterMatchQueue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResNetEnterMatchQueue.Merge(m, src)
}
func (m *ResNetEnterMatchQueue) XXX_Size() int {
	return xxx_messageInfo_ResNetEnterMatchQueue.Size(m)
}
func (m *ResNetEnterMatchQueue) XXX_DiscardUnknown() {
	xxx_messageInfo_ResNetEnterMatchQueue.DiscardUnknown(m)
}

var xxx_messageInfo_ResNetEnterMatchQueue proto.InternalMessageInfo

func (m *ResNetEnterMatchQueue) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResNetEnterMatchQueue) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ResNetEnterMatchQueue) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type ResError struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResError) Reset()         { *m = ResError{} }
func (m *ResError) String() string { return proto.CompactTextString(m) }
func (*ResError) ProtoMessage()    {}
func (*ResError) Descriptor() ([]byte, []int) {
	return fileDescriptor_36bffc8626f07b47, []int{2}
}

func (m *ResError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResError.Unmarshal(m, b)
}
func (m *ResError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResError.Marshal(b, m, deterministic)
}
func (m *ResError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResError.Merge(m, src)
}
func (m *ResError) XXX_Size() int {
	return xxx_messageInfo_ResError.Size(m)
}
func (m *ResError) XXX_DiscardUnknown() {
	xxx_messageInfo_ResError.DiscardUnknown(m)
}

var xxx_messageInfo_ResError proto.InternalMessageInfo

func (m *ResError) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResError) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type ResVersionAddr struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResVersionAddr) Reset()         { *m = ResVersionAddr{} }
func (m *ResVersionAddr) String() string { return proto.CompactTextString(m) }
func (*ResVersionAddr) ProtoMessage()    {}
func (*ResVersionAddr) Descriptor() ([]byte, []int) {
	return fileDescriptor_36bffc8626f07b47, []int{3}
}

func (m *ResVersionAddr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResVersionAddr.Unmarshal(m, b)
}
func (m *ResVersionAddr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResVersionAddr.Marshal(b, m, deterministic)
}
func (m *ResVersionAddr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResVersionAddr.Merge(m, src)
}
func (m *ResVersionAddr) XXX_Size() int {
	return xxx_messageInfo_ResVersionAddr.Size(m)
}
func (m *ResVersionAddr) XXX_DiscardUnknown() {
	xxx_messageInfo_ResVersionAddr.DiscardUnknown(m)
}

var xxx_messageInfo_ResVersionAddr proto.InternalMessageInfo

func (m *ResVersionAddr) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResVersionAddr) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ResVersionAddr) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

//临时 帧同步房间
type ResNetEnterFRoom struct {
	Code                 int32                           `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string                          `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	FrameTime            int32                           `protobuf:"varint,3,opt,name=frameTime,proto3" json:"frameTime,omitempty"`
	KeyFrame             int32                           `protobuf:"varint,4,opt,name=keyFrame,proto3" json:"keyFrame,omitempty"`
	RandSeed             int64                           `protobuf:"varint,5,opt,name=randSeed,proto3" json:"randSeed,omitempty"`
	RoomState            int32                           `protobuf:"varint,6,opt,name=roomState,proto3" json:"roomState,omitempty"`
	Players              []*ResNetEnterFRoom_PlayerInfo  `protobuf:"bytes,7,rep,name=players,proto3" json:"players,omitempty"`
	InitCommands         []*ResNetEnterFRoom_FCommand    `protobuf:"bytes,8,rep,name=initCommands,proto3" json:"initCommands,omitempty"`
	DoingCommands        []*ResNetEnterFRoom_FCommand    `protobuf:"bytes,9,rep,name=doingCommands,proto3" json:"doingCommands,omitempty"`
	Have                 []string                        `protobuf:"bytes,10,rep,name=have,proto3" json:"have,omitempty"`
	ServerId             string                          `protobuf:"bytes,11,opt,name=serverId,proto3" json:"serverId,omitempty"`
	RoomId               string                          `protobuf:"bytes,12,opt,name=roomId,proto3" json:"roomId,omitempty"`
	CurFrame             int32                           `protobuf:"varint,13,opt,name=curFrame,proto3" json:"curFrame,omitempty"`
	Watchers             []*ResNetEnterFRoom_WatcherInfo `protobuf:"bytes,14,rep,name=watchers,proto3" json:"watchers,omitempty"`
	Config               string                          `protobuf:"bytes,15,opt,name=config,proto3" json:"config,omitempty"`
	WaitTime             int64                           `protobuf:"varint,16,opt,name=waitTime,proto3" json:"waitTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ResNetEnterFRoom) Reset()         { *m = ResNetEnterFRoom{} }
func (m *ResNetEnterFRoom) String() string { return proto.CompactTextString(m) }
func (*ResNetEnterFRoom) ProtoMessage()    {}
func (*ResNetEnterFRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_36bffc8626f07b47, []int{4}
}

func (m *ResNetEnterFRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResNetEnterFRoom.Unmarshal(m, b)
}
func (m *ResNetEnterFRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResNetEnterFRoom.Marshal(b, m, deterministic)
}
func (m *ResNetEnterFRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResNetEnterFRoom.Merge(m, src)
}
func (m *ResNetEnterFRoom) XXX_Size() int {
	return xxx_messageInfo_ResNetEnterFRoom.Size(m)
}
func (m *ResNetEnterFRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_ResNetEnterFRoom.DiscardUnknown(m)
}

var xxx_messageInfo_ResNetEnterFRoom proto.InternalMessageInfo

func (m *ResNetEnterFRoom) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResNetEnterFRoom) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ResNetEnterFRoom) GetFrameTime() int32 {
	if m != nil {
		return m.FrameTime
	}
	return 0
}

func (m *ResNetEnterFRoom) GetKeyFrame() int32 {
	if m != nil {
		return m.KeyFrame
	}
	return 0
}

func (m *ResNetEnterFRoom) GetRandSeed() int64 {
	if m != nil {
		return m.RandSeed
	}
	return 0
}

func (m *ResNetEnterFRoom) GetRoomState() int32 {
	if m != nil {
		return m.RoomState
	}
	return 0
}

func (m *ResNetEnterFRoom) GetPlayers() []*ResNetEnterFRoom_PlayerInfo {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *ResNetEnterFRoom) GetInitCommands() []*ResNetEnterFRoom_FCommand {
	if m != nil {
		return m.InitCommands
	}
	return nil
}

func (m *ResNetEnterFRoom) GetDoingCommands() []*ResNetEnterFRoom_FCommand {
	if m != nil {
		return m.DoingCommands
	}
	return nil
}

func (m *ResNetEnterFRoom) GetHave() []string {
	if m != nil {
		return m.Have
	}
	return nil
}

func (m *ResNetEnterFRoom) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func (m *ResNetEnterFRoom) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *ResNetEnterFRoom) GetCurFrame() int32 {
	if m != nil {
		return m.CurFrame
	}
	return 0
}

func (m *ResNetEnterFRoom) GetWatchers() []*ResNetEnterFRoom_WatcherInfo {
	if m != nil {
		return m.Watchers
	}
	return nil
}

func (m *ResNetEnterFRoom) GetConfig() string {
	if m != nil {
		return m.Config
	}
	return ""
}

func (m *ResNetEnterFRoom) GetWaitTime() int64 {
	if m != nil {
		return m.WaitTime
	}
	return 0
}

type ResNetEnterFRoom_FCommand struct {
	ExFrame              int32    `protobuf:"varint,1,opt,name=exFrame,proto3" json:"exFrame,omitempty"`
	EpFrame              int32    `protobuf:"varint,2,opt,name=epFrame,proto3" json:"epFrame,omitempty"`
	Uid                  string   `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Ctype                int32    `protobuf:"varint,4,opt,name=ctype,proto3" json:"ctype,omitempty"`
	ParamList            []int32  `protobuf:"varint,5,rep,packed,name=paramList,proto3" json:"paramList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResNetEnterFRoom_FCommand) Reset()         { *m = ResNetEnterFRoom_FCommand{} }
func (m *ResNetEnterFRoom_FCommand) String() string { return proto.CompactTextString(m) }
func (*ResNetEnterFRoom_FCommand) ProtoMessage()    {}
func (*ResNetEnterFRoom_FCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_36bffc8626f07b47, []int{4, 0}
}

func (m *ResNetEnterFRoom_FCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResNetEnterFRoom_FCommand.Unmarshal(m, b)
}
func (m *ResNetEnterFRoom_FCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResNetEnterFRoom_FCommand.Marshal(b, m, deterministic)
}
func (m *ResNetEnterFRoom_FCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResNetEnterFRoom_FCommand.Merge(m, src)
}
func (m *ResNetEnterFRoom_FCommand) XXX_Size() int {
	return xxx_messageInfo_ResNetEnterFRoom_FCommand.Size(m)
}
func (m *ResNetEnterFRoom_FCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_ResNetEnterFRoom_FCommand.DiscardUnknown(m)
}

var xxx_messageInfo_ResNetEnterFRoom_FCommand proto.InternalMessageInfo

func (m *ResNetEnterFRoom_FCommand) GetExFrame() int32 {
	if m != nil {
		return m.ExFrame
	}
	return 0
}

func (m *ResNetEnterFRoom_FCommand) GetEpFrame() int32 {
	if m != nil {
		return m.EpFrame
	}
	return 0
}

func (m *ResNetEnterFRoom_FCommand) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ResNetEnterFRoom_FCommand) GetCtype() int32 {
	if m != nil {
		return m.Ctype
	}
	return 0
}

func (m *ResNetEnterFRoom_FCommand) GetParamList() []int32 {
	if m != nil {
		return m.ParamList
	}
	return nil
}

type ResNetEnterFRoom_PlayerInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AvaUrl               string   `protobuf:"bytes,3,opt,name=avaUrl,proto3" json:"avaUrl,omitempty"`
	IsReady              bool     `protobuf:"varint,4,opt,name=isReady,proto3" json:"isReady,omitempty"`
	Have                 []string `protobuf:"bytes,5,rep,name=have,proto3" json:"have,omitempty"`
	Select               []string `protobuf:"bytes,6,rep,name=select,proto3" json:"select,omitempty"`
	Gender               int32    `protobuf:"varint,7,opt,name=gender,proto3" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResNetEnterFRoom_PlayerInfo) Reset()         { *m = ResNetEnterFRoom_PlayerInfo{} }
func (m *ResNetEnterFRoom_PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*ResNetEnterFRoom_PlayerInfo) ProtoMessage()    {}
func (*ResNetEnterFRoom_PlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_36bffc8626f07b47, []int{4, 1}
}

func (m *ResNetEnterFRoom_PlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResNetEnterFRoom_PlayerInfo.Unmarshal(m, b)
}
func (m *ResNetEnterFRoom_PlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResNetEnterFRoom_PlayerInfo.Marshal(b, m, deterministic)
}
func (m *ResNetEnterFRoom_PlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResNetEnterFRoom_PlayerInfo.Merge(m, src)
}
func (m *ResNetEnterFRoom_PlayerInfo) XXX_Size() int {
	return xxx_messageInfo_ResNetEnterFRoom_PlayerInfo.Size(m)
}
func (m *ResNetEnterFRoom_PlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ResNetEnterFRoom_PlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ResNetEnterFRoom_PlayerInfo proto.InternalMessageInfo

func (m *ResNetEnterFRoom_PlayerInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ResNetEnterFRoom_PlayerInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ResNetEnterFRoom_PlayerInfo) GetAvaUrl() string {
	if m != nil {
		return m.AvaUrl
	}
	return ""
}

func (m *ResNetEnterFRoom_PlayerInfo) GetIsReady() bool {
	if m != nil {
		return m.IsReady
	}
	return false
}

func (m *ResNetEnterFRoom_PlayerInfo) GetHave() []string {
	if m != nil {
		return m.Have
	}
	return nil
}

func (m *ResNetEnterFRoom_PlayerInfo) GetSelect() []string {
	if m != nil {
		return m.Select
	}
	return nil
}

func (m *ResNetEnterFRoom_PlayerInfo) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

type ResNetEnterFRoom_WatcherInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	TarUid               string   `protobuf:"bytes,2,opt,name=tarUid,proto3" json:"tarUid,omitempty"`
	Total                int32    `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	AvaUrl               string   `protobuf:"bytes,5,opt,name=avaUrl,proto3" json:"avaUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResNetEnterFRoom_WatcherInfo) Reset()         { *m = ResNetEnterFRoom_WatcherInfo{} }
func (m *ResNetEnterFRoom_WatcherInfo) String() string { return proto.CompactTextString(m) }
func (*ResNetEnterFRoom_WatcherInfo) ProtoMessage()    {}
func (*ResNetEnterFRoom_WatcherInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_36bffc8626f07b47, []int{4, 2}
}

func (m *ResNetEnterFRoom_WatcherInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResNetEnterFRoom_WatcherInfo.Unmarshal(m, b)
}
func (m *ResNetEnterFRoom_WatcherInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResNetEnterFRoom_WatcherInfo.Marshal(b, m, deterministic)
}
func (m *ResNetEnterFRoom_WatcherInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResNetEnterFRoom_WatcherInfo.Merge(m, src)
}
func (m *ResNetEnterFRoom_WatcherInfo) XXX_Size() int {
	return xxx_messageInfo_ResNetEnterFRoom_WatcherInfo.Size(m)
}
func (m *ResNetEnterFRoom_WatcherInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ResNetEnterFRoom_WatcherInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ResNetEnterFRoom_WatcherInfo proto.InternalMessageInfo

func (m *ResNetEnterFRoom_WatcherInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ResNetEnterFRoom_WatcherInfo) GetTarUid() string {
	if m != nil {
		return m.TarUid
	}
	return ""
}

func (m *ResNetEnterFRoom_WatcherInfo) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ResNetEnterFRoom_WatcherInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ResNetEnterFRoom_WatcherInfo) GetAvaUrl() string {
	if m != nil {
		return m.AvaUrl
	}
	return ""
}

type ResNetCreateFRoom struct {
	Code                 int32                            `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string                           `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	RoomState            int32                            `protobuf:"varint,3,opt,name=roomState,proto3" json:"roomState,omitempty"`
	WaitTime             int64                            `protobuf:"varint,4,opt,name=waitTime,proto3" json:"waitTime,omitempty"`
	QrUrl                string                           `protobuf:"bytes,5,opt,name=qrUrl,proto3" json:"qrUrl,omitempty"`
	FrameTime            int32                            `protobuf:"varint,6,opt,name=frameTime,proto3" json:"frameTime,omitempty"`
	KeyFrame             int32                            `protobuf:"varint,7,opt,name=keyFrame,proto3" json:"keyFrame,omitempty"`
	RandSeed             int64                            `protobuf:"varint,8,opt,name=randSeed,proto3" json:"randSeed,omitempty"`
	InitCommands         []*ResNetCreateFRoom_FCommand    `protobuf:"bytes,9,rep,name=initCommands,proto3" json:"initCommands,omitempty"`
	DoingCommands        []*ResNetCreateFRoom_FCommand    `protobuf:"bytes,10,rep,name=doingCommands,proto3" json:"doingCommands,omitempty"`
	Star1Awards          []*ResNetCreateFRoom_RoomAward   `protobuf:"bytes,11,rep,name=star1Awards,proto3" json:"star1Awards,omitempty"`
	Star2Awards          []*ResNetCreateFRoom_RoomAward   `protobuf:"bytes,12,rep,name=star2Awards,proto3" json:"star2Awards,omitempty"`
	Star3Awards          []*ResNetCreateFRoom_RoomAward   `protobuf:"bytes,13,rep,name=star3Awards,proto3" json:"star3Awards,omitempty"`
	Star3Players         []*ResNetCreateFRoom_Star3Player `protobuf:"bytes,15,rep,name=star3Players,proto3" json:"star3Players,omitempty"`
	Players              []*ResNetCreateFRoom_PlayerInfo  `protobuf:"bytes,16,rep,name=players,proto3" json:"players,omitempty"`
	Waitings             []*ResNetCreateFRoom_PlayerInfo  `protobuf:"bytes,17,rep,name=waitings,proto3" json:"waitings,omitempty"`
	Watchers             []*ResNetCreateFRoom_WatcherInfo `protobuf:"bytes,18,rep,name=watchers,proto3" json:"watchers,omitempty"`
	CurFrame             int32                            `protobuf:"varint,19,opt,name=curFrame,proto3" json:"curFrame,omitempty"`
	RoundId              int64                            `protobuf:"varint,20,opt,name=roundId,proto3" json:"roundId,omitempty"`
	Config               string                           `protobuf:"bytes,21,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *ResNetCreateFRoom) Reset()         { *m = ResNetCreateFRoom{} }
func (m *ResNetCreateFRoom) String() string { return proto.CompactTextString(m) }
func (*ResNetCreateFRoom) ProtoMessage()    {}
func (*ResNetCreateFRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_36bffc8626f07b47, []int{5}
}

func (m *ResNetCreateFRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResNetCreateFRoom.Unmarshal(m, b)
}
func (m *ResNetCreateFRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResNetCreateFRoom.Marshal(b, m, deterministic)
}
func (m *ResNetCreateFRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResNetCreateFRoom.Merge(m, src)
}
func (m *ResNetCreateFRoom) XXX_Size() int {
	return xxx_messageInfo_ResNetCreateFRoom.Size(m)
}
func (m *ResNetCreateFRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_ResNetCreateFRoom.DiscardUnknown(m)
}

var xxx_messageInfo_ResNetCreateFRoom proto.InternalMessageInfo

func (m *ResNetCreateFRoom) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResNetCreateFRoom) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ResNetCreateFRoom) GetRoomState() int32 {
	if m != nil {
		return m.RoomState
	}
	return 0
}

func (m *ResNetCreateFRoom) GetWaitTime() int64 {
	if m != nil {
		return m.WaitTime
	}
	return 0
}

func (m *ResNetCreateFRoom) GetQrUrl() string {
	if m != nil {
		return m.QrUrl
	}
	return ""
}

func (m *ResNetCreateFRoom) GetFrameTime() int32 {
	if m != nil {
		return m.FrameTime
	}
	return 0
}

func (m *ResNetCreateFRoom) GetKeyFrame() int32 {
	if m != nil {
		return m.KeyFrame
	}
	return 0
}

func (m *ResNetCreateFRoom) GetRandSeed() int64 {
	if m != nil {
		return m.RandSeed
	}
	return 0
}

func (m *ResNetCreateFRoom) GetInitCommands() []*ResNetCreateFRoom_FCommand {
	if m != nil {
		return m.InitCommands
	}
	return nil
}

func (m *ResNetCreateFRoom) GetDoingCommands() []*ResNetCreateFRoom_FCommand {
	if m != nil {
		return m.DoingCommands
	}
	return nil
}

func (m *ResNetCreateFRoom) GetStar1Awards() []*ResNetCreateFRoom_RoomAward {
	if m != nil {
		return m.Star1Awards
	}
	return nil
}

func (m *ResNetCreateFRoom) GetStar2Awards() []*ResNetCreateFRoom_RoomAward {
	if m != nil {
		return m.Star2Awards
	}
	return nil
}

func (m *ResNetCreateFRoom) GetStar3Awards() []*ResNetCreateFRoom_RoomAward {
	if m != nil {
		return m.Star3Awards
	}
	return nil
}

func (m *ResNetCreateFRoom) GetStar3Players() []*ResNetCreateFRoom_Star3Player {
	if m != nil {
		return m.Star3Players
	}
	return nil
}

func (m *ResNetCreateFRoom) GetPlayers() []*ResNetCreateFRoom_PlayerInfo {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *ResNetCreateFRoom) GetWaitings() []*ResNetCreateFRoom_PlayerInfo {
	if m != nil {
		return m.Waitings
	}
	return nil
}

func (m *ResNetCreateFRoom) GetWatchers() []*ResNetCreateFRoom_WatcherInfo {
	if m != nil {
		return m.Watchers
	}
	return nil
}

func (m *ResNetCreateFRoom) GetCurFrame() int32 {
	if m != nil {
		return m.CurFrame
	}
	return 0
}

func (m *ResNetCreateFRoom) GetRoundId() int64 {
	if m != nil {
		return m.RoundId
	}
	return 0
}

func (m *ResNetCreateFRoom) GetConfig() string {
	if m != nil {
		return m.Config
	}
	return ""
}

type ResNetCreateFRoom_Rank struct {
	NickName             string   `protobuf:"bytes,1,opt,name=nickName,proto3" json:"nickName,omitempty"`
	AvatarUrl            string   `protobuf:"bytes,2,opt,name=avatarUrl,proto3" json:"avatarUrl,omitempty"`
	Gender               int32    `protobuf:"varint,3,opt,name=gender,proto3" json:"gender,omitempty"`
	Score                int32    `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResNetCreateFRoom_Rank) Reset()         { *m = ResNetCreateFRoom_Rank{} }
func (m *ResNetCreateFRoom_Rank) String() string { return proto.CompactTextString(m) }
func (*ResNetCreateFRoom_Rank) ProtoMessage()    {}
func (*ResNetCreateFRoom_Rank) Descriptor() ([]byte, []int) {
	return fileDescriptor_36bffc8626f07b47, []int{5, 0}
}

func (m *ResNetCreateFRoom_Rank) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResNetCreateFRoom_Rank.Unmarshal(m, b)
}
func (m *ResNetCreateFRoom_Rank) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResNetCreateFRoom_Rank.Marshal(b, m, deterministic)
}
func (m *ResNetCreateFRoom_Rank) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResNetCreateFRoom_Rank.Merge(m, src)
}
func (m *ResNetCreateFRoom_Rank) XXX_Size() int {
	return xxx_messageInfo_ResNetCreateFRoom_Rank.Size(m)
}
func (m *ResNetCreateFRoom_Rank) XXX_DiscardUnknown() {
	xxx_messageInfo_ResNetCreateFRoom_Rank.DiscardUnknown(m)
}

var xxx_messageInfo_ResNetCreateFRoom_Rank proto.InternalMessageInfo

func (m *ResNetCreateFRoom_Rank) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *ResNetCreateFRoom_Rank) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *ResNetCreateFRoom_Rank) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *ResNetCreateFRoom_Rank) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

type ResNetCreateFRoom_Star3Player struct {
	NickName             string   `protobuf:"bytes,1,opt,name=nickName,proto3" json:"nickName,omitempty"`
	AvatarUrl            string   `protobuf:"bytes,2,opt,name=avatarUrl,proto3" json:"avatarUrl,omitempty"`
	ItemName             string   `protobuf:"bytes,3,opt,name=itemName,proto3" json:"itemName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResNetCreateFRoom_Star3Player) Reset()         { *m = ResNetCreateFRoom_Star3Player{} }
func (m *ResNetCreateFRoom_Star3Player) String() string { return proto.CompactTextString(m) }
func (*ResNetCreateFRoom_Star3Player) ProtoMessage()    {}
func (*ResNetCreateFRoom_Star3Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_36bffc8626f07b47, []int{5, 1}
}

func (m *ResNetCreateFRoom_Star3Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResNetCreateFRoom_Star3Player.Unmarshal(m, b)
}
func (m *ResNetCreateFRoom_Star3Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResNetCreateFRoom_Star3Player.Marshal(b, m, deterministic)
}
func (m *ResNetCreateFRoom_Star3Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResNetCreateFRoom_Star3Player.Merge(m, src)
}
func (m *ResNetCreateFRoom_Star3Player) XXX_Size() int {
	return xxx_messageInfo_ResNetCreateFRoom_Star3Player.Size(m)
}
func (m *ResNetCreateFRoom_Star3Player) XXX_DiscardUnknown() {
	xxx_messageInfo_ResNetCreateFRoom_Star3Player.DiscardUnknown(m)
}

var xxx_messageInfo_ResNetCreateFRoom_Star3Player proto.InternalMessageInfo

func (m *ResNetCreateFRoom_Star3Player) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *ResNetCreateFRoom_Star3Player) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *ResNetCreateFRoom_Star3Player) GetItemName() string {
	if m != nil {
		return m.ItemName
	}
	return ""
}

type ResNetCreateFRoom_FCommand struct {
	ExFrame              int32    `protobuf:"varint,1,opt,name=exFrame,proto3" json:"exFrame,omitempty"`
	EpFrame              int32    `protobuf:"varint,2,opt,name=epFrame,proto3" json:"epFrame,omitempty"`
	Uid                  string   `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Ctype                int32    `protobuf:"varint,4,opt,name=ctype,proto3" json:"ctype,omitempty"`
	ParamList            []int32  `protobuf:"varint,5,rep,packed,name=paramList,proto3" json:"paramList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResNetCreateFRoom_FCommand) Reset()         { *m = ResNetCreateFRoom_FCommand{} }
func (m *ResNetCreateFRoom_FCommand) String() string { return proto.CompactTextString(m) }
func (*ResNetCreateFRoom_FCommand) ProtoMessage()    {}
func (*ResNetCreateFRoom_FCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_36bffc8626f07b47, []int{5, 2}
}

func (m *ResNetCreateFRoom_FCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResNetCreateFRoom_FCommand.Unmarshal(m, b)
}
func (m *ResNetCreateFRoom_FCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResNetCreateFRoom_FCommand.Marshal(b, m, deterministic)
}
func (m *ResNetCreateFRoom_FCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResNetCreateFRoom_FCommand.Merge(m, src)
}
func (m *ResNetCreateFRoom_FCommand) XXX_Size() int {
	return xxx_messageInfo_ResNetCreateFRoom_FCommand.Size(m)
}
func (m *ResNetCreateFRoom_FCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_ResNetCreateFRoom_FCommand.DiscardUnknown(m)
}

var xxx_messageInfo_ResNetCreateFRoom_FCommand proto.InternalMessageInfo

func (m *ResNetCreateFRoom_FCommand) GetExFrame() int32 {
	if m != nil {
		return m.ExFrame
	}
	return 0
}

func (m *ResNetCreateFRoom_FCommand) GetEpFrame() int32 {
	if m != nil {
		return m.EpFrame
	}
	return 0
}

func (m *ResNetCreateFRoom_FCommand) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ResNetCreateFRoom_FCommand) GetCtype() int32 {
	if m != nil {
		return m.Ctype
	}
	return 0
}

func (m *ResNetCreateFRoom_FCommand) GetParamList() []int32 {
	if m != nil {
		return m.ParamList
	}
	return nil
}

type ResNetCreateFRoom_PlayerInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AvaUrl               string   `protobuf:"bytes,3,opt,name=avaUrl,proto3" json:"avaUrl,omitempty"`
	IsReady              bool     `protobuf:"varint,4,opt,name=isReady,proto3" json:"isReady,omitempty"`
	Have                 []string `protobuf:"bytes,5,rep,name=have,proto3" json:"have,omitempty"`
	Select               []string `protobuf:"bytes,6,rep,name=select,proto3" json:"select,omitempty"`
	Gender               int32    `protobuf:"varint,7,opt,name=gender,proto3" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResNetCreateFRoom_PlayerInfo) Reset()         { *m = ResNetCreateFRoom_PlayerInfo{} }
func (m *ResNetCreateFRoom_PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*ResNetCreateFRoom_PlayerInfo) ProtoMessage()    {}
func (*ResNetCreateFRoom_PlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_36bffc8626f07b47, []int{5, 3}
}

func (m *ResNetCreateFRoom_PlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResNetCreateFRoom_PlayerInfo.Unmarshal(m, b)
}
func (m *ResNetCreateFRoom_PlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResNetCreateFRoom_PlayerInfo.Marshal(b, m, deterministic)
}
func (m *ResNetCreateFRoom_PlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResNetCreateFRoom_PlayerInfo.Merge(m, src)
}
func (m *ResNetCreateFRoom_PlayerInfo) XXX_Size() int {
	return xxx_messageInfo_ResNetCreateFRoom_PlayerInfo.Size(m)
}
func (m *ResNetCreateFRoom_PlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ResNetCreateFRoom_PlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ResNetCreateFRoom_PlayerInfo proto.InternalMessageInfo

func (m *ResNetCreateFRoom_PlayerInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ResNetCreateFRoom_PlayerInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ResNetCreateFRoom_PlayerInfo) GetAvaUrl() string {
	if m != nil {
		return m.AvaUrl
	}
	return ""
}

func (m *ResNetCreateFRoom_PlayerInfo) GetIsReady() bool {
	if m != nil {
		return m.IsReady
	}
	return false
}

func (m *ResNetCreateFRoom_PlayerInfo) GetHave() []string {
	if m != nil {
		return m.Have
	}
	return nil
}

func (m *ResNetCreateFRoom_PlayerInfo) GetSelect() []string {
	if m != nil {
		return m.Select
	}
	return nil
}

func (m *ResNetCreateFRoom_PlayerInfo) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

type ResNetCreateFRoom_WatcherInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	TarUid               string   `protobuf:"bytes,2,opt,name=tarUid,proto3" json:"tarUid,omitempty"`
	Total                int32    `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	AvaUrl               string   `protobuf:"bytes,5,opt,name=avaUrl,proto3" json:"avaUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResNetCreateFRoom_WatcherInfo) Reset()         { *m = ResNetCreateFRoom_WatcherInfo{} }
func (m *ResNetCreateFRoom_WatcherInfo) String() string { return proto.CompactTextString(m) }
func (*ResNetCreateFRoom_WatcherInfo) ProtoMessage()    {}
func (*ResNetCreateFRoom_WatcherInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_36bffc8626f07b47, []int{5, 4}
}

func (m *ResNetCreateFRoom_WatcherInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResNetCreateFRoom_WatcherInfo.Unmarshal(m, b)
}
func (m *ResNetCreateFRoom_WatcherInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResNetCreateFRoom_WatcherInfo.Marshal(b, m, deterministic)
}
func (m *ResNetCreateFRoom_WatcherInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResNetCreateFRoom_WatcherInfo.Merge(m, src)
}
func (m *ResNetCreateFRoom_WatcherInfo) XXX_Size() int {
	return xxx_messageInfo_ResNetCreateFRoom_WatcherInfo.Size(m)
}
func (m *ResNetCreateFRoom_WatcherInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ResNetCreateFRoom_WatcherInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ResNetCreateFRoom_WatcherInfo proto.InternalMessageInfo

func (m *ResNetCreateFRoom_WatcherInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ResNetCreateFRoom_WatcherInfo) GetTarUid() string {
	if m != nil {
		return m.TarUid
	}
	return ""
}

func (m *ResNetCreateFRoom_WatcherInfo) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ResNetCreateFRoom_WatcherInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ResNetCreateFRoom_WatcherInfo) GetAvaUrl() string {
	if m != nil {
		return m.AvaUrl
	}
	return ""
}

type ResNetCreateFRoom_RoomAward struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CouponName           string   `protobuf:"bytes,2,opt,name=couponName,proto3" json:"couponName,omitempty"`
	CouponImg            string   `protobuf:"bytes,3,opt,name=couponImg,proto3" json:"couponImg,omitempty"`
	CouponDesc           string   `protobuf:"bytes,4,opt,name=couponDesc,proto3" json:"couponDesc,omitempty"`
	Weight               int32    `protobuf:"varint,5,opt,name=weight,proto3" json:"weight,omitempty"`
	Stock                int32    `protobuf:"varint,6,opt,name=stock,proto3" json:"stock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResNetCreateFRoom_RoomAward) Reset()         { *m = ResNetCreateFRoom_RoomAward{} }
func (m *ResNetCreateFRoom_RoomAward) String() string { return proto.CompactTextString(m) }
func (*ResNetCreateFRoom_RoomAward) ProtoMessage()    {}
func (*ResNetCreateFRoom_RoomAward) Descriptor() ([]byte, []int) {
	return fileDescriptor_36bffc8626f07b47, []int{5, 5}
}

func (m *ResNetCreateFRoom_RoomAward) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResNetCreateFRoom_RoomAward.Unmarshal(m, b)
}
func (m *ResNetCreateFRoom_RoomAward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResNetCreateFRoom_RoomAward.Marshal(b, m, deterministic)
}
func (m *ResNetCreateFRoom_RoomAward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResNetCreateFRoom_RoomAward.Merge(m, src)
}
func (m *ResNetCreateFRoom_RoomAward) XXX_Size() int {
	return xxx_messageInfo_ResNetCreateFRoom_RoomAward.Size(m)
}
func (m *ResNetCreateFRoom_RoomAward) XXX_DiscardUnknown() {
	xxx_messageInfo_ResNetCreateFRoom_RoomAward.DiscardUnknown(m)
}

var xxx_messageInfo_ResNetCreateFRoom_RoomAward proto.InternalMessageInfo

func (m *ResNetCreateFRoom_RoomAward) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ResNetCreateFRoom_RoomAward) GetCouponName() string {
	if m != nil {
		return m.CouponName
	}
	return ""
}

func (m *ResNetCreateFRoom_RoomAward) GetCouponImg() string {
	if m != nil {
		return m.CouponImg
	}
	return ""
}

func (m *ResNetCreateFRoom_RoomAward) GetCouponDesc() string {
	if m != nil {
		return m.CouponDesc
	}
	return ""
}

func (m *ResNetCreateFRoom_RoomAward) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *ResNetCreateFRoom_RoomAward) GetStock() int32 {
	if m != nil {
		return m.Stock
	}
	return 0
}

//大屏创建状态同步房间
type ResNetCreateSRoom struct {
	Code                 int32                            `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string                           `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	ServerId             string                           `protobuf:"bytes,3,opt,name=serverId,proto3" json:"serverId,omitempty"`
	RoomId               string                           `protobuf:"bytes,4,opt,name=roomId,proto3" json:"roomId,omitempty"`
	QrUrl                string                           `protobuf:"bytes,5,opt,name=qrUrl,proto3" json:"qrUrl,omitempty"`
	RoomState            int32                            `protobuf:"varint,6,opt,name=roomState,proto3" json:"roomState,omitempty"`
	WaitTime             int64                            `protobuf:"varint,7,opt,name=waitTime,proto3" json:"waitTime,omitempty"`
	RunTime              int64                            `protobuf:"varint,8,opt,name=runTime,proto3" json:"runTime,omitempty"`
	Star1Awards          []*ResNetCreateSRoom_RoomAward   `protobuf:"bytes,9,rep,name=star1Awards,proto3" json:"star1Awards,omitempty"`
	Star2Awards          []*ResNetCreateSRoom_RoomAward   `protobuf:"bytes,10,rep,name=star2Awards,proto3" json:"star2Awards,omitempty"`
	Star3Awards          []*ResNetCreateSRoom_RoomAward   `protobuf:"bytes,11,rep,name=star3Awards,proto3" json:"star3Awards,omitempty"`
	Star3Players         []*ResNetCreateSRoom_Star3Player `protobuf:"bytes,12,rep,name=star3Players,proto3" json:"star3Players,omitempty"`
	Players              []*ResNetCreateSRoom_PlayerInfo  `protobuf:"bytes,13,rep,name=players,proto3" json:"players,omitempty"`
	Waitings             []*ResNetCreateSRoom_PlayerInfo  `protobuf:"bytes,14,rep,name=waitings,proto3" json:"waitings,omitempty"`
	Watchers             []*ResNetCreateSRoom_WatcherInfo `protobuf:"bytes,15,rep,name=watchers,proto3" json:"watchers,omitempty"`
	SyncStates           []*ResNetCreateSRoom_RoomState   `protobuf:"bytes,16,rep,name=syncStates,proto3" json:"syncStates,omitempty"`
	RoundId              int64                            `protobuf:"varint,17,opt,name=roundId,proto3" json:"roundId,omitempty"`
	Config               string                           `protobuf:"bytes,18,opt,name=config,proto3" json:"config,omitempty"`
	RandSeed             int64                            `protobuf:"varint,19,opt,name=randSeed,proto3" json:"randSeed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *ResNetCreateSRoom) Reset()         { *m = ResNetCreateSRoom{} }
func (m *ResNetCreateSRoom) String() string { return proto.CompactTextString(m) }
func (*ResNetCreateSRoom) ProtoMessage()    {}
func (*ResNetCreateSRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_36bffc8626f07b47, []int{6}
}

func (m *ResNetCreateSRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResNetCreateSRoom.Unmarshal(m, b)
}
func (m *ResNetCreateSRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResNetCreateSRoom.Marshal(b, m, deterministic)
}
func (m *ResNetCreateSRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResNetCreateSRoom.Merge(m, src)
}
func (m *ResNetCreateSRoom) XXX_Size() int {
	return xxx_messageInfo_ResNetCreateSRoom.Size(m)
}
func (m *ResNetCreateSRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_ResNetCreateSRoom.DiscardUnknown(m)
}

var xxx_messageInfo_ResNetCreateSRoom proto.InternalMessageInfo

func (m *ResNetCreateSRoom) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResNetCreateSRoom) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ResNetCreateSRoom) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func (m *ResNetCreateSRoom) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *ResNetCreateSRoom) GetQrUrl() string {
	if m != nil {
		return m.QrUrl
	}
	return ""
}

func (m *ResNetCreateSRoom) GetRoomState() int32 {
	if m != nil {
		return m.RoomState
	}
	return 0
}

func (m *ResNetCreateSRoom) GetWaitTime() int64 {
	if m != nil {
		return m.WaitTime
	}
	return 0
}

func (m *ResNetCreateSRoom) GetRunTime() int64 {
	if m != nil {
		return m.RunTime
	}
	return 0
}

func (m *ResNetCreateSRoom) GetStar1Awards() []*ResNetCreateSRoom_RoomAward {
	if m != nil {
		return m.Star1Awards
	}
	return nil
}

func (m *ResNetCreateSRoom) GetStar2Awards() []*ResNetCreateSRoom_RoomAward {
	if m != nil {
		return m.Star2Awards
	}
	return nil
}

func (m *ResNetCreateSRoom) GetStar3Awards() []*ResNetCreateSRoom_RoomAward {
	if m != nil {
		return m.Star3Awards
	}
	return nil
}

func (m *ResNetCreateSRoom) GetStar3Players() []*ResNetCreateSRoom_Star3Player {
	if m != nil {
		return m.Star3Players
	}
	return nil
}

func (m *ResNetCreateSRoom) GetPlayers() []*ResNetCreateSRoom_PlayerInfo {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *ResNetCreateSRoom) GetWaitings() []*ResNetCreateSRoom_PlayerInfo {
	if m != nil {
		return m.Waitings
	}
	return nil
}

func (m *ResNetCreateSRoom) GetWatchers() []*ResNetCreateSRoom_WatcherInfo {
	if m != nil {
		return m.Watchers
	}
	return nil
}

func (m *ResNetCreateSRoom) GetSyncStates() []*ResNetCreateSRoom_RoomState {
	if m != nil {
		return m.SyncStates
	}
	return nil
}

func (m *ResNetCreateSRoom) GetRoundId() int64 {
	if m != nil {
		return m.RoundId
	}
	return 0
}

func (m *ResNetCreateSRoom) GetConfig() string {
	if m != nil {
		return m.Config
	}
	return ""
}

func (m *ResNetCreateSRoom) GetRandSeed() int64 {
	if m != nil {
		return m.RandSeed
	}
	return 0
}

type ResNetCreateSRoom_RoomState struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResNetCreateSRoom_RoomState) Reset()         { *m = ResNetCreateSRoom_RoomState{} }
func (m *ResNetCreateSRoom_RoomState) String() string { return proto.CompactTextString(m) }
func (*ResNetCreateSRoom_RoomState) ProtoMessage()    {}
func (*ResNetCreateSRoom_RoomState) Descriptor() ([]byte, []int) {
	return fileDescriptor_36bffc8626f07b47, []int{6, 0}
}

func (m *ResNetCreateSRoom_RoomState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResNetCreateSRoom_RoomState.Unmarshal(m, b)
}
func (m *ResNetCreateSRoom_RoomState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResNetCreateSRoom_RoomState.Marshal(b, m, deterministic)
}
func (m *ResNetCreateSRoom_RoomState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResNetCreateSRoom_RoomState.Merge(m, src)
}
func (m *ResNetCreateSRoom_RoomState) XXX_Size() int {
	return xxx_messageInfo_ResNetCreateSRoom_RoomState.Size(m)
}
func (m *ResNetCreateSRoom_RoomState) XXX_DiscardUnknown() {
	xxx_messageInfo_ResNetCreateSRoom_RoomState.DiscardUnknown(m)
}

var xxx_messageInfo_ResNetCreateSRoom_RoomState proto.InternalMessageInfo

func (m *ResNetCreateSRoom_RoomState) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ResNetCreateSRoom_RoomState) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ResNetCreateSRoom_PlayerInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AvaUrl               string   `protobuf:"bytes,3,opt,name=avaUrl,proto3" json:"avaUrl,omitempty"`
	IsReady              bool     `protobuf:"varint,4,opt,name=isReady,proto3" json:"isReady,omitempty"`
	Have                 []string `protobuf:"bytes,5,rep,name=have,proto3" json:"have,omitempty"`
	Select               []string `protobuf:"bytes,6,rep,name=select,proto3" json:"select,omitempty"`
	Gender               int32    `protobuf:"varint,7,opt,name=gender,proto3" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResNetCreateSRoom_PlayerInfo) Reset()         { *m = ResNetCreateSRoom_PlayerInfo{} }
func (m *ResNetCreateSRoom_PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*ResNetCreateSRoom_PlayerInfo) ProtoMessage()    {}
func (*ResNetCreateSRoom_PlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_36bffc8626f07b47, []int{6, 1}
}

func (m *ResNetCreateSRoom_PlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResNetCreateSRoom_PlayerInfo.Unmarshal(m, b)
}
func (m *ResNetCreateSRoom_PlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResNetCreateSRoom_PlayerInfo.Marshal(b, m, deterministic)
}
func (m *ResNetCreateSRoom_PlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResNetCreateSRoom_PlayerInfo.Merge(m, src)
}
func (m *ResNetCreateSRoom_PlayerInfo) XXX_Size() int {
	return xxx_messageInfo_ResNetCreateSRoom_PlayerInfo.Size(m)
}
func (m *ResNetCreateSRoom_PlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ResNetCreateSRoom_PlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ResNetCreateSRoom_PlayerInfo proto.InternalMessageInfo

func (m *ResNetCreateSRoom_PlayerInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ResNetCreateSRoom_PlayerInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ResNetCreateSRoom_PlayerInfo) GetAvaUrl() string {
	if m != nil {
		return m.AvaUrl
	}
	return ""
}

func (m *ResNetCreateSRoom_PlayerInfo) GetIsReady() bool {
	if m != nil {
		return m.IsReady
	}
	return false
}

func (m *ResNetCreateSRoom_PlayerInfo) GetHave() []string {
	if m != nil {
		return m.Have
	}
	return nil
}

func (m *ResNetCreateSRoom_PlayerInfo) GetSelect() []string {
	if m != nil {
		return m.Select
	}
	return nil
}

func (m *ResNetCreateSRoom_PlayerInfo) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

type ResNetCreateSRoom_WatcherInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	TarUid               string   `protobuf:"bytes,2,opt,name=tarUid,proto3" json:"tarUid,omitempty"`
	Total                int32    `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	AvaUrl               string   `protobuf:"bytes,5,opt,name=avaUrl,proto3" json:"avaUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResNetCreateSRoom_WatcherInfo) Reset()         { *m = ResNetCreateSRoom_WatcherInfo{} }
func (m *ResNetCreateSRoom_WatcherInfo) String() string { return proto.CompactTextString(m) }
func (*ResNetCreateSRoom_WatcherInfo) ProtoMessage()    {}
func (*ResNetCreateSRoom_WatcherInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_36bffc8626f07b47, []int{6, 2}
}

func (m *ResNetCreateSRoom_WatcherInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResNetCreateSRoom_WatcherInfo.Unmarshal(m, b)
}
func (m *ResNetCreateSRoom_WatcherInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResNetCreateSRoom_WatcherInfo.Marshal(b, m, deterministic)
}
func (m *ResNetCreateSRoom_WatcherInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResNetCreateSRoom_WatcherInfo.Merge(m, src)
}
func (m *ResNetCreateSRoom_WatcherInfo) XXX_Size() int {
	return xxx_messageInfo_ResNetCreateSRoom_WatcherInfo.Size(m)
}
func (m *ResNetCreateSRoom_WatcherInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ResNetCreateSRoom_WatcherInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ResNetCreateSRoom_WatcherInfo proto.InternalMessageInfo

func (m *ResNetCreateSRoom_WatcherInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ResNetCreateSRoom_WatcherInfo) GetTarUid() string {
	if m != nil {
		return m.TarUid
	}
	return ""
}

func (m *ResNetCreateSRoom_WatcherInfo) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ResNetCreateSRoom_WatcherInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ResNetCreateSRoom_WatcherInfo) GetAvaUrl() string {
	if m != nil {
		return m.AvaUrl
	}
	return ""
}

type ResNetCreateSRoom_RoomAward struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CouponName           string   `protobuf:"bytes,2,opt,name=couponName,proto3" json:"couponName,omitempty"`
	CouponImg            string   `protobuf:"bytes,3,opt,name=couponImg,proto3" json:"couponImg,omitempty"`
	CouponDesc           string   `protobuf:"bytes,4,opt,name=couponDesc,proto3" json:"couponDesc,omitempty"`
	Weight               int32    `protobuf:"varint,5,opt,name=weight,proto3" json:"weight,omitempty"`
	Stock                int32    `protobuf:"varint,6,opt,name=stock,proto3" json:"stock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResNetCreateSRoom_RoomAward) Reset()         { *m = ResNetCreateSRoom_RoomAward{} }
func (m *ResNetCreateSRoom_RoomAward) String() string { return proto.CompactTextString(m) }
func (*ResNetCreateSRoom_RoomAward) ProtoMessage()    {}
func (*ResNetCreateSRoom_RoomAward) Descriptor() ([]byte, []int) {
	return fileDescriptor_36bffc8626f07b47, []int{6, 3}
}

func (m *ResNetCreateSRoom_RoomAward) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResNetCreateSRoom_RoomAward.Unmarshal(m, b)
}
func (m *ResNetCreateSRoom_RoomAward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResNetCreateSRoom_RoomAward.Marshal(b, m, deterministic)
}
func (m *ResNetCreateSRoom_RoomAward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResNetCreateSRoom_RoomAward.Merge(m, src)
}
func (m *ResNetCreateSRoom_RoomAward) XXX_Size() int {
	return xxx_messageInfo_ResNetCreateSRoom_RoomAward.Size(m)
}
func (m *ResNetCreateSRoom_RoomAward) XXX_DiscardUnknown() {
	xxx_messageInfo_ResNetCreateSRoom_RoomAward.DiscardUnknown(m)
}

var xxx_messageInfo_ResNetCreateSRoom_RoomAward proto.InternalMessageInfo

func (m *ResNetCreateSRoom_RoomAward) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ResNetCreateSRoom_RoomAward) GetCouponName() string {
	if m != nil {
		return m.CouponName
	}
	return ""
}

func (m *ResNetCreateSRoom_RoomAward) GetCouponImg() string {
	if m != nil {
		return m.CouponImg
	}
	return ""
}

func (m *ResNetCreateSRoom_RoomAward) GetCouponDesc() string {
	if m != nil {
		return m.CouponDesc
	}
	return ""
}

func (m *ResNetCreateSRoom_RoomAward) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *ResNetCreateSRoom_RoomAward) GetStock() int32 {
	if m != nil {
		return m.Stock
	}
	return 0
}

type ResNetCreateSRoom_Star3Player struct {
	NickName             string   `protobuf:"bytes,1,opt,name=nickName,proto3" json:"nickName,omitempty"`
	AvatarUrl            string   `protobuf:"bytes,2,opt,name=avatarUrl,proto3" json:"avatarUrl,omitempty"`
	ItemName             string   `protobuf:"bytes,3,opt,name=itemName,proto3" json:"itemName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResNetCreateSRoom_Star3Player) Reset()         { *m = ResNetCreateSRoom_Star3Player{} }
func (m *ResNetCreateSRoom_Star3Player) String() string { return proto.CompactTextString(m) }
func (*ResNetCreateSRoom_Star3Player) ProtoMessage()    {}
func (*ResNetCreateSRoom_Star3Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_36bffc8626f07b47, []int{6, 4}
}

func (m *ResNetCreateSRoom_Star3Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResNetCreateSRoom_Star3Player.Unmarshal(m, b)
}
func (m *ResNetCreateSRoom_Star3Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResNetCreateSRoom_Star3Player.Marshal(b, m, deterministic)
}
func (m *ResNetCreateSRoom_Star3Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResNetCreateSRoom_Star3Player.Merge(m, src)
}
func (m *ResNetCreateSRoom_Star3Player) XXX_Size() int {
	return xxx_messageInfo_ResNetCreateSRoom_Star3Player.Size(m)
}
func (m *ResNetCreateSRoom_Star3Player) XXX_DiscardUnknown() {
	xxx_messageInfo_ResNetCreateSRoom_Star3Player.DiscardUnknown(m)
}

var xxx_messageInfo_ResNetCreateSRoom_Star3Player proto.InternalMessageInfo

func (m *ResNetCreateSRoom_Star3Player) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *ResNetCreateSRoom_Star3Player) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *ResNetCreateSRoom_Star3Player) GetItemName() string {
	if m != nil {
		return m.ItemName
	}
	return ""
}

//玩家进入状态同步房间
type ResNetEnterSRoom struct {
	Code                 int32                           `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string                          `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	RoomState            int32                           `protobuf:"varint,3,opt,name=roomState,proto3" json:"roomState,omitempty"`
	WaitTime             int64                           `protobuf:"varint,4,opt,name=waitTime,proto3" json:"waitTime,omitempty"`
	RunTime              int64                           `protobuf:"varint,5,opt,name=runTime,proto3" json:"runTime,omitempty"`
	Have                 []string                        `protobuf:"bytes,6,rep,name=have,proto3" json:"have,omitempty"`
	Select               []string                        `protobuf:"bytes,7,rep,name=select,proto3" json:"select,omitempty"`
	Players              []*ResNetEnterSRoom_PlayerInfo  `protobuf:"bytes,8,rep,name=players,proto3" json:"players,omitempty"`
	Watchers             []*ResNetEnterSRoom_WatcherInfo `protobuf:"bytes,9,rep,name=watchers,proto3" json:"watchers,omitempty"`
	SyncStates           []*ResNetEnterSRoom_RoomState   `protobuf:"bytes,10,rep,name=syncStates,proto3" json:"syncStates,omitempty"`
	Config               string                          `protobuf:"bytes,11,opt,name=config,proto3" json:"config,omitempty"`
	RandSeed             int64                           `protobuf:"varint,12,opt,name=randSeed,proto3" json:"randSeed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ResNetEnterSRoom) Reset()         { *m = ResNetEnterSRoom{} }
func (m *ResNetEnterSRoom) String() string { return proto.CompactTextString(m) }
func (*ResNetEnterSRoom) ProtoMessage()    {}
func (*ResNetEnterSRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_36bffc8626f07b47, []int{7}
}

func (m *ResNetEnterSRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResNetEnterSRoom.Unmarshal(m, b)
}
func (m *ResNetEnterSRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResNetEnterSRoom.Marshal(b, m, deterministic)
}
func (m *ResNetEnterSRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResNetEnterSRoom.Merge(m, src)
}
func (m *ResNetEnterSRoom) XXX_Size() int {
	return xxx_messageInfo_ResNetEnterSRoom.Size(m)
}
func (m *ResNetEnterSRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_ResNetEnterSRoom.DiscardUnknown(m)
}

var xxx_messageInfo_ResNetEnterSRoom proto.InternalMessageInfo

func (m *ResNetEnterSRoom) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResNetEnterSRoom) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ResNetEnterSRoom) GetRoomState() int32 {
	if m != nil {
		return m.RoomState
	}
	return 0
}

func (m *ResNetEnterSRoom) GetWaitTime() int64 {
	if m != nil {
		return m.WaitTime
	}
	return 0
}

func (m *ResNetEnterSRoom) GetRunTime() int64 {
	if m != nil {
		return m.RunTime
	}
	return 0
}

func (m *ResNetEnterSRoom) GetHave() []string {
	if m != nil {
		return m.Have
	}
	return nil
}

func (m *ResNetEnterSRoom) GetSelect() []string {
	if m != nil {
		return m.Select
	}
	return nil
}

func (m *ResNetEnterSRoom) GetPlayers() []*ResNetEnterSRoom_PlayerInfo {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *ResNetEnterSRoom) GetWatchers() []*ResNetEnterSRoom_WatcherInfo {
	if m != nil {
		return m.Watchers
	}
	return nil
}

func (m *ResNetEnterSRoom) GetSyncStates() []*ResNetEnterSRoom_RoomState {
	if m != nil {
		return m.SyncStates
	}
	return nil
}

func (m *ResNetEnterSRoom) GetConfig() string {
	if m != nil {
		return m.Config
	}
	return ""
}

func (m *ResNetEnterSRoom) GetRandSeed() int64 {
	if m != nil {
		return m.RandSeed
	}
	return 0
}

type ResNetEnterSRoom_RoomState struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResNetEnterSRoom_RoomState) Reset()         { *m = ResNetEnterSRoom_RoomState{} }
func (m *ResNetEnterSRoom_RoomState) String() string { return proto.CompactTextString(m) }
func (*ResNetEnterSRoom_RoomState) ProtoMessage()    {}
func (*ResNetEnterSRoom_RoomState) Descriptor() ([]byte, []int) {
	return fileDescriptor_36bffc8626f07b47, []int{7, 0}
}

func (m *ResNetEnterSRoom_RoomState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResNetEnterSRoom_RoomState.Unmarshal(m, b)
}
func (m *ResNetEnterSRoom_RoomState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResNetEnterSRoom_RoomState.Marshal(b, m, deterministic)
}
func (m *ResNetEnterSRoom_RoomState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResNetEnterSRoom_RoomState.Merge(m, src)
}
func (m *ResNetEnterSRoom_RoomState) XXX_Size() int {
	return xxx_messageInfo_ResNetEnterSRoom_RoomState.Size(m)
}
func (m *ResNetEnterSRoom_RoomState) XXX_DiscardUnknown() {
	xxx_messageInfo_ResNetEnterSRoom_RoomState.DiscardUnknown(m)
}

var xxx_messageInfo_ResNetEnterSRoom_RoomState proto.InternalMessageInfo

func (m *ResNetEnterSRoom_RoomState) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ResNetEnterSRoom_RoomState) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ResNetEnterSRoom_PlayerInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AvaUrl               string   `protobuf:"bytes,3,opt,name=avaUrl,proto3" json:"avaUrl,omitempty"`
	IsReady              bool     `protobuf:"varint,4,opt,name=isReady,proto3" json:"isReady,omitempty"`
	Have                 []string `protobuf:"bytes,5,rep,name=have,proto3" json:"have,omitempty"`
	Select               []string `protobuf:"bytes,6,rep,name=select,proto3" json:"select,omitempty"`
	Gender               int32    `protobuf:"varint,7,opt,name=gender,proto3" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResNetEnterSRoom_PlayerInfo) Reset()         { *m = ResNetEnterSRoom_PlayerInfo{} }
func (m *ResNetEnterSRoom_PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*ResNetEnterSRoom_PlayerInfo) ProtoMessage()    {}
func (*ResNetEnterSRoom_PlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_36bffc8626f07b47, []int{7, 1}
}

func (m *ResNetEnterSRoom_PlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResNetEnterSRoom_PlayerInfo.Unmarshal(m, b)
}
func (m *ResNetEnterSRoom_PlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResNetEnterSRoom_PlayerInfo.Marshal(b, m, deterministic)
}
func (m *ResNetEnterSRoom_PlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResNetEnterSRoom_PlayerInfo.Merge(m, src)
}
func (m *ResNetEnterSRoom_PlayerInfo) XXX_Size() int {
	return xxx_messageInfo_ResNetEnterSRoom_PlayerInfo.Size(m)
}
func (m *ResNetEnterSRoom_PlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ResNetEnterSRoom_PlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ResNetEnterSRoom_PlayerInfo proto.InternalMessageInfo

func (m *ResNetEnterSRoom_PlayerInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ResNetEnterSRoom_PlayerInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ResNetEnterSRoom_PlayerInfo) GetAvaUrl() string {
	if m != nil {
		return m.AvaUrl
	}
	return ""
}

func (m *ResNetEnterSRoom_PlayerInfo) GetIsReady() bool {
	if m != nil {
		return m.IsReady
	}
	return false
}

func (m *ResNetEnterSRoom_PlayerInfo) GetHave() []string {
	if m != nil {
		return m.Have
	}
	return nil
}

func (m *ResNetEnterSRoom_PlayerInfo) GetSelect() []string {
	if m != nil {
		return m.Select
	}
	return nil
}

func (m *ResNetEnterSRoom_PlayerInfo) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

type ResNetEnterSRoom_WatcherInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	TarUid               string   `protobuf:"bytes,2,opt,name=tarUid,proto3" json:"tarUid,omitempty"`
	Total                int32    `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	AvaUrl               string   `protobuf:"bytes,5,opt,name=avaUrl,proto3" json:"avaUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResNetEnterSRoom_WatcherInfo) Reset()         { *m = ResNetEnterSRoom_WatcherInfo{} }
func (m *ResNetEnterSRoom_WatcherInfo) String() string { return proto.CompactTextString(m) }
func (*ResNetEnterSRoom_WatcherInfo) ProtoMessage()    {}
func (*ResNetEnterSRoom_WatcherInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_36bffc8626f07b47, []int{7, 2}
}

func (m *ResNetEnterSRoom_WatcherInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResNetEnterSRoom_WatcherInfo.Unmarshal(m, b)
}
func (m *ResNetEnterSRoom_WatcherInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResNetEnterSRoom_WatcherInfo.Marshal(b, m, deterministic)
}
func (m *ResNetEnterSRoom_WatcherInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResNetEnterSRoom_WatcherInfo.Merge(m, src)
}
func (m *ResNetEnterSRoom_WatcherInfo) XXX_Size() int {
	return xxx_messageInfo_ResNetEnterSRoom_WatcherInfo.Size(m)
}
func (m *ResNetEnterSRoom_WatcherInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ResNetEnterSRoom_WatcherInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ResNetEnterSRoom_WatcherInfo proto.InternalMessageInfo

func (m *ResNetEnterSRoom_WatcherInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ResNetEnterSRoom_WatcherInfo) GetTarUid() string {
	if m != nil {
		return m.TarUid
	}
	return ""
}

func (m *ResNetEnterSRoom_WatcherInfo) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ResNetEnterSRoom_WatcherInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ResNetEnterSRoom_WatcherInfo) GetAvaUrl() string {
	if m != nil {
		return m.AvaUrl
	}
	return ""
}

//--------------client proto--------------
type ResSyncPlayerData struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	BoxCount             int32    `protobuf:"varint,2,opt,name=boxCount,proto3" json:"boxCount,omitempty"`
	Score                int32    `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	Popularity           int32    `protobuf:"varint,4,opt,name=popularity,proto3" json:"popularity,omitempty"`
	LeftGameTime         int32    `protobuf:"varint,5,opt,name=leftGameTime,proto3" json:"leftGameTime,omitempty"`
	MaxPopularityUid     string   `protobuf:"bytes,6,opt,name=maxPopularityUid,proto3" json:"maxPopularityUid,omitempty"`
	PlayerIndex          int32    `protobuf:"varint,7,opt,name=playerIndex,proto3" json:"playerIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResSyncPlayerData) Reset()         { *m = ResSyncPlayerData{} }
func (m *ResSyncPlayerData) String() string { return proto.CompactTextString(m) }
func (*ResSyncPlayerData) ProtoMessage()    {}
func (*ResSyncPlayerData) Descriptor() ([]byte, []int) {
	return fileDescriptor_36bffc8626f07b47, []int{8}
}

func (m *ResSyncPlayerData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResSyncPlayerData.Unmarshal(m, b)
}
func (m *ResSyncPlayerData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResSyncPlayerData.Marshal(b, m, deterministic)
}
func (m *ResSyncPlayerData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResSyncPlayerData.Merge(m, src)
}
func (m *ResSyncPlayerData) XXX_Size() int {
	return xxx_messageInfo_ResSyncPlayerData.Size(m)
}
func (m *ResSyncPlayerData) XXX_DiscardUnknown() {
	xxx_messageInfo_ResSyncPlayerData.DiscardUnknown(m)
}

var xxx_messageInfo_ResSyncPlayerData proto.InternalMessageInfo

func (m *ResSyncPlayerData) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ResSyncPlayerData) GetBoxCount() int32 {
	if m != nil {
		return m.BoxCount
	}
	return 0
}

func (m *ResSyncPlayerData) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *ResSyncPlayerData) GetPopularity() int32 {
	if m != nil {
		return m.Popularity
	}
	return 0
}

func (m *ResSyncPlayerData) GetLeftGameTime() int32 {
	if m != nil {
		return m.LeftGameTime
	}
	return 0
}

func (m *ResSyncPlayerData) GetMaxPopularityUid() string {
	if m != nil {
		return m.MaxPopularityUid
	}
	return ""
}

func (m *ResSyncPlayerData) GetPlayerIndex() int32 {
	if m != nil {
		return m.PlayerIndex
	}
	return 0
}

type ResGamRandomAward struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	CouponName           string   `protobuf:"bytes,4,opt,name=couponName,proto3" json:"couponName,omitempty"`
	CouponImg            string   `protobuf:"bytes,5,opt,name=couponImg,proto3" json:"couponImg,omitempty"`
	CouponDesc           string   `protobuf:"bytes,6,opt,name=couponDesc,proto3" json:"couponDesc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResGamRandomAward) Reset()         { *m = ResGamRandomAward{} }
func (m *ResGamRandomAward) String() string { return proto.CompactTextString(m) }
func (*ResGamRandomAward) ProtoMessage()    {}
func (*ResGamRandomAward) Descriptor() ([]byte, []int) {
	return fileDescriptor_36bffc8626f07b47, []int{9}
}

func (m *ResGamRandomAward) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResGamRandomAward.Unmarshal(m, b)
}
func (m *ResGamRandomAward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResGamRandomAward.Marshal(b, m, deterministic)
}
func (m *ResGamRandomAward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResGamRandomAward.Merge(m, src)
}
func (m *ResGamRandomAward) XXX_Size() int {
	return xxx_messageInfo_ResGamRandomAward.Size(m)
}
func (m *ResGamRandomAward) XXX_DiscardUnknown() {
	xxx_messageInfo_ResGamRandomAward.DiscardUnknown(m)
}

var xxx_messageInfo_ResGamRandomAward proto.InternalMessageInfo

func (m *ResGamRandomAward) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResGamRandomAward) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ResGamRandomAward) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ResGamRandomAward) GetCouponName() string {
	if m != nil {
		return m.CouponName
	}
	return ""
}

func (m *ResGamRandomAward) GetCouponImg() string {
	if m != nil {
		return m.CouponImg
	}
	return ""
}

func (m *ResGamRandomAward) GetCouponDesc() string {
	if m != nil {
		return m.CouponDesc
	}
	return ""
}

type ResNetEnterTRoom struct {
	Code                 int32                          `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string                         `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	WaitTime             int64                          `protobuf:"varint,3,opt,name=waitTime,proto3" json:"waitTime,omitempty"`
	RunTime              int64                          `protobuf:"varint,4,opt,name=runTime,proto3" json:"runTime,omitempty"`
	Have                 []string                       `protobuf:"bytes,5,rep,name=have,proto3" json:"have,omitempty"`
	Select               []string                       `protobuf:"bytes,6,rep,name=select,proto3" json:"select,omitempty"`
	Players              []*ResNetEnterTRoom_PlayerInfo `protobuf:"bytes,7,rep,name=players,proto3" json:"players,omitempty"`
	SyncStates           []*ResNetEnterTRoom_RoomState  `protobuf:"bytes,8,rep,name=syncStates,proto3" json:"syncStates,omitempty"`
	Config               string                         `protobuf:"bytes,9,opt,name=config,proto3" json:"config,omitempty"`
	Star1Awards          []*ResNetEnterTRoom_RoomAward  `protobuf:"bytes,10,rep,name=star1Awards,proto3" json:"star1Awards,omitempty"`
	Star2Awards          []*ResNetEnterTRoom_RoomAward  `protobuf:"bytes,11,rep,name=star2Awards,proto3" json:"star2Awards,omitempty"`
	Star3Awards          []*ResNetEnterTRoom_RoomAward  `protobuf:"bytes,12,rep,name=star3Awards,proto3" json:"star3Awards,omitempty"`
	RandSeed             int64                          `protobuf:"varint,13,opt,name=randSeed,proto3" json:"randSeed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *ResNetEnterTRoom) Reset()         { *m = ResNetEnterTRoom{} }
func (m *ResNetEnterTRoom) String() string { return proto.CompactTextString(m) }
func (*ResNetEnterTRoom) ProtoMessage()    {}
func (*ResNetEnterTRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_36bffc8626f07b47, []int{10}
}

func (m *ResNetEnterTRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResNetEnterTRoom.Unmarshal(m, b)
}
func (m *ResNetEnterTRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResNetEnterTRoom.Marshal(b, m, deterministic)
}
func (m *ResNetEnterTRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResNetEnterTRoom.Merge(m, src)
}
func (m *ResNetEnterTRoom) XXX_Size() int {
	return xxx_messageInfo_ResNetEnterTRoom.Size(m)
}
func (m *ResNetEnterTRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_ResNetEnterTRoom.DiscardUnknown(m)
}

var xxx_messageInfo_ResNetEnterTRoom proto.InternalMessageInfo

func (m *ResNetEnterTRoom) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResNetEnterTRoom) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ResNetEnterTRoom) GetWaitTime() int64 {
	if m != nil {
		return m.WaitTime
	}
	return 0
}

func (m *ResNetEnterTRoom) GetRunTime() int64 {
	if m != nil {
		return m.RunTime
	}
	return 0
}

func (m *ResNetEnterTRoom) GetHave() []string {
	if m != nil {
		return m.Have
	}
	return nil
}

func (m *ResNetEnterTRoom) GetSelect() []string {
	if m != nil {
		return m.Select
	}
	return nil
}

func (m *ResNetEnterTRoom) GetPlayers() []*ResNetEnterTRoom_PlayerInfo {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *ResNetEnterTRoom) GetSyncStates() []*ResNetEnterTRoom_RoomState {
	if m != nil {
		return m.SyncStates
	}
	return nil
}

func (m *ResNetEnterTRoom) GetConfig() string {
	if m != nil {
		return m.Config
	}
	return ""
}

func (m *ResNetEnterTRoom) GetStar1Awards() []*ResNetEnterTRoom_RoomAward {
	if m != nil {
		return m.Star1Awards
	}
	return nil
}

func (m *ResNetEnterTRoom) GetStar2Awards() []*ResNetEnterTRoom_RoomAward {
	if m != nil {
		return m.Star2Awards
	}
	return nil
}

func (m *ResNetEnterTRoom) GetStar3Awards() []*ResNetEnterTRoom_RoomAward {
	if m != nil {
		return m.Star3Awards
	}
	return nil
}

func (m *ResNetEnterTRoom) GetRandSeed() int64 {
	if m != nil {
		return m.RandSeed
	}
	return 0
}

type ResNetEnterTRoom_RoomState struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResNetEnterTRoom_RoomState) Reset()         { *m = ResNetEnterTRoom_RoomState{} }
func (m *ResNetEnterTRoom_RoomState) String() string { return proto.CompactTextString(m) }
func (*ResNetEnterTRoom_RoomState) ProtoMessage()    {}
func (*ResNetEnterTRoom_RoomState) Descriptor() ([]byte, []int) {
	return fileDescriptor_36bffc8626f07b47, []int{10, 0}
}

func (m *ResNetEnterTRoom_RoomState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResNetEnterTRoom_RoomState.Unmarshal(m, b)
}
func (m *ResNetEnterTRoom_RoomState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResNetEnterTRoom_RoomState.Marshal(b, m, deterministic)
}
func (m *ResNetEnterTRoom_RoomState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResNetEnterTRoom_RoomState.Merge(m, src)
}
func (m *ResNetEnterTRoom_RoomState) XXX_Size() int {
	return xxx_messageInfo_ResNetEnterTRoom_RoomState.Size(m)
}
func (m *ResNetEnterTRoom_RoomState) XXX_DiscardUnknown() {
	xxx_messageInfo_ResNetEnterTRoom_RoomState.DiscardUnknown(m)
}

var xxx_messageInfo_ResNetEnterTRoom_RoomState proto.InternalMessageInfo

func (m *ResNetEnterTRoom_RoomState) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ResNetEnterTRoom_RoomState) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ResNetEnterTRoom_PlayerInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AvaUrl               string   `protobuf:"bytes,3,opt,name=avaUrl,proto3" json:"avaUrl,omitempty"`
	IsReady              bool     `protobuf:"varint,4,opt,name=isReady,proto3" json:"isReady,omitempty"`
	Have                 []string `protobuf:"bytes,5,rep,name=have,proto3" json:"have,omitempty"`
	Select               []string `protobuf:"bytes,6,rep,name=select,proto3" json:"select,omitempty"`
	Gender               int32    `protobuf:"varint,7,opt,name=gender,proto3" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResNetEnterTRoom_PlayerInfo) Reset()         { *m = ResNetEnterTRoom_PlayerInfo{} }
func (m *ResNetEnterTRoom_PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*ResNetEnterTRoom_PlayerInfo) ProtoMessage()    {}
func (*ResNetEnterTRoom_PlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_36bffc8626f07b47, []int{10, 1}
}

func (m *ResNetEnterTRoom_PlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResNetEnterTRoom_PlayerInfo.Unmarshal(m, b)
}
func (m *ResNetEnterTRoom_PlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResNetEnterTRoom_PlayerInfo.Marshal(b, m, deterministic)
}
func (m *ResNetEnterTRoom_PlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResNetEnterTRoom_PlayerInfo.Merge(m, src)
}
func (m *ResNetEnterTRoom_PlayerInfo) XXX_Size() int {
	return xxx_messageInfo_ResNetEnterTRoom_PlayerInfo.Size(m)
}
func (m *ResNetEnterTRoom_PlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ResNetEnterTRoom_PlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ResNetEnterTRoom_PlayerInfo proto.InternalMessageInfo

func (m *ResNetEnterTRoom_PlayerInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ResNetEnterTRoom_PlayerInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ResNetEnterTRoom_PlayerInfo) GetAvaUrl() string {
	if m != nil {
		return m.AvaUrl
	}
	return ""
}

func (m *ResNetEnterTRoom_PlayerInfo) GetIsReady() bool {
	if m != nil {
		return m.IsReady
	}
	return false
}

func (m *ResNetEnterTRoom_PlayerInfo) GetHave() []string {
	if m != nil {
		return m.Have
	}
	return nil
}

func (m *ResNetEnterTRoom_PlayerInfo) GetSelect() []string {
	if m != nil {
		return m.Select
	}
	return nil
}

func (m *ResNetEnterTRoom_PlayerInfo) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

type ResNetEnterTRoom_RoomAward struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CouponName           string   `protobuf:"bytes,2,opt,name=couponName,proto3" json:"couponName,omitempty"`
	CouponImg            string   `protobuf:"bytes,3,opt,name=couponImg,proto3" json:"couponImg,omitempty"`
	CouponDesc           string   `protobuf:"bytes,4,opt,name=couponDesc,proto3" json:"couponDesc,omitempty"`
	Weight               int32    `protobuf:"varint,5,opt,name=weight,proto3" json:"weight,omitempty"`
	Stock                int32    `protobuf:"varint,6,opt,name=stock,proto3" json:"stock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResNetEnterTRoom_RoomAward) Reset()         { *m = ResNetEnterTRoom_RoomAward{} }
func (m *ResNetEnterTRoom_RoomAward) String() string { return proto.CompactTextString(m) }
func (*ResNetEnterTRoom_RoomAward) ProtoMessage()    {}
func (*ResNetEnterTRoom_RoomAward) Descriptor() ([]byte, []int) {
	return fileDescriptor_36bffc8626f07b47, []int{10, 2}
}

func (m *ResNetEnterTRoom_RoomAward) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResNetEnterTRoom_RoomAward.Unmarshal(m, b)
}
func (m *ResNetEnterTRoom_RoomAward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResNetEnterTRoom_RoomAward.Marshal(b, m, deterministic)
}
func (m *ResNetEnterTRoom_RoomAward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResNetEnterTRoom_RoomAward.Merge(m, src)
}
func (m *ResNetEnterTRoom_RoomAward) XXX_Size() int {
	return xxx_messageInfo_ResNetEnterTRoom_RoomAward.Size(m)
}
func (m *ResNetEnterTRoom_RoomAward) XXX_DiscardUnknown() {
	xxx_messageInfo_ResNetEnterTRoom_RoomAward.DiscardUnknown(m)
}

var xxx_messageInfo_ResNetEnterTRoom_RoomAward proto.InternalMessageInfo

func (m *ResNetEnterTRoom_RoomAward) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ResNetEnterTRoom_RoomAward) GetCouponName() string {
	if m != nil {
		return m.CouponName
	}
	return ""
}

func (m *ResNetEnterTRoom_RoomAward) GetCouponImg() string {
	if m != nil {
		return m.CouponImg
	}
	return ""
}

func (m *ResNetEnterTRoom_RoomAward) GetCouponDesc() string {
	if m != nil {
		return m.CouponDesc
	}
	return ""
}

func (m *ResNetEnterTRoom_RoomAward) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *ResNetEnterTRoom_RoomAward) GetStock() int32 {
	if m != nil {
		return m.Stock
	}
	return 0
}

func init() {
	proto.RegisterType((*ResNetLogin)(nil), "gopb.ResNetLogin")
	proto.RegisterType((*ResNetLogin_Player)(nil), "gopb.ResNetLogin.Player")
	proto.RegisterType((*ResNetEnterMatchQueue)(nil), "gopb.ResNetEnterMatchQueue")
	proto.RegisterType((*ResError)(nil), "gopb.ResError")
	proto.RegisterType((*ResVersionAddr)(nil), "gopb.ResVersionAddr")
	proto.RegisterType((*ResNetEnterFRoom)(nil), "gopb.ResNetEnterFRoom")
	proto.RegisterType((*ResNetEnterFRoom_FCommand)(nil), "gopb.ResNetEnterFRoom.FCommand")
	proto.RegisterType((*ResNetEnterFRoom_PlayerInfo)(nil), "gopb.ResNetEnterFRoom.PlayerInfo")
	proto.RegisterType((*ResNetEnterFRoom_WatcherInfo)(nil), "gopb.ResNetEnterFRoom.WatcherInfo")
	proto.RegisterType((*ResNetCreateFRoom)(nil), "gopb.ResNetCreateFRoom")
	proto.RegisterType((*ResNetCreateFRoom_Rank)(nil), "gopb.ResNetCreateFRoom.Rank")
	proto.RegisterType((*ResNetCreateFRoom_Star3Player)(nil), "gopb.ResNetCreateFRoom.Star3Player")
	proto.RegisterType((*ResNetCreateFRoom_FCommand)(nil), "gopb.ResNetCreateFRoom.FCommand")
	proto.RegisterType((*ResNetCreateFRoom_PlayerInfo)(nil), "gopb.ResNetCreateFRoom.PlayerInfo")
	proto.RegisterType((*ResNetCreateFRoom_WatcherInfo)(nil), "gopb.ResNetCreateFRoom.WatcherInfo")
	proto.RegisterType((*ResNetCreateFRoom_RoomAward)(nil), "gopb.ResNetCreateFRoom.RoomAward")
	proto.RegisterType((*ResNetCreateSRoom)(nil), "gopb.ResNetCreateSRoom")
	proto.RegisterType((*ResNetCreateSRoom_RoomState)(nil), "gopb.ResNetCreateSRoom.RoomState")
	proto.RegisterType((*ResNetCreateSRoom_PlayerInfo)(nil), "gopb.ResNetCreateSRoom.PlayerInfo")
	proto.RegisterType((*ResNetCreateSRoom_WatcherInfo)(nil), "gopb.ResNetCreateSRoom.WatcherInfo")
	proto.RegisterType((*ResNetCreateSRoom_RoomAward)(nil), "gopb.ResNetCreateSRoom.RoomAward")
	proto.RegisterType((*ResNetCreateSRoom_Star3Player)(nil), "gopb.ResNetCreateSRoom.Star3Player")
	proto.RegisterType((*ResNetEnterSRoom)(nil), "gopb.ResNetEnterSRoom")
	proto.RegisterType((*ResNetEnterSRoom_RoomState)(nil), "gopb.ResNetEnterSRoom.RoomState")
	proto.RegisterType((*ResNetEnterSRoom_PlayerInfo)(nil), "gopb.ResNetEnterSRoom.PlayerInfo")
	proto.RegisterType((*ResNetEnterSRoom_WatcherInfo)(nil), "gopb.ResNetEnterSRoom.WatcherInfo")
	proto.RegisterType((*ResSyncPlayerData)(nil), "gopb.ResSyncPlayerData")
	proto.RegisterType((*ResGamRandomAward)(nil), "gopb.ResGamRandomAward")
	proto.RegisterType((*ResNetEnterTRoom)(nil), "gopb.ResNetEnterTRoom")
	proto.RegisterType((*ResNetEnterTRoom_RoomState)(nil), "gopb.ResNetEnterTRoom.RoomState")
	proto.RegisterType((*ResNetEnterTRoom_PlayerInfo)(nil), "gopb.ResNetEnterTRoom.PlayerInfo")
	proto.RegisterType((*ResNetEnterTRoom_RoomAward)(nil), "gopb.ResNetEnterTRoom.RoomAward")
}

func init() { proto.RegisterFile("res.proto", fileDescriptor_36bffc8626f07b47) }

var fileDescriptor_36bffc8626f07b47 = []byte{
	// 1416 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x59, 0x4d, 0x6f, 0xdb, 0x46,
	0x13, 0x86, 0x4c, 0x89, 0xa2, 0x86, 0xb2, 0xe3, 0x6c, 0x3e, 0x40, 0x08, 0x2f, 0xf2, 0xaa, 0xec,
	0xc5, 0xe8, 0xc1, 0x48, 0x9c, 0x63, 0x8b, 0xb4, 0x89, 0x13, 0xa7, 0x06, 0x52, 0x23, 0xa1, 0x9c,
	0xf6, 0xbc, 0x21, 0xd7, 0x0a, 0x61, 0x91, 0xab, 0x2e, 0x57, 0xb6, 0x75, 0xcf, 0xb9, 0xc7, 0xde,
	0x7b, 0x4a, 0x7f, 0x45, 0xff, 0x4f, 0xff, 0x42, 0x4f, 0xc5, 0x7e, 0x90, 0x5c, 0xca, 0xa4, 0x42,
	0xa1, 0x40, 0x80, 0xb4, 0xb9, 0x18, 0x7a, 0x86, 0x9c, 0x87, 0xbb, 0xb3, 0x33, 0xcf, 0x0c, 0x69,
	0x18, 0x30, 0x92, 0xed, 0xcf, 0x19, 0xe5, 0x14, 0x75, 0xa7, 0x74, 0xfe, 0xc6, 0xff, 0x75, 0x0b,
	0xdc, 0x80, 0x64, 0x27, 0x84, 0xbf, 0xa0, 0xd3, 0x38, 0x45, 0x08, 0xba, 0x21, 0x8d, 0x88, 0xd7,
	0x19, 0x77, 0xf6, 0x7a, 0x81, 0xfc, 0x8d, 0x76, 0xc1, 0x4a, 0xb2, 0xa9, 0xb7, 0x35, 0xee, 0xec,
	0x0d, 0x02, 0xf1, 0x13, 0xdd, 0x07, 0x7b, 0x3e, 0xc3, 0x4b, 0xc2, 0x3c, 0x6b, 0xdc, 0xd9, 0x73,
	0x0f, 0xbc, 0x7d, 0x41, 0xb6, 0x6f, 0x10, 0xed, 0xbf, 0x94, 0xd7, 0x03, 0x7d, 0x1f, 0xba, 0x07,
	0x30, 0xc5, 0x09, 0x39, 0xa4, 0xe9, 0x59, 0x3c, 0xf5, 0xba, 0x92, 0xca, 0xb0, 0x8c, 0x7e, 0xe9,
	0x80, 0xad, 0x5c, 0xd0, 0x08, 0x9c, 0x45, 0x46, 0x58, 0x8a, 0x13, 0xb5, 0x8c, 0x41, 0x50, 0x60,
	0xb1, 0x94, 0x45, 0x1c, 0xe5, 0x4b, 0x59, 0xc4, 0x91, 0x58, 0xb0, 0xbc, 0xd3, 0x92, 0x26, 0xf9,
	0x1b, 0xdd, 0x05, 0x1b, 0x5f, 0xe0, 0xd7, 0x6c, 0xa6, 0x1f, 0xa4, 0x11, 0xba, 0x0d, 0xbd, 0x2c,
	0xa4, 0x8c, 0x78, 0x3d, 0xb9, 0x3b, 0x05, 0x84, 0x75, 0x46, 0x2e, 0xc8, 0xcc, 0xb3, 0x95, 0x55,
	0x02, 0xff, 0x15, 0xdc, 0x51, 0xdb, 0x79, 0x96, 0x72, 0xc2, 0x7e, 0xc0, 0x3c, 0x7c, 0xfb, 0x6a,
	0x41, 0x16, 0xa4, 0x65, 0x84, 0x10, 0x74, 0x23, 0xcc, 0x71, 0xbe, 0x2c, 0xf1, 0xdb, 0xbf, 0x0f,
	0x4e, 0x40, 0xb2, 0x67, 0x8c, 0x51, 0xd6, 0x8e, 0xc5, 0xff, 0x1e, 0x76, 0x02, 0x92, 0xfd, 0x48,
	0x58, 0x16, 0xd3, 0xf4, 0x71, 0x14, 0xb5, 0xf4, 0x93, 0x61, 0x62, 0x33, 0xfd, 0x70, 0xf1, 0xd3,
	0xff, 0xab, 0x0f, 0xbb, 0xc6, 0x7e, 0x8e, 0x02, 0x4a, 0x93, 0x96, 0x64, 0xff, 0x83, 0xc1, 0x19,
	0xc3, 0x09, 0x39, 0x8d, 0x75, 0x98, 0x7b, 0x41, 0x69, 0x10, 0xa7, 0x75, 0x4e, 0x96, 0x47, 0x02,
	0xcb, 0x68, 0xf7, 0x82, 0x02, 0x8b, 0x6b, 0x0c, 0xa7, 0xd1, 0x84, 0x90, 0x48, 0x86, 0xdc, 0x0a,
	0x0a, 0x2c, 0x58, 0x19, 0xa5, 0xc9, 0x84, 0x63, 0x4e, 0x74, 0xe4, 0x4b, 0x03, 0xfa, 0x1a, 0xfa,
	0x2a, 0x71, 0x32, 0xaf, 0x3f, 0xb6, 0xf6, 0xdc, 0x83, 0x2f, 0xcc, 0x0c, 0x2b, 0xb7, 0xa0, 0xd3,
	0xec, 0x38, 0x3d, 0xa3, 0x41, 0xee, 0x81, 0x0e, 0x61, 0x18, 0xa7, 0x31, 0x3f, 0xa4, 0x49, 0x82,
	0xd3, 0x28, 0xf3, 0x1c, 0xc9, 0xf0, 0xff, 0x06, 0x86, 0x23, 0x7d, 0x5f, 0x50, 0x71, 0x42, 0xcf,
	0x60, 0x3b, 0xa2, 0x71, 0x3a, 0x2d, 0x58, 0x06, 0xed, 0x58, 0xaa, 0x5e, 0x22, 0xc4, 0x6f, 0xf1,
	0x05, 0xf1, 0x60, 0x6c, 0x89, 0x3c, 0x10, 0xbf, 0x45, 0x58, 0x32, 0xc2, 0x2e, 0x08, 0x3b, 0x8e,
	0x3c, 0x57, 0x25, 0x78, 0x8e, 0x45, 0xea, 0x8a, 0x28, 0x1c, 0x47, 0xde, 0x50, 0xa5, 0xae, 0x42,
	0xc2, 0x27, 0x5c, 0x30, 0x15, 0xe6, 0x6d, 0x15, 0xe6, 0x1c, 0xa3, 0x47, 0xe0, 0x5c, 0x8a, 0xfc,
	0x14, 0xd1, 0xda, 0x91, 0xab, 0xf4, 0x1b, 0x56, 0xf9, 0x93, 0xba, 0x4d, 0x86, 0xab, 0xf0, 0x11,
	0xcf, 0x0c, 0x55, 0x5d, 0xde, 0x50, 0xcf, 0x54, 0x48, 0x3c, 0xf3, 0x12, 0xc7, 0x5c, 0x9e, 0xfb,
	0xae, 0x3a, 0xbe, 0x1c, 0x8f, 0xde, 0x75, 0xc0, 0xc9, 0xf7, 0x8c, 0x3c, 0xe8, 0x93, 0x2b, 0xb5,
	0x36, 0x95, 0x4a, 0x39, 0x94, 0x57, 0xe6, 0xea, 0xca, 0x96, 0xbe, 0xa2, 0x60, 0x5e, 0xc9, 0x56,
	0x59, 0xc9, 0xb7, 0xa1, 0x17, 0xf2, 0xe5, 0x3c, 0x4f, 0x23, 0x05, 0x44, 0x9e, 0xcc, 0x31, 0xc3,
	0xc9, 0x8b, 0x38, 0xe3, 0x5e, 0x6f, 0x6c, 0x89, 0x3c, 0x29, 0x0c, 0xa3, 0xdf, 0x3b, 0x00, 0x65,
	0x0a, 0xe4, 0xa4, 0x9d, 0xeb, 0xf2, 0xb0, 0x55, 0x2b, 0x0f, 0x56, 0x45, 0x1e, 0x3c, 0xe8, 0xc7,
	0x59, 0x40, 0x70, 0xb4, 0x94, 0x4b, 0x70, 0x82, 0x1c, 0x16, 0xa7, 0xd8, 0x33, 0x4e, 0xf1, 0x2e,
	0xd8, 0x19, 0x99, 0x91, 0x90, 0x7b, 0xb6, 0xb4, 0x6a, 0x24, 0xec, 0x53, 0x92, 0x46, 0x84, 0x79,
	0x7d, 0xb9, 0x0f, 0x8d, 0x46, 0x4b, 0x70, 0x8d, 0xf0, 0xd7, 0x2c, 0xf5, 0x2e, 0xd8, 0x1c, 0xb3,
	0xd7, 0x85, 0xbc, 0x69, 0x24, 0xe2, 0xc2, 0x29, 0xc7, 0x33, 0x5d, 0x7b, 0x0a, 0x14, 0x1b, 0xeb,
	0xd6, 0x6e, 0xac, 0x67, 0x6e, 0xcc, 0xff, 0x63, 0x1b, 0x6e, 0xaa, 0x5c, 0x38, 0x64, 0x04, 0x73,
	0xb2, 0x61, 0xf5, 0x97, 0x75, 0x6a, 0xad, 0xd6, 0xa9, 0x99, 0x22, 0xdd, 0x6a, 0x8a, 0x88, 0x75,
	0xff, 0xcc, 0xca, 0xc5, 0x28, 0x50, 0x55, 0x13, 0x7b, 0x9d, 0x9a, 0xf4, 0xd7, 0xa8, 0x89, 0xb3,
	0xa2, 0x26, 0x4f, 0x57, 0x4a, 0x5e, 0x15, 0xeb, 0xd8, 0x2c, 0x03, 0x63, 0xeb, 0x4d, 0x35, 0x7f,
	0xb4, 0x5a, 0xf3, 0xd0, 0x92, 0x66, 0xa5, 0xe8, 0x0f, 0xc1, 0xcd, 0x38, 0x66, 0x0f, 0x1e, 0x5f,
	0x62, 0x16, 0x65, 0x9e, 0x7b, 0x5d, 0xc1, 0x4c, 0x16, 0xf1, 0x47, 0xde, 0x19, 0x98, 0x5e, 0x39,
	0xc9, 0x81, 0x26, 0x19, 0x6e, 0x44, 0x72, 0x50, 0x25, 0x79, 0xa8, 0x49, 0xb6, 0x37, 0x22, 0xd1,
	0x5e, 0xe8, 0x39, 0x0c, 0x25, 0x7c, 0xa9, 0x15, 0xf9, 0x86, 0x64, 0xf9, 0xb2, 0x89, 0x65, 0x52,
	0xde, 0x1b, 0x54, 0x1c, 0xd1, 0x37, 0xa5, 0xaa, 0xef, 0x5e, 0xd7, 0x29, 0x93, 0xa3, 0x4e, 0xd6,
	0x1f, 0xa9, 0x5c, 0x8b, 0xd3, 0x69, 0xe6, 0xdd, 0x6c, 0xed, 0x5e, 0xf8, 0xa0, 0x6f, 0x0d, 0x99,
	0x44, 0xeb, 0xb7, 0x50, 0xaf, 0x93, 0xa6, 0x06, 0xdf, 0x5a, 0xd1, 0x60, 0x0f, 0xfa, 0x8c, 0x2e,
	0xd2, 0xe8, 0x38, 0xf2, 0x6e, 0xcb, 0xdc, 0xcc, 0xa1, 0xa1, 0xae, 0x77, 0x4c, 0x75, 0x1d, 0xa5,
	0xd0, 0x0d, 0x70, 0x7a, 0x2e, 0x58, 0xd3, 0x38, 0x3c, 0x3f, 0x31, 0xc6, 0x9d, 0x1c, 0x8b, 0x62,
	0xc1, 0x17, 0x58, 0xe8, 0x00, 0x9b, 0xe9, 0xa2, 0x2c, 0x0d, 0x86, 0xd2, 0x58, 0xa6, 0xd2, 0x94,
	0x63, 0x4e, 0xd7, 0x18, 0x73, 0x46, 0x21, 0xb8, 0xc6, 0xc9, 0xfc, 0x83, 0xc7, 0x8e, 0xc0, 0x89,
	0x39, 0x49, 0x4e, 0xca, 0xa9, 0xab, 0xc0, 0x9f, 0xdb, 0xc2, 0x27, 0xd4, 0x16, 0x46, 0xef, 0x3b,
	0x30, 0x28, 0x4a, 0x1e, 0xed, 0xc0, 0x56, 0xf1, 0xe0, 0xad, 0x38, 0x12, 0x13, 0x7b, 0x48, 0x17,
	0x73, 0x9a, 0x9e, 0x94, 0x81, 0x32, 0x2c, 0xe2, 0x04, 0x14, 0x3a, 0x4e, 0xa6, 0x3a, 0x62, 0xa5,
	0xa1, 0xf4, 0x7e, 0x4a, 0xb2, 0x30, 0x9f, 0xf7, 0x4b, 0x8b, 0x58, 0xd3, 0x25, 0x89, 0xa7, 0x6f,
	0xb9, 0x9e, 0xc5, 0x35, 0x92, 0xb9, 0xcb, 0x69, 0x78, 0x9e, 0x0f, 0xe3, 0x12, 0xf8, 0xef, 0xdd,
	0x6a, 0x03, 0x9b, 0x6c, 0xd0, 0xc0, 0xcc, 0x69, 0xcb, 0x6a, 0x9c, 0xb6, 0xba, 0x95, 0x69, 0xab,
	0xb1, 0x75, 0xad, 0x19, 0x59, 0xcd, 0x56, 0xd8, 0x5f, 0x69, 0x85, 0x42, 0x1d, 0x16, 0xa9, 0xbc,
	0xe4, 0x68, 0x75, 0x50, 0x70, 0xb5, 0x55, 0x0c, 0x9a, 0x04, 0x7a, 0xb2, 0x41, 0xab, 0x80, 0x8d,
	0x48, 0x1a, 0x5a, 0x85, 0xbb, 0x11, 0x49, 0x53, 0xab, 0x18, 0x36, 0xe9, 0xec, 0xa4, 0x7d, 0xab,
	0xd8, 0x6e, 0xd2, 0xfa, 0x49, 0xab, 0x56, 0xb1, 0xd3, 0xda, 0xbd, 0xbe, 0x55, 0xdc, 0x58, 0xbf,
	0x85, 0xfa, 0x56, 0xf1, 0x18, 0x20, 0x5b, 0xa6, 0xa1, 0xcc, 0x8c, 0xbc, 0xd9, 0xad, 0x8d, 0xa5,
	0xbc, 0x33, 0x30, 0x9c, 0xcc, 0x8e, 0x72, 0xb3, 0xa9, 0xa3, 0xa0, 0xd5, 0x79, 0xbd, 0x18, 0x90,
	0x6e, 0x55, 0x07, 0xa4, 0xd1, 0x03, 0x55, 0xea, 0x2a, 0x55, 0x6b, 0xf5, 0x50, 0xbe, 0xae, 0x8a,
	0xba, 0x19, 0xaa, 0xd7, 0xd5, 0xcf, 0x22, 0xfa, 0xef, 0x12, 0xd1, 0x8f, 0x32, 0x00, 0xf8, 0xef,
	0xec, 0xca, 0x77, 0x86, 0xc9, 0x47, 0x79, 0xd3, 0x30, 0xe4, 0xb5, 0x57, 0x95, 0xd7, 0x3c, 0xb9,
	0xec, 0xda, 0xe4, 0xea, 0x57, 0x92, 0xcb, 0xf8, 0xe6, 0xe0, 0x34, 0x7c, 0x73, 0xf8, 0x80, 0xe2,
	0x68, 0xc5, 0x18, 0x34, 0xbc, 0x83, 0xaf, 0x13, 0x8c, 0xef, 0x2a, 0x82, 0x51, 0xf3, 0xde, 0x61,
	0x30, 0xd4, 0xeb, 0x45, 0xa9, 0x0a, 0x6e, 0xa3, 0x2a, 0x0c, 0x3f, 0xab, 0xc2, 0xc7, 0x79, 0xe3,
	0xfe, 0xb3, 0x23, 0x07, 0x96, 0xc9, 0x32, 0x0d, 0x55, 0xb0, 0x9e, 0x62, 0x8e, 0x6b, 0x56, 0x30,
	0x02, 0xe7, 0x0d, 0xbd, 0x3a, 0xa4, 0x8b, 0x94, 0xeb, 0x49, 0xb8, 0xc0, 0xe5, 0x18, 0x6f, 0x99,
	0x5f, 0x2b, 0xef, 0x01, 0xcc, 0xe9, 0x7c, 0x31, 0xc3, 0x2c, 0xe6, 0x4b, 0x3d, 0x13, 0x1b, 0x16,
	0xe4, 0xc3, 0x70, 0x46, 0xce, 0xf8, 0xf3, 0xfc, 0x15, 0x5b, 0x29, 0x43, 0xc5, 0x86, 0xbe, 0x82,
	0xdd, 0x04, 0x5f, 0xbd, 0x2c, 0x9c, 0x44, 0x04, 0x6c, 0xb9, 0xa8, 0x6b, 0x76, 0x34, 0x06, 0x77,
	0xae, 0x8f, 0x3b, 0x22, 0x57, 0x3a, 0xc2, 0xa6, 0xc9, 0x7f, 0xaf, 0xf6, 0xfa, 0x1c, 0x27, 0x01,
	0x4e, 0xa3, 0x5c, 0x09, 0xdb, 0xd5, 0xbc, 0xd2, 0x4b, 0xab, 0x41, 0x2f, 0xbb, 0xeb, 0xf5, 0xb2,
	0xb7, 0x5e, 0x2f, 0xed, 0x55, 0xbd, 0xf4, 0x7f, 0xab, 0x7e, 0x04, 0x3d, 0xdd, 0x6c, 0x8a, 0x2c,
	0xe4, 0xc7, 0x6a, 0x96, 0x9f, 0x6e, 0xbd, 0xfc, 0xb4, 0xc9, 0xe2, 0x16, 0x9f, 0x3c, 0x4f, 0x1b,
	0xe5, 0xa7, 0x2a, 0x1f, 0x4e, 0x83, 0x7c, 0x9c, 0xb6, 0x92, 0x8f, 0x41, 0x45, 0x3e, 0x9e, 0x54,
	0x07, 0x54, 0xf8, 0x20, 0x75, 0xcd, 0x7c, 0xfa, 0xa4, 0x3a, 0x9f, 0xba, 0x9b, 0x70, 0x1c, 0x54,
	0x39, 0x1e, 0x56, 0x3e, 0x87, 0xb4, 0xe4, 0xc8, 0xa7, 0x53, 0x53, 0x0a, 0xb7, 0xff, 0x53, 0x52,
	0xf8, 0xc9, 0x4c, 0x29, 0x6f, 0x6c, 0xf9, 0xdf, 0xa9, 0x87, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff,
	0xff, 0x1e, 0xa9, 0xaa, 0xaa, 0x1a, 0x00, 0x00,
}
