// Code generated by protoc-gen-go. DO NOT EDIT.
// source: res.proto

package SimonProto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResModelArea struct {
	AreaId               int32    `protobuf:"varint,1,opt,name=areaId,proto3" json:"areaId,omitempty"`
	AreaName             string   `protobuf:"bytes,2,opt,name=areaName,proto3" json:"areaName,omitempty"`
	AreaState            int32    `protobuf:"varint,3,opt,name=areaState,proto3" json:"areaState,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResModelArea) Reset()         { *m = ResModelArea{} }
func (m *ResModelArea) String() string { return proto.CompactTextString(m) }
func (*ResModelArea) ProtoMessage()    {}
func (*ResModelArea) Descriptor() ([]byte, []int) {
	return fileDescriptor_36bffc8626f07b47, []int{0}
}

func (m *ResModelArea) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResModelArea.Unmarshal(m, b)
}
func (m *ResModelArea) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResModelArea.Marshal(b, m, deterministic)
}
func (m *ResModelArea) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResModelArea.Merge(m, src)
}
func (m *ResModelArea) XXX_Size() int {
	return xxx_messageInfo_ResModelArea.Size(m)
}
func (m *ResModelArea) XXX_DiscardUnknown() {
	xxx_messageInfo_ResModelArea.DiscardUnknown(m)
}

var xxx_messageInfo_ResModelArea proto.InternalMessageInfo

func (m *ResModelArea) GetAreaId() int32 {
	if m != nil {
		return m.AreaId
	}
	return 0
}

func (m *ResModelArea) GetAreaName() string {
	if m != nil {
		return m.AreaName
	}
	return ""
}

func (m *ResModelArea) GetAreaState() int32 {
	if m != nil {
		return m.AreaState
	}
	return 0
}

type ResGateGetConnector struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	ErrorMsg             string   `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
	Host                 string   `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Port                 int32    `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResGateGetConnector) Reset()         { *m = ResGateGetConnector{} }
func (m *ResGateGetConnector) String() string { return proto.CompactTextString(m) }
func (*ResGateGetConnector) ProtoMessage()    {}
func (*ResGateGetConnector) Descriptor() ([]byte, []int) {
	return fileDescriptor_36bffc8626f07b47, []int{1}
}

func (m *ResGateGetConnector) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResGateGetConnector.Unmarshal(m, b)
}
func (m *ResGateGetConnector) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResGateGetConnector.Marshal(b, m, deterministic)
}
func (m *ResGateGetConnector) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResGateGetConnector.Merge(m, src)
}
func (m *ResGateGetConnector) XXX_Size() int {
	return xxx_messageInfo_ResGateGetConnector.Size(m)
}
func (m *ResGateGetConnector) XXX_DiscardUnknown() {
	xxx_messageInfo_ResGateGetConnector.DiscardUnknown(m)
}

var xxx_messageInfo_ResGateGetConnector proto.InternalMessageInfo

func (m *ResGateGetConnector) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResGateGetConnector) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

func (m *ResGateGetConnector) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *ResGateGetConnector) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type ResUserRegister struct {
	Code                 int32           `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	ErrorMsg             string          `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
	Recommended          int32           `protobuf:"varint,3,opt,name=recommended,proto3" json:"recommended,omitempty"`
	Areas                []*ResModelArea `protobuf:"bytes,4,rep,name=areas,proto3" json:"areas,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ResUserRegister) Reset()         { *m = ResUserRegister{} }
func (m *ResUserRegister) String() string { return proto.CompactTextString(m) }
func (*ResUserRegister) ProtoMessage()    {}
func (*ResUserRegister) Descriptor() ([]byte, []int) {
	return fileDescriptor_36bffc8626f07b47, []int{2}
}

func (m *ResUserRegister) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResUserRegister.Unmarshal(m, b)
}
func (m *ResUserRegister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResUserRegister.Marshal(b, m, deterministic)
}
func (m *ResUserRegister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResUserRegister.Merge(m, src)
}
func (m *ResUserRegister) XXX_Size() int {
	return xxx_messageInfo_ResUserRegister.Size(m)
}
func (m *ResUserRegister) XXX_DiscardUnknown() {
	xxx_messageInfo_ResUserRegister.DiscardUnknown(m)
}

var xxx_messageInfo_ResUserRegister proto.InternalMessageInfo

func (m *ResUserRegister) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResUserRegister) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

func (m *ResUserRegister) GetRecommended() int32 {
	if m != nil {
		return m.Recommended
	}
	return 0
}

func (m *ResUserRegister) GetAreas() []*ResModelArea {
	if m != nil {
		return m.Areas
	}
	return nil
}

type ResUserGetAreas struct {
	Code                 int32           `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	ErrorMsg             string          `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
	Recommended          int32           `protobuf:"varint,3,opt,name=recommended,proto3" json:"recommended,omitempty"`
	Areas                []*ResModelArea `protobuf:"bytes,4,rep,name=areas,proto3" json:"areas,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ResUserGetAreas) Reset()         { *m = ResUserGetAreas{} }
func (m *ResUserGetAreas) String() string { return proto.CompactTextString(m) }
func (*ResUserGetAreas) ProtoMessage()    {}
func (*ResUserGetAreas) Descriptor() ([]byte, []int) {
	return fileDescriptor_36bffc8626f07b47, []int{3}
}

func (m *ResUserGetAreas) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResUserGetAreas.Unmarshal(m, b)
}
func (m *ResUserGetAreas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResUserGetAreas.Marshal(b, m, deterministic)
}
func (m *ResUserGetAreas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResUserGetAreas.Merge(m, src)
}
func (m *ResUserGetAreas) XXX_Size() int {
	return xxx_messageInfo_ResUserGetAreas.Size(m)
}
func (m *ResUserGetAreas) XXX_DiscardUnknown() {
	xxx_messageInfo_ResUserGetAreas.DiscardUnknown(m)
}

var xxx_messageInfo_ResUserGetAreas proto.InternalMessageInfo

func (m *ResUserGetAreas) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResUserGetAreas) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

func (m *ResUserGetAreas) GetRecommended() int32 {
	if m != nil {
		return m.Recommended
	}
	return 0
}

func (m *ResUserGetAreas) GetAreas() []*ResModelArea {
	if m != nil {
		return m.Areas
	}
	return nil
}

type ResUserSelectArea struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	ErrorMsg             string   `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
	PersonalDataString   string   `protobuf:"bytes,3,opt,name=personalDataString,proto3" json:"personalDataString,omitempty"`
	ServerTime           string   `protobuf:"bytes,4,opt,name=serverTime,proto3" json:"serverTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResUserSelectArea) Reset()         { *m = ResUserSelectArea{} }
func (m *ResUserSelectArea) String() string { return proto.CompactTextString(m) }
func (*ResUserSelectArea) ProtoMessage()    {}
func (*ResUserSelectArea) Descriptor() ([]byte, []int) {
	return fileDescriptor_36bffc8626f07b47, []int{4}
}

func (m *ResUserSelectArea) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResUserSelectArea.Unmarshal(m, b)
}
func (m *ResUserSelectArea) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResUserSelectArea.Marshal(b, m, deterministic)
}
func (m *ResUserSelectArea) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResUserSelectArea.Merge(m, src)
}
func (m *ResUserSelectArea) XXX_Size() int {
	return xxx_messageInfo_ResUserSelectArea.Size(m)
}
func (m *ResUserSelectArea) XXX_DiscardUnknown() {
	xxx_messageInfo_ResUserSelectArea.DiscardUnknown(m)
}

var xxx_messageInfo_ResUserSelectArea proto.InternalMessageInfo

func (m *ResUserSelectArea) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResUserSelectArea) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

func (m *ResUserSelectArea) GetPersonalDataString() string {
	if m != nil {
		return m.PersonalDataString
	}
	return ""
}

func (m *ResUserSelectArea) GetServerTime() string {
	if m != nil {
		return m.ServerTime
	}
	return ""
}

func init() {
	proto.RegisterType((*ResModelArea)(nil), "SimonProto.ResModelArea")
	proto.RegisterType((*ResGateGetConnector)(nil), "SimonProto.ResGateGetConnector")
	proto.RegisterType((*ResUserRegister)(nil), "SimonProto.ResUserRegister")
	proto.RegisterType((*ResUserGetAreas)(nil), "SimonProto.ResUserGetAreas")
	proto.RegisterType((*ResUserSelectArea)(nil), "SimonProto.ResUserSelectArea")
}

func init() { proto.RegisterFile("res.proto", fileDescriptor_36bffc8626f07b47) }

var fileDescriptor_36bffc8626f07b47 = []byte{
	// 300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x52, 0x4f, 0x4b, 0xfb, 0x40,
	0x10, 0x25, 0xbf, 0xfe, 0xe1, 0x97, 0xa9, 0x20, 0xae, 0x20, 0x41, 0x44, 0x42, 0x4f, 0x3d, 0xe5,
	0xa0, 0x9f, 0x40, 0x14, 0x8a, 0x87, 0x8a, 0x6c, 0xf4, 0xee, 0x9a, 0x3c, 0x6a, 0xa0, 0xc9, 0x96,
	0x99, 0xc1, 0x2f, 0xe2, 0x17, 0x96, 0xdd, 0xa6, 0x36, 0x07, 0x2f, 0xbd, 0x79, 0x7b, 0xf3, 0x66,
	0x76, 0xde, 0x9b, 0x99, 0xa5, 0x94, 0x21, 0xc5, 0x96, 0xbd, 0x7a, 0x43, 0x65, 0xd3, 0xfa, 0xee,
	0x39, 0xe0, 0xf9, 0x1b, 0x9d, 0x58, 0xc8, 0xca, 0xd7, 0xd8, 0xdc, 0x31, 0x9c, 0xb9, 0xa0, 0xa9,
	0x63, 0xb8, 0xc7, 0x3a, 0x4b, 0xf2, 0x64, 0x31, 0xb1, 0x7d, 0x64, 0x2e, 0xe9, 0x7f, 0x40, 0x4f,
	0xae, 0x45, 0xf6, 0x2f, 0x4f, 0x16, 0xa9, 0xfd, 0x89, 0xcd, 0x15, 0xa5, 0x01, 0x97, 0xea, 0x14,
	0xd9, 0x28, 0x3e, 0x3b, 0x10, 0xf3, 0x96, 0xce, 0x2d, 0x64, 0xe9, 0x14, 0x4b, 0xe8, 0xbd, 0xef,
	0x3a, 0x54, 0xea, 0xd9, 0x18, 0x1a, 0x57, 0xbe, 0x46, 0x2f, 0x13, 0x71, 0x10, 0x01, 0xb3, 0xe7,
	0x95, 0xac, 0xf7, 0x22, 0xfb, 0x38, 0xd4, 0x7f, 0x78, 0xd1, 0xd8, 0x3f, 0xb5, 0x11, 0x07, 0x6e,
	0xeb, 0x59, 0xb3, 0xf1, 0xae, 0x47, 0xc0, 0xf3, 0xaf, 0x84, 0x4e, 0x2d, 0xe4, 0x55, 0xc0, 0x16,
	0xeb, 0x46, 0x14, 0xc7, 0x6b, 0xe5, 0x34, 0x63, 0x54, 0xbe, 0x6d, 0xd1, 0xd5, 0xa8, 0xfb, 0x91,
	0x86, 0x94, 0x29, 0x68, 0x12, 0x26, 0x94, 0x6c, 0x9c, 0x8f, 0x16, 0xb3, 0x9b, 0xac, 0x38, 0xac,
	0xb4, 0x18, 0xee, 0xd3, 0xee, 0xca, 0x86, 0xae, 0x96, 0xd0, 0x90, 0x91, 0xbf, 0xe1, 0xea, 0xac,
	0x77, 0x55, 0x62, 0x83, 0x2a, 0x1a, 0x3b, 0xda, 0x57, 0x41, 0x66, 0x0b, 0x16, 0xdf, 0xb9, 0xcd,
	0x83, 0x53, 0x57, 0x2a, 0x37, 0xdd, 0xba, 0xbf, 0xd3, 0x2f, 0x19, 0x73, 0x4d, 0x24, 0xe0, 0x4f,
	0xf0, 0x4b, 0xd3, 0x22, 0xde, 0x2e, 0xb5, 0x03, 0xe6, 0x7d, 0x1a, 0x7f, 0xe9, 0xed, 0x77, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x34, 0x32, 0xe5, 0xd4, 0xb2, 0x02, 0x00, 0x00,
}
