// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: push.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SimonProto {

  /// <summary>Holder for reflection information generated from push.proto</summary>
  public static partial class PushReflection {

    #region Descriptor
    /// <summary>File descriptor for push.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PushReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpwdXNoLnByb3RvEgpTaW1vblByb3RvIlcKDFB1c2hNb2RlbE1zZxIQCghm",
            "cm9tVXNlchgBIAEoCRISCgp0YXJnZXRVc2VyGAIgASgJEg8KB2NvbnRlbnQY",
            "AyABKAkSEAoIc2VuZFRpbWUYBCABKAUiNwoKUHVzaE9uQ2hhdBIpCgdtc2dM",
            "aXN0GAEgAygLMhguU2ltb25Qcm90by5QdXNoTW9kZWxNc2diBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::SimonProto.PushModelMsg), global::SimonProto.PushModelMsg.Parser, new[]{ "FromUser", "TargetUser", "Content", "SendTime" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SimonProto.PushOnChat), global::SimonProto.PushOnChat.Parser, new[]{ "MsgList" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class PushModelMsg : pb::IMessage<PushModelMsg> {
    private static readonly pb::MessageParser<PushModelMsg> _parser = new pb::MessageParser<PushModelMsg>(() => new PushModelMsg());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PushModelMsg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SimonProto.PushReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PushModelMsg() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PushModelMsg(PushModelMsg other) : this() {
      fromUser_ = other.fromUser_;
      targetUser_ = other.targetUser_;
      content_ = other.content_;
      sendTime_ = other.sendTime_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PushModelMsg Clone() {
      return new PushModelMsg(this);
    }

    /// <summary>Field number for the "fromUser" field.</summary>
    public const int FromUserFieldNumber = 1;
    private string fromUser_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FromUser {
      get { return fromUser_; }
      set {
        fromUser_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "targetUser" field.</summary>
    public const int TargetUserFieldNumber = 2;
    private string targetUser_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TargetUser {
      get { return targetUser_; }
      set {
        targetUser_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "content" field.</summary>
    public const int ContentFieldNumber = 3;
    private string content_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Content {
      get { return content_; }
      set {
        content_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "sendTime" field.</summary>
    public const int SendTimeFieldNumber = 4;
    private int sendTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int SendTime {
      get { return sendTime_; }
      set {
        sendTime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PushModelMsg);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PushModelMsg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FromUser != other.FromUser) return false;
      if (TargetUser != other.TargetUser) return false;
      if (Content != other.Content) return false;
      if (SendTime != other.SendTime) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (FromUser.Length != 0) hash ^= FromUser.GetHashCode();
      if (TargetUser.Length != 0) hash ^= TargetUser.GetHashCode();
      if (Content.Length != 0) hash ^= Content.GetHashCode();
      if (SendTime != 0) hash ^= SendTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (FromUser.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(FromUser);
      }
      if (TargetUser.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(TargetUser);
      }
      if (Content.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Content);
      }
      if (SendTime != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(SendTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (FromUser.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FromUser);
      }
      if (TargetUser.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TargetUser);
      }
      if (Content.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Content);
      }
      if (SendTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SendTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PushModelMsg other) {
      if (other == null) {
        return;
      }
      if (other.FromUser.Length != 0) {
        FromUser = other.FromUser;
      }
      if (other.TargetUser.Length != 0) {
        TargetUser = other.TargetUser;
      }
      if (other.Content.Length != 0) {
        Content = other.Content;
      }
      if (other.SendTime != 0) {
        SendTime = other.SendTime;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            FromUser = input.ReadString();
            break;
          }
          case 18: {
            TargetUser = input.ReadString();
            break;
          }
          case 26: {
            Content = input.ReadString();
            break;
          }
          case 32: {
            SendTime = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class PushOnChat : pb::IMessage<PushOnChat> {
    private static readonly pb::MessageParser<PushOnChat> _parser = new pb::MessageParser<PushOnChat>(() => new PushOnChat());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PushOnChat> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SimonProto.PushReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PushOnChat() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PushOnChat(PushOnChat other) : this() {
      msgList_ = other.msgList_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PushOnChat Clone() {
      return new PushOnChat(this);
    }

    /// <summary>Field number for the "msgList" field.</summary>
    public const int MsgListFieldNumber = 1;
    private static readonly pb::FieldCodec<global::SimonProto.PushModelMsg> _repeated_msgList_codec
        = pb::FieldCodec.ForMessage(10, global::SimonProto.PushModelMsg.Parser);
    private readonly pbc::RepeatedField<global::SimonProto.PushModelMsg> msgList_ = new pbc::RepeatedField<global::SimonProto.PushModelMsg>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::SimonProto.PushModelMsg> MsgList {
      get { return msgList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PushOnChat);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PushOnChat other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!msgList_.Equals(other.msgList_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= msgList_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      msgList_.WriteTo(output, _repeated_msgList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += msgList_.CalculateSize(_repeated_msgList_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PushOnChat other) {
      if (other == null) {
        return;
      }
      msgList_.Add(other.msgList_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            msgList_.AddEntriesFrom(input, _repeated_msgList_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
