// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SDGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

package conf

import (
    "encoding/json"
    "gameserver-997/server/base/utils"
)

type SDConstant struct {
    Id string
    Players int
    PrepareTime int
    WaitingTime int
    TurnTime int
    Exp int
}

var _SDConstantMap = make(map[string]*SDConstant)
var _SDConstantList = []*SDConstant{}

func init() {
    loadSDConstantData()
}
func loadSDConstantData() {
    data, err := utils.ReadFile("sd_conf/SDConstant.json")
    if err != nil {
        panic(err)
    }
    err = json.Unmarshal(data, &_SDConstantList)
    if err != nil {
        panic(err)
    }
    for _, v := range _SDConstantList {
      _SDConstantMap[v.Id] = v
    }
}
func GetSDConstantList() []*SDConstant {
    return _SDConstantList
}
func GetSDConstantElement(id string) *SDConstant {
    return _SDConstantMap[id]
}